services:
  umineko-city-of-books:
    image: ghcr.io/victoriquemoe/umineko_city_of_books:latest
    container_name: umineko-city-of-books
    restart: unless-stopped
    ports:
      - "2312:4323"
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  glitchtip-postgres:
    image: postgres:18
    container_name: glitchtip-postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - glitchtip-pg-data:/var/lib/postgresql

  glitchtip:
    image: glitchtip/glitchtip:6
    container_name: glitchtip
    restart: unless-stopped
    depends_on:
      - glitchtip-postgres
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.glitchtip
    volumes:
      - glitchtip-uploads:/code/uploads

volumes:
  glitchtip-pg-data:
  glitchtip-uploads:
