services:
  umineko-city-of-books:
    build: .
    container_name: umineko-city-of-books
    restart: unless-stopped
    ports:
      - "2312:4323"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
