// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gameroom

import (
	"context"
	"encoding/json"
	"umineko_city_of_books/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockService
func (_mock *MockService) Accept(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (*dto.GameRoom, error) {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 *dto.GameRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.GameRoom, error)); ok {
		return returnFunc(ctx, roomID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.GameRoom); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockService_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) Accept(ctx interface{}, roomID interface{}, userID interface{}) *MockService_Accept_Call {
	return &MockService_Accept_Call{Call: _e.mock.On("Accept", ctx, roomID, userID)}
}

func (_c *MockService_Accept_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Accept_Call) Return(gameRoom *dto.GameRoom, err error) *MockService_Accept_Call {
	_c.Call.Return(gameRoom, err)
	return _c
}

func (_c *MockService_Accept_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (*dto.GameRoom, error)) *MockService_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function for the type MockService
func (_mock *MockService) Cancel(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) Cancel(ctx interface{}, roomID interface{}, userID interface{}) *MockService_Cancel_Call {
	return &MockService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, roomID, userID)}
}

func (_c *MockService_Cancel_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Cancel_Call) Return(err error) *MockService_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Cancel_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error) *MockService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// CountLive provides a mock function for the type MockService
func (_mock *MockService) CountLive(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountLive")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CountLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountLive'
type MockService_CountLive_Call struct {
	*mock.Call
}

// CountLive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) CountLive(ctx interface{}) *MockService_CountLive_Call {
	return &MockService_CountLive_Call{Call: _e.mock.On("CountLive", ctx)}
}

func (_c *MockService_CountLive_Call) Run(run func(ctx context.Context)) *MockService_CountLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_CountLive_Call) Return(n int, err error) *MockService_CountLive_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_CountLive_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockService_CountLive_Call {
	_c.Call.Return(run)
	return _c
}

// Decline provides a mock function for the type MockService
func (_mock *MockService) Decline(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Decline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Decline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decline'
type MockService_Decline_Call struct {
	*mock.Call
}

// Decline is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) Decline(ctx interface{}, roomID interface{}, userID interface{}) *MockService_Decline_Call {
	return &MockService_Decline_Call{Call: _e.mock.On("Decline", ctx, roomID, userID)}
}

func (_c *MockService_Decline_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_Decline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Decline_Call) Return(err error) *MockService_Decline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Decline_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error) *MockService_Decline_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, roomID uuid.UUID, viewerID uuid.UUID) (*dto.GameRoom, error) {
	ret := _mock.Called(ctx, roomID, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.GameRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.GameRoom, error)); ok {
		return returnFunc(ctx, roomID, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.GameRoom); ok {
		r0 = returnFunc(ctx, roomID, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) Get(ctx interface{}, roomID interface{}, viewerID interface{}) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, roomID, viewerID)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, roomID uuid.UUID, viewerID uuid.UUID)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(gameRoom *dto.GameRoom, err error) *MockService_Get_Call {
	_c.Call.Return(gameRoom, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, viewerID uuid.UUID) (*dto.GameRoom, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpectatorChat provides a mock function for the type MockService
func (_mock *MockService) GetSpectatorChat(ctx context.Context, roomID uuid.UUID) (*dto.SpectatorChatResponse, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetSpectatorChat")
	}

	var r0 *dto.SpectatorChatResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.SpectatorChatResponse, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.SpectatorChatResponse); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SpectatorChatResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetSpectatorChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpectatorChat'
type MockService_GetSpectatorChat_Call struct {
	*mock.Call
}

// GetSpectatorChat is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockService_Expecter) GetSpectatorChat(ctx interface{}, roomID interface{}) *MockService_GetSpectatorChat_Call {
	return &MockService_GetSpectatorChat_Call{Call: _e.mock.On("GetSpectatorChat", ctx, roomID)}
}

func (_c *MockService_GetSpectatorChat_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockService_GetSpectatorChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetSpectatorChat_Call) Return(spectatorChatResponse *dto.SpectatorChatResponse, err error) *MockService_GetSpectatorChat_Call {
	_c.Call.Return(spectatorChatResponse, err)
	return _c
}

func (_c *MockService_GetSpectatorChat_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID) (*dto.SpectatorChatResponse, error)) *MockService_GetSpectatorChat_Call {
	_c.Call.Return(run)
	return _c
}

// HandleClientJoin provides a mock function for the type MockService
func (_mock *MockService) HandleClientJoin(ctx context.Context, userID uuid.UUID, roomID uuid.UUID) {
	_mock.Called(ctx, userID, roomID)
	return
}

// MockService_HandleClientJoin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleClientJoin'
type MockService_HandleClientJoin_Call struct {
	*mock.Call
}

// HandleClientJoin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
func (_e *MockService_Expecter) HandleClientJoin(ctx interface{}, userID interface{}, roomID interface{}) *MockService_HandleClientJoin_Call {
	return &MockService_HandleClientJoin_Call{Call: _e.mock.On("HandleClientJoin", ctx, userID, roomID)}
}

func (_c *MockService_HandleClientJoin_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID)) *MockService_HandleClientJoin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_HandleClientJoin_Call) Return() *MockService_HandleClientJoin_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_HandleClientJoin_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID)) *MockService_HandleClientJoin_Call {
	_c.Run(run)
	return _c
}

// HandleClientLeave provides a mock function for the type MockService
func (_mock *MockService) HandleClientLeave(userID uuid.UUID, roomID uuid.UUID) {
	_mock.Called(userID, roomID)
	return
}

// MockService_HandleClientLeave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleClientLeave'
type MockService_HandleClientLeave_Call struct {
	*mock.Call
}

// HandleClientLeave is a helper method to define mock.On call
//   - userID uuid.UUID
//   - roomID uuid.UUID
func (_e *MockService_Expecter) HandleClientLeave(userID interface{}, roomID interface{}) *MockService_HandleClientLeave_Call {
	return &MockService_HandleClientLeave_Call{Call: _e.mock.On("HandleClientLeave", userID, roomID)}
}

func (_c *MockService_HandleClientLeave_Call) Run(run func(userID uuid.UUID, roomID uuid.UUID)) *MockService_HandleClientLeave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_HandleClientLeave_Call) Return() *MockService_HandleClientLeave_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_HandleClientLeave_Call) RunAndReturn(run func(userID uuid.UUID, roomID uuid.UUID)) *MockService_HandleClientLeave_Call {
	_c.Run(run)
	return _c
}

// Invite provides a mock function for the type MockService
func (_mock *MockService) Invite(ctx context.Context, inviterID uuid.UUID, opponentID uuid.UUID, gameType dto.GameType) (*dto.GameRoom, error) {
	ret := _mock.Called(ctx, inviterID, opponentID, gameType)

	if len(ret) == 0 {
		panic("no return value specified for Invite")
	}

	var r0 *dto.GameRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.GameType) (*dto.GameRoom, error)); ok {
		return returnFunc(ctx, inviterID, opponentID, gameType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.GameType) *dto.GameRoom); ok {
		r0 = returnFunc(ctx, inviterID, opponentID, gameType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.GameType) error); ok {
		r1 = returnFunc(ctx, inviterID, opponentID, gameType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Invite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invite'
type MockService_Invite_Call struct {
	*mock.Call
}

// Invite is a helper method to define mock.On call
//   - ctx context.Context
//   - inviterID uuid.UUID
//   - opponentID uuid.UUID
//   - gameType dto.GameType
func (_e *MockService_Expecter) Invite(ctx interface{}, inviterID interface{}, opponentID interface{}, gameType interface{}) *MockService_Invite_Call {
	return &MockService_Invite_Call{Call: _e.mock.On("Invite", ctx, inviterID, opponentID, gameType)}
}

func (_c *MockService_Invite_Call) Run(run func(ctx context.Context, inviterID uuid.UUID, opponentID uuid.UUID, gameType dto.GameType)) *MockService_Invite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.GameType
		if args[3] != nil {
			arg3 = args[3].(dto.GameType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Invite_Call) Return(gameRoom *dto.GameRoom, err error) *MockService_Invite_Call {
	_c.Call.Return(gameRoom, err)
	return _c
}

func (_c *MockService_Invite_Call) RunAndReturn(run func(ctx context.Context, inviterID uuid.UUID, opponentID uuid.UUID, gameType dto.GameType) (*dto.GameRoom, error)) *MockService_Invite_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, userID uuid.UUID, filter ListFilter) (*dto.GameRoomListResponse, error) {
	ret := _mock.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.GameRoomListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ListFilter) (*dto.GameRoomListResponse, error)); ok {
		return returnFunc(ctx, userID, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ListFilter) *dto.GameRoomListResponse); ok {
		r0 = returnFunc(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameRoomListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ListFilter) error); ok {
		r1 = returnFunc(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - filter ListFilter
func (_e *MockService_Expecter) List(ctx interface{}, userID interface{}, filter interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, userID, filter)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, filter ListFilter)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 ListFilter
		if args[2] != nil {
			arg2 = args[2].(ListFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(gameRoomListResponse *dto.GameRoomListResponse, err error) *MockService_List_Call {
	_c.Call.Return(gameRoomListResponse, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, filter ListFilter) (*dto.GameRoomListResponse, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListFinished provides a mock function for the type MockService
func (_mock *MockService) ListFinished(ctx context.Context, gameType dto.GameType, limit int, offset int) (*dto.GameRoomListResponse, error) {
	ret := _mock.Called(ctx, gameType, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListFinished")
	}

	var r0 *dto.GameRoomListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GameType, int, int) (*dto.GameRoomListResponse, error)); ok {
		return returnFunc(ctx, gameType, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GameType, int, int) *dto.GameRoomListResponse); ok {
		r0 = returnFunc(ctx, gameType, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameRoomListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GameType, int, int) error); ok {
		r1 = returnFunc(ctx, gameType, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListFinished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFinished'
type MockService_ListFinished_Call struct {
	*mock.Call
}

// ListFinished is a helper method to define mock.On call
//   - ctx context.Context
//   - gameType dto.GameType
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListFinished(ctx interface{}, gameType interface{}, limit interface{}, offset interface{}) *MockService_ListFinished_Call {
	return &MockService_ListFinished_Call{Call: _e.mock.On("ListFinished", ctx, gameType, limit, offset)}
}

func (_c *MockService_ListFinished_Call) Run(run func(ctx context.Context, gameType dto.GameType, limit int, offset int)) *MockService_ListFinished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GameType
		if args[1] != nil {
			arg1 = args[1].(dto.GameType)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ListFinished_Call) Return(gameRoomListResponse *dto.GameRoomListResponse, err error) *MockService_ListFinished_Call {
	_c.Call.Return(gameRoomListResponse, err)
	return _c
}

func (_c *MockService_ListFinished_Call) RunAndReturn(run func(ctx context.Context, gameType dto.GameType, limit int, offset int) (*dto.GameRoomListResponse, error)) *MockService_ListFinished_Call {
	_c.Call.Return(run)
	return _c
}

// ListLive provides a mock function for the type MockService
func (_mock *MockService) ListLive(ctx context.Context, gameType dto.GameType, limit int, offset int) (*dto.GameRoomListResponse, error) {
	ret := _mock.Called(ctx, gameType, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListLive")
	}

	var r0 *dto.GameRoomListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GameType, int, int) (*dto.GameRoomListResponse, error)); ok {
		return returnFunc(ctx, gameType, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GameType, int, int) *dto.GameRoomListResponse); ok {
		r0 = returnFunc(ctx, gameType, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameRoomListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GameType, int, int) error); ok {
		r1 = returnFunc(ctx, gameType, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLive'
type MockService_ListLive_Call struct {
	*mock.Call
}

// ListLive is a helper method to define mock.On call
//   - ctx context.Context
//   - gameType dto.GameType
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListLive(ctx interface{}, gameType interface{}, limit interface{}, offset interface{}) *MockService_ListLive_Call {
	return &MockService_ListLive_Call{Call: _e.mock.On("ListLive", ctx, gameType, limit, offset)}
}

func (_c *MockService_ListLive_Call) Run(run func(ctx context.Context, gameType dto.GameType, limit int, offset int)) *MockService_ListLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GameType
		if args[1] != nil {
			arg1 = args[1].(dto.GameType)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ListLive_Call) Return(gameRoomListResponse *dto.GameRoomListResponse, err error) *MockService_ListLive_Call {
	_c.Call.Return(gameRoomListResponse, err)
	return _c
}

func (_c *MockService_ListLive_Call) RunAndReturn(run func(ctx context.Context, gameType dto.GameType, limit int, offset int) (*dto.GameRoomListResponse, error)) *MockService_ListLive_Call {
	_c.Call.Return(run)
	return _c
}

// PostSpectatorChat provides a mock function for the type MockService
func (_mock *MockService) PostSpectatorChat(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, body string) (*dto.SpectatorMessage, error) {
	ret := _mock.Called(ctx, roomID, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for PostSpectatorChat")
	}

	var r0 *dto.SpectatorMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*dto.SpectatorMessage, error)); ok {
		return returnFunc(ctx, roomID, userID, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *dto.SpectatorMessage); ok {
		r0 = returnFunc(ctx, roomID, userID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SpectatorMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, roomID, userID, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_PostSpectatorChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostSpectatorChat'
type MockService_PostSpectatorChat_Call struct {
	*mock.Call
}

// PostSpectatorChat is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockService_Expecter) PostSpectatorChat(ctx interface{}, roomID interface{}, userID interface{}, body interface{}) *MockService_PostSpectatorChat_Call {
	return &MockService_PostSpectatorChat_Call{Call: _e.mock.On("PostSpectatorChat", ctx, roomID, userID, body)}
}

func (_c *MockService_PostSpectatorChat_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, body string)) *MockService_PostSpectatorChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_PostSpectatorChat_Call) Return(spectatorMessage *dto.SpectatorMessage, err error) *MockService_PostSpectatorChat_Call {
	_c.Call.Return(spectatorMessage, err)
	return _c
}

func (_c *MockService_PostSpectatorChat_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, body string) (*dto.SpectatorMessage, error)) *MockService_PostSpectatorChat_Call {
	_c.Call.Return(run)
	return _c
}

// Resign provides a mock function for the type MockService
func (_mock *MockService) Resign(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (*dto.GameRoom, error) {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Resign")
	}

	var r0 *dto.GameRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.GameRoom, error)); ok {
		return returnFunc(ctx, roomID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.GameRoom); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Resign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resign'
type MockService_Resign_Call struct {
	*mock.Call
}

// Resign is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) Resign(ctx interface{}, roomID interface{}, userID interface{}) *MockService_Resign_Call {
	return &MockService_Resign_Call{Call: _e.mock.On("Resign", ctx, roomID, userID)}
}

func (_c *MockService_Resign_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_Resign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Resign_Call) Return(gameRoom *dto.GameRoom, err error) *MockService_Resign_Call {
	_c.Call.Return(gameRoom, err)
	return _c
}

func (_c *MockService_Resign_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (*dto.GameRoom, error)) *MockService_Resign_Call {
	_c.Call.Return(run)
	return _c
}

// Scoreboard provides a mock function for the type MockService
func (_mock *MockService) Scoreboard(ctx context.Context, gameType dto.GameType) (*dto.GameScoreboardResponse, error) {
	ret := _mock.Called(ctx, gameType)

	if len(ret) == 0 {
		panic("no return value specified for Scoreboard")
	}

	var r0 *dto.GameScoreboardResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GameType) (*dto.GameScoreboardResponse, error)); ok {
		return returnFunc(ctx, gameType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GameType) *dto.GameScoreboardResponse); ok {
		r0 = returnFunc(ctx, gameType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameScoreboardResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GameType) error); ok {
		r1 = returnFunc(ctx, gameType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Scoreboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scoreboard'
type MockService_Scoreboard_Call struct {
	*mock.Call
}

// Scoreboard is a helper method to define mock.On call
//   - ctx context.Context
//   - gameType dto.GameType
func (_e *MockService_Expecter) Scoreboard(ctx interface{}, gameType interface{}) *MockService_Scoreboard_Call {
	return &MockService_Scoreboard_Call{Call: _e.mock.On("Scoreboard", ctx, gameType)}
}

func (_c *MockService_Scoreboard_Call) Run(run func(ctx context.Context, gameType dto.GameType)) *MockService_Scoreboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GameType
		if args[1] != nil {
			arg1 = args[1].(dto.GameType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Scoreboard_Call) Return(gameScoreboardResponse *dto.GameScoreboardResponse, err error) *MockService_Scoreboard_Call {
	_c.Call.Return(gameScoreboardResponse, err)
	return _c
}

func (_c *MockService_Scoreboard_Call) RunAndReturn(run func(ctx context.Context, gameType dto.GameType) (*dto.GameScoreboardResponse, error)) *MockService_Scoreboard_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitAction provides a mock function for the type MockService
func (_mock *MockService) SubmitAction(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, action json.RawMessage) (*dto.GameRoom, error) {
	ret := _mock.Called(ctx, roomID, userID, action)

	if len(ret) == 0 {
		panic("no return value specified for SubmitAction")
	}

	var r0 *dto.GameRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, json.RawMessage) (*dto.GameRoom, error)); ok {
		return returnFunc(ctx, roomID, userID, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, json.RawMessage) *dto.GameRoom); ok {
		r0 = returnFunc(ctx, roomID, userID, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GameRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, roomID, userID, action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SubmitAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitAction'
type MockService_SubmitAction_Call struct {
	*mock.Call
}

// SubmitAction is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - action json.RawMessage
func (_e *MockService_Expecter) SubmitAction(ctx interface{}, roomID interface{}, userID interface{}, action interface{}) *MockService_SubmitAction_Call {
	return &MockService_SubmitAction_Call{Call: _e.mock.On("SubmitAction", ctx, roomID, userID, action)}
}

func (_c *MockService_SubmitAction_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, action json.RawMessage)) *MockService_SubmitAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 json.RawMessage
		if args[3] != nil {
			arg3 = args[3].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SubmitAction_Call) Return(gameRoom *dto.GameRoom, err error) *MockService_SubmitAction_Call {
	_c.Call.Return(gameRoom, err)
	return _c
}

func (_c *MockService_SubmitAction_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, action json.RawMessage) (*dto.GameRoom, error)) *MockService_SubmitAction_Call {
	_c.Call.Return(run)
	return _c
}
