// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package admin

import (
	"context"
	"umineko_city_of_books/internal/dto"
	"umineko_city_of_books/internal/role"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AssignVanityRole provides a mock function for the type MockService
func (_mock *MockService) AssignVanityRole(ctx context.Context, actorID uuid.UUID, roleID string, userID uuid.UUID) error {
	ret := _mock.Called(ctx, actorID, roleID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssignVanityRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, actorID, roleID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AssignVanityRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignVanityRole'
type MockService_AssignVanityRole_Call struct {
	*mock.Call
}

// AssignVanityRole is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - roleID string
//   - userID uuid.UUID
func (_e *MockService_Expecter) AssignVanityRole(ctx interface{}, actorID interface{}, roleID interface{}, userID interface{}) *MockService_AssignVanityRole_Call {
	return &MockService_AssignVanityRole_Call{Call: _e.mock.On("AssignVanityRole", ctx, actorID, roleID, userID)}
}

func (_c *MockService_AssignVanityRole_Call) Run(run func(ctx context.Context, actorID uuid.UUID, roleID string, userID uuid.UUID)) *MockService_AssignVanityRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_AssignVanityRole_Call) Return(err error) *MockService_AssignVanityRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AssignVanityRole_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, roleID string, userID uuid.UUID) error) *MockService_AssignVanityRole_Call {
	_c.Call.Return(run)
	return _c
}

// BanUser provides a mock function for the type MockService
func (_mock *MockService) BanUser(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, reason string) error {
	ret := _mock.Called(ctx, actorID, targetID, reason)

	if len(ret) == 0 {
		panic("no return value specified for BanUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, actorID, targetID, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_BanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BanUser'
type MockService_BanUser_Call struct {
	*mock.Call
}

// BanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - targetID uuid.UUID
//   - reason string
func (_e *MockService_Expecter) BanUser(ctx interface{}, actorID interface{}, targetID interface{}, reason interface{}) *MockService_BanUser_Call {
	return &MockService_BanUser_Call{Call: _e.mock.On("BanUser", ctx, actorID, targetID, reason)}
}

func (_c *MockService_BanUser_Call) Run(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, reason string)) *MockService_BanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_BanUser_Call) Return(err error) *MockService_BanUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_BanUser_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, reason string) error) *MockService_BanUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvite provides a mock function for the type MockService
func (_mock *MockService) CreateInvite(ctx context.Context, actorID uuid.UUID) (*dto.InviteResponse, error) {
	ret := _mock.Called(ctx, actorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvite")
	}

	var r0 *dto.InviteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.InviteResponse, error)); ok {
		return returnFunc(ctx, actorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.InviteResponse); ok {
		r0 = returnFunc(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.InviteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvite'
type MockService_CreateInvite_Call struct {
	*mock.Call
}

// CreateInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
func (_e *MockService_Expecter) CreateInvite(ctx interface{}, actorID interface{}) *MockService_CreateInvite_Call {
	return &MockService_CreateInvite_Call{Call: _e.mock.On("CreateInvite", ctx, actorID)}
}

func (_c *MockService_CreateInvite_Call) Run(run func(ctx context.Context, actorID uuid.UUID)) *MockService_CreateInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateInvite_Call) Return(inviteResponse *dto.InviteResponse, err error) *MockService_CreateInvite_Call {
	_c.Call.Return(inviteResponse, err)
	return _c
}

func (_c *MockService_CreateInvite_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID) (*dto.InviteResponse, error)) *MockService_CreateInvite_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVanityRole provides a mock function for the type MockService
func (_mock *MockService) CreateVanityRole(ctx context.Context, actorID uuid.UUID, req dto.CreateVanityRoleRequest) (*dto.VanityRoleResponse, error) {
	ret := _mock.Called(ctx, actorID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateVanityRole")
	}

	var r0 *dto.VanityRoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateVanityRoleRequest) (*dto.VanityRoleResponse, error)); ok {
		return returnFunc(ctx, actorID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateVanityRoleRequest) *dto.VanityRoleResponse); ok {
		r0 = returnFunc(ctx, actorID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VanityRoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateVanityRoleRequest) error); ok {
		r1 = returnFunc(ctx, actorID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateVanityRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVanityRole'
type MockService_CreateVanityRole_Call struct {
	*mock.Call
}

// CreateVanityRole is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - req dto.CreateVanityRoleRequest
func (_e *MockService_Expecter) CreateVanityRole(ctx interface{}, actorID interface{}, req interface{}) *MockService_CreateVanityRole_Call {
	return &MockService_CreateVanityRole_Call{Call: _e.mock.On("CreateVanityRole", ctx, actorID, req)}
}

func (_c *MockService_CreateVanityRole_Call) Run(run func(ctx context.Context, actorID uuid.UUID, req dto.CreateVanityRoleRequest)) *MockService_CreateVanityRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.CreateVanityRoleRequest
		if args[2] != nil {
			arg2 = args[2].(dto.CreateVanityRoleRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateVanityRole_Call) Return(vanityRoleResponse *dto.VanityRoleResponse, err error) *MockService_CreateVanityRole_Call {
	_c.Call.Return(vanityRoleResponse, err)
	return _c
}

func (_c *MockService_CreateVanityRole_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, req dto.CreateVanityRoleRequest) (*dto.VanityRoleResponse, error)) *MockService_CreateVanityRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInvite provides a mock function for the type MockService
func (_mock *MockService) DeleteInvite(ctx context.Context, actorID uuid.UUID, code string) error {
	ret := _mock.Called(ctx, actorID, code)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, actorID, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInvite'
type MockService_DeleteInvite_Call struct {
	*mock.Call
}

// DeleteInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - code string
func (_e *MockService_Expecter) DeleteInvite(ctx interface{}, actorID interface{}, code interface{}) *MockService_DeleteInvite_Call {
	return &MockService_DeleteInvite_Call{Call: _e.mock.On("DeleteInvite", ctx, actorID, code)}
}

func (_c *MockService_DeleteInvite_Call) Run(run func(ctx context.Context, actorID uuid.UUID, code string)) *MockService_DeleteInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteInvite_Call) Return(err error) *MockService_DeleteInvite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteInvite_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, code string) error) *MockService_DeleteInvite_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockService
func (_mock *MockService) DeleteUser(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID) error {
	ret := _mock.Called(ctx, actorID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, actorID, targetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - targetID uuid.UUID
func (_e *MockService_Expecter) DeleteUser(ctx interface{}, actorID interface{}, targetID interface{}) *MockService_DeleteUser_Call {
	return &MockService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, actorID, targetID)}
}

func (_c *MockService_DeleteUser_Call) Run(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID)) *MockService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteUser_Call) Return(err error) *MockService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID) error) *MockService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVanityRole provides a mock function for the type MockService
func (_mock *MockService) DeleteVanityRole(ctx context.Context, actorID uuid.UUID, id string) error {
	ret := _mock.Called(ctx, actorID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVanityRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, actorID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteVanityRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVanityRole'
type MockService_DeleteVanityRole_Call struct {
	*mock.Call
}

// DeleteVanityRole is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - id string
func (_e *MockService_Expecter) DeleteVanityRole(ctx interface{}, actorID interface{}, id interface{}) *MockService_DeleteVanityRole_Call {
	return &MockService_DeleteVanityRole_Call{Call: _e.mock.On("DeleteVanityRole", ctx, actorID, id)}
}

func (_c *MockService_DeleteVanityRole_Call) Run(run func(ctx context.Context, actorID uuid.UUID, id string)) *MockService_DeleteVanityRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteVanityRole_Call) Return(err error) *MockService_DeleteVanityRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteVanityRole_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, id string) error) *MockService_DeleteVanityRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuditLog provides a mock function for the type MockService
func (_mock *MockService) GetAuditLog(ctx context.Context, action string, limit int, offset int) (*dto.AuditLogListResponse, error) {
	ret := _mock.Called(ctx, action, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditLog")
	}

	var r0 *dto.AuditLogListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (*dto.AuditLogListResponse, error)); ok {
		return returnFunc(ctx, action, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) *dto.AuditLogListResponse); ok {
		r0 = returnFunc(ctx, action, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuditLogListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, action, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuditLog'
type MockService_GetAuditLog_Call struct {
	*mock.Call
}

// GetAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - action string
//   - limit int
//   - offset int
func (_e *MockService_Expecter) GetAuditLog(ctx interface{}, action interface{}, limit interface{}, offset interface{}) *MockService_GetAuditLog_Call {
	return &MockService_GetAuditLog_Call{Call: _e.mock.On("GetAuditLog", ctx, action, limit, offset)}
}

func (_c *MockService_GetAuditLog_Call) Run(run func(ctx context.Context, action string, limit int, offset int)) *MockService_GetAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_GetAuditLog_Call) Return(auditLogListResponse *dto.AuditLogListResponse, err error) *MockService_GetAuditLog_Call {
	_c.Call.Return(auditLogListResponse, err)
	return _c
}

func (_c *MockService_GetAuditLog_Call) RunAndReturn(run func(ctx context.Context, action string, limit int, offset int) (*dto.AuditLogListResponse, error)) *MockService_GetAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// GetSettings provides a mock function for the type MockService
func (_mock *MockService) GetSettings(ctx context.Context) (*dto.SettingsResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSettings")
	}

	var r0 *dto.SettingsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*dto.SettingsResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *dto.SettingsResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SettingsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSettings'
type MockService_GetSettings_Call struct {
	*mock.Call
}

// GetSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetSettings(ctx interface{}) *MockService_GetSettings_Call {
	return &MockService_GetSettings_Call{Call: _e.mock.On("GetSettings", ctx)}
}

func (_c *MockService_GetSettings_Call) Run(run func(ctx context.Context)) *MockService_GetSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetSettings_Call) Return(settingsResponse *dto.SettingsResponse, err error) *MockService_GetSettings_Call {
	_c.Call.Return(settingsResponse, err)
	return _c
}

func (_c *MockService_GetSettings_Call) RunAndReturn(run func(ctx context.Context) (*dto.SettingsResponse, error)) *MockService_GetSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockService
func (_mock *MockService) GetStats(ctx context.Context) (*dto.AdminStatsResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *dto.AdminStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*dto.AdminStatsResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *dto.AdminStatsResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AdminStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockService_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetStats(ctx interface{}) *MockService_GetStats_Call {
	return &MockService_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockService_GetStats_Call) Run(run func(ctx context.Context)) *MockService_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetStats_Call) Return(adminStatsResponse *dto.AdminStatsResponse, err error) *MockService_GetStats_Call {
	_c.Call.Return(adminStatsResponse, err)
	return _c
}

func (_c *MockService_GetStats_Call) RunAndReturn(run func(ctx context.Context) (*dto.AdminStatsResponse, error)) *MockService_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockService
func (_mock *MockService) GetUser(ctx context.Context, targetID uuid.UUID) (*dto.AdminUserDetailResponse, error) {
	ret := _mock.Called(ctx, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *dto.AdminUserDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.AdminUserDetailResponse, error)); ok {
		return returnFunc(ctx, targetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.AdminUserDetailResponse); ok {
		r0 = returnFunc(ctx, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AdminUserDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, targetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - targetID uuid.UUID
func (_e *MockService_Expecter) GetUser(ctx interface{}, targetID interface{}) *MockService_GetUser_Call {
	return &MockService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, targetID)}
}

func (_c *MockService_GetUser_Call) Run(run func(ctx context.Context, targetID uuid.UUID)) *MockService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetUser_Call) Return(adminUserDetailResponse *dto.AdminUserDetailResponse, err error) *MockService_GetUser_Call {
	_c.Call.Return(adminUserDetailResponse, err)
	return _c
}

func (_c *MockService_GetUser_Call) RunAndReturn(run func(ctx context.Context, targetID uuid.UUID) (*dto.AdminUserDetailResponse, error)) *MockService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetVanityRoleUsers provides a mock function for the type MockService
func (_mock *MockService) GetVanityRoleUsers(ctx context.Context, roleID string, search string, limit int, offset int) (*dto.VanityRoleUsersResponse, error) {
	ret := _mock.Called(ctx, roleID, search, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetVanityRoleUsers")
	}

	var r0 *dto.VanityRoleUsersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) (*dto.VanityRoleUsersResponse, error)); ok {
		return returnFunc(ctx, roleID, search, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) *dto.VanityRoleUsersResponse); ok {
		r0 = returnFunc(ctx, roleID, search, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.VanityRoleUsersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, roleID, search, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetVanityRoleUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVanityRoleUsers'
type MockService_GetVanityRoleUsers_Call struct {
	*mock.Call
}

// GetVanityRoleUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID string
//   - search string
//   - limit int
//   - offset int
func (_e *MockService_Expecter) GetVanityRoleUsers(ctx interface{}, roleID interface{}, search interface{}, limit interface{}, offset interface{}) *MockService_GetVanityRoleUsers_Call {
	return &MockService_GetVanityRoleUsers_Call{Call: _e.mock.On("GetVanityRoleUsers", ctx, roleID, search, limit, offset)}
}

func (_c *MockService_GetVanityRoleUsers_Call) Run(run func(ctx context.Context, roleID string, search string, limit int, offset int)) *MockService_GetVanityRoleUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_GetVanityRoleUsers_Call) Return(vanityRoleUsersResponse *dto.VanityRoleUsersResponse, err error) *MockService_GetVanityRoleUsers_Call {
	_c.Call.Return(vanityRoleUsersResponse, err)
	return _c
}

func (_c *MockService_GetVanityRoleUsers_Call) RunAndReturn(run func(ctx context.Context, roleID string, search string, limit int, offset int) (*dto.VanityRoleUsersResponse, error)) *MockService_GetVanityRoleUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvites provides a mock function for the type MockService
func (_mock *MockService) ListInvites(ctx context.Context, limit int, offset int) (*dto.InviteListResponse, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListInvites")
	}

	var r0 *dto.InviteListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*dto.InviteListResponse, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *dto.InviteListResponse); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.InviteListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvites'
type MockService_ListInvites_Call struct {
	*mock.Call
}

// ListInvites is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListInvites(ctx interface{}, limit interface{}, offset interface{}) *MockService_ListInvites_Call {
	return &MockService_ListInvites_Call{Call: _e.mock.On("ListInvites", ctx, limit, offset)}
}

func (_c *MockService_ListInvites_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockService_ListInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListInvites_Call) Return(inviteListResponse *dto.InviteListResponse, err error) *MockService_ListInvites_Call {
	_c.Call.Return(inviteListResponse, err)
	return _c
}

func (_c *MockService_ListInvites_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) (*dto.InviteListResponse, error)) *MockService_ListInvites_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockService
func (_mock *MockService) ListUsers(ctx context.Context, search string, limit int, offset int) (*dto.AdminUserListResponse, error) {
	ret := _mock.Called(ctx, search, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *dto.AdminUserListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (*dto.AdminUserListResponse, error)); ok {
		return returnFunc(ctx, search, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) *dto.AdminUserListResponse); ok {
		r0 = returnFunc(ctx, search, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AdminUserListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, search, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListUsers(ctx interface{}, search interface{}, limit interface{}, offset interface{}) *MockService_ListUsers_Call {
	return &MockService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, search, limit, offset)}
}

func (_c *MockService_ListUsers_Call) Run(run func(ctx context.Context, search string, limit int, offset int)) *MockService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ListUsers_Call) Return(adminUserListResponse *dto.AdminUserListResponse, err error) *MockService_ListUsers_Call {
	_c.Call.Return(adminUserListResponse, err)
	return _c
}

func (_c *MockService_ListUsers_Call) RunAndReturn(run func(ctx context.Context, search string, limit int, offset int) (*dto.AdminUserListResponse, error)) *MockService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ListVanityRoles provides a mock function for the type MockService
func (_mock *MockService) ListVanityRoles(ctx context.Context) ([]dto.VanityRoleResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListVanityRoles")
	}

	var r0 []dto.VanityRoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.VanityRoleResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.VanityRoleResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.VanityRoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListVanityRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVanityRoles'
type MockService_ListVanityRoles_Call struct {
	*mock.Call
}

// ListVanityRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListVanityRoles(ctx interface{}) *MockService_ListVanityRoles_Call {
	return &MockService_ListVanityRoles_Call{Call: _e.mock.On("ListVanityRoles", ctx)}
}

func (_c *MockService_ListVanityRoles_Call) Run(run func(ctx context.Context)) *MockService_ListVanityRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListVanityRoles_Call) Return(vanityRoleResponses []dto.VanityRoleResponse, err error) *MockService_ListVanityRoles_Call {
	_c.Call.Return(vanityRoleResponses, err)
	return _c
}

func (_c *MockService_ListVanityRoles_Call) RunAndReturn(run func(ctx context.Context) ([]dto.VanityRoleResponse, error)) *MockService_ListVanityRoles_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserRole provides a mock function for the type MockService
func (_mock *MockService) RemoveUserRole(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, r role.Role) error {
	ret := _mock.Called(ctx, actorID, targetID, r)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, role.Role) error); ok {
		r0 = returnFunc(ctx, actorID, targetID, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserRole'
type MockService_RemoveUserRole_Call struct {
	*mock.Call
}

// RemoveUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - targetID uuid.UUID
//   - r role.Role
func (_e *MockService_Expecter) RemoveUserRole(ctx interface{}, actorID interface{}, targetID interface{}, r interface{}) *MockService_RemoveUserRole_Call {
	return &MockService_RemoveUserRole_Call{Call: _e.mock.On("RemoveUserRole", ctx, actorID, targetID, r)}
}

func (_c *MockService_RemoveUserRole_Call) Run(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, r role.Role)) *MockService_RemoveUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 role.Role
		if args[3] != nil {
			arg3 = args[3].(role.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_RemoveUserRole_Call) Return(err error) *MockService_RemoveUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveUserRole_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, r role.Role) error) *MockService_RemoveUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserRole provides a mock function for the type MockService
func (_mock *MockService) SetUserRole(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, r role.Role) error {
	ret := _mock.Called(ctx, actorID, targetID, r)

	if len(ret) == 0 {
		panic("no return value specified for SetUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, role.Role) error); ok {
		r0 = returnFunc(ctx, actorID, targetID, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserRole'
type MockService_SetUserRole_Call struct {
	*mock.Call
}

// SetUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - targetID uuid.UUID
//   - r role.Role
func (_e *MockService_Expecter) SetUserRole(ctx interface{}, actorID interface{}, targetID interface{}, r interface{}) *MockService_SetUserRole_Call {
	return &MockService_SetUserRole_Call{Call: _e.mock.On("SetUserRole", ctx, actorID, targetID, r)}
}

func (_c *MockService_SetUserRole_Call) Run(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, r role.Role)) *MockService_SetUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 role.Role
		if args[3] != nil {
			arg3 = args[3].(role.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SetUserRole_Call) Return(err error) *MockService_SetUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetUserRole_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID, r role.Role) error) *MockService_SetUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// UnassignVanityRole provides a mock function for the type MockService
func (_mock *MockService) UnassignVanityRole(ctx context.Context, actorID uuid.UUID, roleID string, userID uuid.UUID) error {
	ret := _mock.Called(ctx, actorID, roleID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnassignVanityRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, actorID, roleID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UnassignVanityRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnassignVanityRole'
type MockService_UnassignVanityRole_Call struct {
	*mock.Call
}

// UnassignVanityRole is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - roleID string
//   - userID uuid.UUID
func (_e *MockService_Expecter) UnassignVanityRole(ctx interface{}, actorID interface{}, roleID interface{}, userID interface{}) *MockService_UnassignVanityRole_Call {
	return &MockService_UnassignVanityRole_Call{Call: _e.mock.On("UnassignVanityRole", ctx, actorID, roleID, userID)}
}

func (_c *MockService_UnassignVanityRole_Call) Run(run func(ctx context.Context, actorID uuid.UUID, roleID string, userID uuid.UUID)) *MockService_UnassignVanityRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UnassignVanityRole_Call) Return(err error) *MockService_UnassignVanityRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UnassignVanityRole_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, roleID string, userID uuid.UUID) error) *MockService_UnassignVanityRole_Call {
	_c.Call.Return(run)
	return _c
}

// UnbanUser provides a mock function for the type MockService
func (_mock *MockService) UnbanUser(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID) error {
	ret := _mock.Called(ctx, actorID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for UnbanUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, actorID, targetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UnbanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnbanUser'
type MockService_UnbanUser_Call struct {
	*mock.Call
}

// UnbanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - targetID uuid.UUID
func (_e *MockService_Expecter) UnbanUser(ctx interface{}, actorID interface{}, targetID interface{}) *MockService_UnbanUser_Call {
	return &MockService_UnbanUser_Call{Call: _e.mock.On("UnbanUser", ctx, actorID, targetID)}
}

func (_c *MockService_UnbanUser_Call) Run(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID)) *MockService_UnbanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UnbanUser_Call) Return(err error) *MockService_UnbanUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UnbanUser_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, targetID uuid.UUID) error) *MockService_UnbanUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSettings provides a mock function for the type MockService
func (_mock *MockService) UpdateSettings(ctx context.Context, actorID uuid.UUID, settings map[string]string) error {
	ret := _mock.Called(ctx, actorID, settings)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]string) error); ok {
		r0 = returnFunc(ctx, actorID, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSettings'
type MockService_UpdateSettings_Call struct {
	*mock.Call
}

// UpdateSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - settings map[string]string
func (_e *MockService_Expecter) UpdateSettings(ctx interface{}, actorID interface{}, settings interface{}) *MockService_UpdateSettings_Call {
	return &MockService_UpdateSettings_Call{Call: _e.mock.On("UpdateSettings", ctx, actorID, settings)}
}

func (_c *MockService_UpdateSettings_Call) Run(run func(ctx context.Context, actorID uuid.UUID, settings map[string]string)) *MockService_UpdateSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateSettings_Call) Return(err error) *MockService_UpdateSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateSettings_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, settings map[string]string) error) *MockService_UpdateSettings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVanityRole provides a mock function for the type MockService
func (_mock *MockService) UpdateVanityRole(ctx context.Context, actorID uuid.UUID, id string, req dto.UpdateVanityRoleRequest) error {
	ret := _mock.Called(ctx, actorID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVanityRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, dto.UpdateVanityRoleRequest) error); ok {
		r0 = returnFunc(ctx, actorID, id, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateVanityRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVanityRole'
type MockService_UpdateVanityRole_Call struct {
	*mock.Call
}

// UpdateVanityRole is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - id string
//   - req dto.UpdateVanityRoleRequest
func (_e *MockService_Expecter) UpdateVanityRole(ctx interface{}, actorID interface{}, id interface{}, req interface{}) *MockService_UpdateVanityRole_Call {
	return &MockService_UpdateVanityRole_Call{Call: _e.mock.On("UpdateVanityRole", ctx, actorID, id, req)}
}

func (_c *MockService_UpdateVanityRole_Call) Run(run func(ctx context.Context, actorID uuid.UUID, id string, req dto.UpdateVanityRoleRequest)) *MockService_UpdateVanityRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 dto.UpdateVanityRoleRequest
		if args[3] != nil {
			arg3 = args[3].(dto.UpdateVanityRoleRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateVanityRole_Call) Return(err error) *MockService_UpdateVanityRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateVanityRole_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, id string, req dto.UpdateVanityRoleRequest) error) *MockService_UpdateVanityRole_Call {
	_c.Call.Return(run)
	return _c
}
