// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnnouncementRepository creates a new instance of MockAnnouncementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnnouncementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnnouncementRepository {
	mock := &MockAnnouncementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnnouncementRepository is an autogenerated mock type for the AnnouncementRepository type
type MockAnnouncementRepository struct {
	mock.Mock
}

type MockAnnouncementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnnouncementRepository) EXPECT() *MockAnnouncementRepository_Expecter {
	return &MockAnnouncementRepository_Expecter{mock: &_m.Mock}
}

// AddCommentMedia provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) AddCommentMedia(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int) (int64, error) {
	ret := _mock.Called(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for AddCommentMedia")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) (int64, error)); ok {
		return returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) int64); ok {
		r0 = returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r1 = returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnnouncementRepository_AddCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCommentMedia'
type MockAnnouncementRepository_AddCommentMedia_Call struct {
	*mock.Call
}

// AddCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - mediaURL string
//   - mediaType string
//   - thumbnailURL string
//   - sortOrder int
func (_e *MockAnnouncementRepository_Expecter) AddCommentMedia(ctx interface{}, commentID interface{}, mediaURL interface{}, mediaType interface{}, thumbnailURL interface{}, sortOrder interface{}) *MockAnnouncementRepository_AddCommentMedia_Call {
	return &MockAnnouncementRepository_AddCommentMedia_Call{Call: _e.mock.On("AddCommentMedia", ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)}
}

func (_c *MockAnnouncementRepository_AddCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int)) *MockAnnouncementRepository_AddCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_AddCommentMedia_Call) Return(n int64, err error) *MockAnnouncementRepository_AddCommentMedia_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAnnouncementRepository_AddCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int) (int64, error)) *MockAnnouncementRepository_AddCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) Create(ctx context.Context, id uuid.UUID, authorID uuid.UUID, title string, body string) error {
	ret := _mock.Called(ctx, id, authorID, title, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, authorID, title, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAnnouncementRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - authorID uuid.UUID
//   - title string
//   - body string
func (_e *MockAnnouncementRepository_Expecter) Create(ctx interface{}, id interface{}, authorID interface{}, title interface{}, body interface{}) *MockAnnouncementRepository_Create_Call {
	return &MockAnnouncementRepository_Create_Call{Call: _e.mock.On("Create", ctx, id, authorID, title, body)}
}

func (_c *MockAnnouncementRepository_Create_Call) Run(run func(ctx context.Context, id uuid.UUID, authorID uuid.UUID, title string, body string)) *MockAnnouncementRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_Create_Call) Return(err error) *MockAnnouncementRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_Create_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, authorID uuid.UUID, title string, body string) error) *MockAnnouncementRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComment provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) CreateComment(ctx context.Context, id uuid.UUID, announcementID uuid.UUID, parentID *uuid.UUID, userID uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, announcementID, parentID, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, announcementID, parentID, userID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockAnnouncementRepository_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - announcementID uuid.UUID
//   - parentID *uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockAnnouncementRepository_Expecter) CreateComment(ctx interface{}, id interface{}, announcementID interface{}, parentID interface{}, userID interface{}, body interface{}) *MockAnnouncementRepository_CreateComment_Call {
	return &MockAnnouncementRepository_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, id, announcementID, parentID, userID, body)}
}

func (_c *MockAnnouncementRepository_CreateComment_Call) Run(run func(ctx context.Context, id uuid.UUID, announcementID uuid.UUID, parentID *uuid.UUID, userID uuid.UUID, body string)) *MockAnnouncementRepository_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_CreateComment_Call) Return(err error) *MockAnnouncementRepository_CreateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_CreateComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, announcementID uuid.UUID, parentID *uuid.UUID, userID uuid.UUID, body string) error) *MockAnnouncementRepository_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAnnouncementRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAnnouncementRepository_Delete_Call {
	return &MockAnnouncementRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAnnouncementRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAnnouncementRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_Delete_Call) Return(err error) *MockAnnouncementRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAnnouncementRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) DeleteComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockAnnouncementRepository_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) DeleteComment(ctx interface{}, id interface{}, userID interface{}) *MockAnnouncementRepository_DeleteComment_Call {
	return &MockAnnouncementRepository_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, id, userID)}
}

func (_c *MockAnnouncementRepository_DeleteComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockAnnouncementRepository_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_DeleteComment_Call) Return(err error) *MockAnnouncementRepository_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockAnnouncementRepository_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCommentAsAdmin provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) DeleteCommentAsAdmin(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCommentAsAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_DeleteCommentAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCommentAsAdmin'
type MockAnnouncementRepository_DeleteCommentAsAdmin_Call struct {
	*mock.Call
}

// DeleteCommentAsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) DeleteCommentAsAdmin(ctx interface{}, id interface{}) *MockAnnouncementRepository_DeleteCommentAsAdmin_Call {
	return &MockAnnouncementRepository_DeleteCommentAsAdmin_Call{Call: _e.mock.On("DeleteCommentAsAdmin", ctx, id)}
}

func (_c *MockAnnouncementRepository_DeleteCommentAsAdmin_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAnnouncementRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_DeleteCommentAsAdmin_Call) Return(err error) *MockAnnouncementRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_DeleteCommentAsAdmin_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAnnouncementRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) GetByID(ctx context.Context, id uuid.UUID) (*AnnouncementRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *AnnouncementRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*AnnouncementRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *AnnouncementRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AnnouncementRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnnouncementRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAnnouncementRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAnnouncementRepository_GetByID_Call {
	return &MockAnnouncementRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAnnouncementRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAnnouncementRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_GetByID_Call) Return(announcementRow *AnnouncementRow, err error) *MockAnnouncementRepository_GetByID_Call {
	_c.Call.Return(announcementRow, err)
	return _c
}

func (_c *MockAnnouncementRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*AnnouncementRow, error)) *MockAnnouncementRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentAnnouncementID provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) GetCommentAnnouncementID(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentAnnouncementID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnnouncementRepository_GetCommentAnnouncementID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentAnnouncementID'
type MockAnnouncementRepository_GetCommentAnnouncementID_Call struct {
	*mock.Call
}

// GetCommentAnnouncementID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) GetCommentAnnouncementID(ctx interface{}, commentID interface{}) *MockAnnouncementRepository_GetCommentAnnouncementID_Call {
	return &MockAnnouncementRepository_GetCommentAnnouncementID_Call{Call: _e.mock.On("GetCommentAnnouncementID", ctx, commentID)}
}

func (_c *MockAnnouncementRepository_GetCommentAnnouncementID_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockAnnouncementRepository_GetCommentAnnouncementID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_GetCommentAnnouncementID_Call) Return(uUID uuid.UUID, err error) *MockAnnouncementRepository_GetCommentAnnouncementID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockAnnouncementRepository_GetCommentAnnouncementID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error)) *MockAnnouncementRepository_GetCommentAnnouncementID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentAuthorID provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) GetCommentAuthorID(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentAuthorID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnnouncementRepository_GetCommentAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentAuthorID'
type MockAnnouncementRepository_GetCommentAuthorID_Call struct {
	*mock.Call
}

// GetCommentAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) GetCommentAuthorID(ctx interface{}, commentID interface{}) *MockAnnouncementRepository_GetCommentAuthorID_Call {
	return &MockAnnouncementRepository_GetCommentAuthorID_Call{Call: _e.mock.On("GetCommentAuthorID", ctx, commentID)}
}

func (_c *MockAnnouncementRepository_GetCommentAuthorID_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockAnnouncementRepository_GetCommentAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_GetCommentAuthorID_Call) Return(uUID uuid.UUID, err error) *MockAnnouncementRepository_GetCommentAuthorID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockAnnouncementRepository_GetCommentAuthorID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error)) *MockAnnouncementRepository_GetCommentAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMediaBatch provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) GetCommentMediaBatch(ctx context.Context, commentIDs []uuid.UUID) (map[uuid.UUID][]AnnouncementCommentMediaRow, error) {
	ret := _mock.Called(ctx, commentIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMediaBatch")
	}

	var r0 map[uuid.UUID][]AnnouncementCommentMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID][]AnnouncementCommentMediaRow, error)); ok {
		return returnFunc(ctx, commentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID][]AnnouncementCommentMediaRow); ok {
		r0 = returnFunc(ctx, commentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]AnnouncementCommentMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnnouncementRepository_GetCommentMediaBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMediaBatch'
type MockAnnouncementRepository_GetCommentMediaBatch_Call struct {
	*mock.Call
}

// GetCommentMediaBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - commentIDs []uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) GetCommentMediaBatch(ctx interface{}, commentIDs interface{}) *MockAnnouncementRepository_GetCommentMediaBatch_Call {
	return &MockAnnouncementRepository_GetCommentMediaBatch_Call{Call: _e.mock.On("GetCommentMediaBatch", ctx, commentIDs)}
}

func (_c *MockAnnouncementRepository_GetCommentMediaBatch_Call) Run(run func(ctx context.Context, commentIDs []uuid.UUID)) *MockAnnouncementRepository_GetCommentMediaBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_GetCommentMediaBatch_Call) Return(uUIDToVs map[uuid.UUID][]AnnouncementCommentMediaRow, err error) *MockAnnouncementRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(uUIDToVs, err)
	return _c
}

func (_c *MockAnnouncementRepository_GetCommentMediaBatch_Call) RunAndReturn(run func(ctx context.Context, commentIDs []uuid.UUID) (map[uuid.UUID][]AnnouncementCommentMediaRow, error)) *MockAnnouncementRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) GetComments(ctx context.Context, announcementID uuid.UUID, viewerID uuid.UUID, limit int, offset int, excludeUserIDs []uuid.UUID) ([]AnnouncementCommentRow, int, error) {
	ret := _mock.Called(ctx, announcementID, viewerID, limit, offset, excludeUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []AnnouncementCommentRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, []uuid.UUID) ([]AnnouncementCommentRow, int, error)); ok {
		return returnFunc(ctx, announcementID, viewerID, limit, offset, excludeUserIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, []uuid.UUID) []AnnouncementCommentRow); ok {
		r0 = returnFunc(ctx, announcementID, viewerID, limit, offset, excludeUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AnnouncementCommentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int, []uuid.UUID) int); ok {
		r1 = returnFunc(ctx, announcementID, viewerID, limit, offset, excludeUserIDs)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int, []uuid.UUID) error); ok {
		r2 = returnFunc(ctx, announcementID, viewerID, limit, offset, excludeUserIDs)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAnnouncementRepository_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockAnnouncementRepository_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - announcementID uuid.UUID
//   - viewerID uuid.UUID
//   - limit int
//   - offset int
//   - excludeUserIDs []uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) GetComments(ctx interface{}, announcementID interface{}, viewerID interface{}, limit interface{}, offset interface{}, excludeUserIDs interface{}) *MockAnnouncementRepository_GetComments_Call {
	return &MockAnnouncementRepository_GetComments_Call{Call: _e.mock.On("GetComments", ctx, announcementID, viewerID, limit, offset, excludeUserIDs)}
}

func (_c *MockAnnouncementRepository_GetComments_Call) Run(run func(ctx context.Context, announcementID uuid.UUID, viewerID uuid.UUID, limit int, offset int, excludeUserIDs []uuid.UUID)) *MockAnnouncementRepository_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 []uuid.UUID
		if args[5] != nil {
			arg5 = args[5].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_GetComments_Call) Return(announcementCommentRows []AnnouncementCommentRow, n int, err error) *MockAnnouncementRepository_GetComments_Call {
	_c.Call.Return(announcementCommentRows, n, err)
	return _c
}

func (_c *MockAnnouncementRepository_GetComments_Call) RunAndReturn(run func(ctx context.Context, announcementID uuid.UUID, viewerID uuid.UUID, limit int, offset int, excludeUserIDs []uuid.UUID) ([]AnnouncementCommentRow, int, error)) *MockAnnouncementRepository_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatest provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) GetLatest(ctx context.Context) (*AnnouncementRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 *AnnouncementRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*AnnouncementRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *AnnouncementRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AnnouncementRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnnouncementRepository_GetLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatest'
type MockAnnouncementRepository_GetLatest_Call struct {
	*mock.Call
}

// GetLatest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAnnouncementRepository_Expecter) GetLatest(ctx interface{}) *MockAnnouncementRepository_GetLatest_Call {
	return &MockAnnouncementRepository_GetLatest_Call{Call: _e.mock.On("GetLatest", ctx)}
}

func (_c *MockAnnouncementRepository_GetLatest_Call) Run(run func(ctx context.Context)) *MockAnnouncementRepository_GetLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_GetLatest_Call) Return(announcementRow *AnnouncementRow, err error) *MockAnnouncementRepository_GetLatest_Call {
	_c.Call.Return(announcementRow, err)
	return _c
}

func (_c *MockAnnouncementRepository_GetLatest_Call) RunAndReturn(run func(ctx context.Context) (*AnnouncementRow, error)) *MockAnnouncementRepository_GetLatest_Call {
	_c.Call.Return(run)
	return _c
}

// LikeComment provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) LikeComment(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for LikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_LikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeComment'
type MockAnnouncementRepository_LikeComment_Call struct {
	*mock.Call
}

// LikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - commentID uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) LikeComment(ctx interface{}, userID interface{}, commentID interface{}) *MockAnnouncementRepository_LikeComment_Call {
	return &MockAnnouncementRepository_LikeComment_Call{Call: _e.mock.On("LikeComment", ctx, userID, commentID)}
}

func (_c *MockAnnouncementRepository_LikeComment_Call) Run(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID)) *MockAnnouncementRepository_LikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_LikeComment_Call) Return(err error) *MockAnnouncementRepository_LikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_LikeComment_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error) *MockAnnouncementRepository_LikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) List(ctx context.Context, limit int, offset int) ([]AnnouncementRow, int, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []AnnouncementRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]AnnouncementRow, int, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []AnnouncementRow); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AnnouncementRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAnnouncementRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAnnouncementRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockAnnouncementRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockAnnouncementRepository_List_Call {
	return &MockAnnouncementRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockAnnouncementRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockAnnouncementRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_List_Call) Return(announcementRows []AnnouncementRow, n int, err error) *MockAnnouncementRepository_List_Call {
	_c.Call.Return(announcementRows, n, err)
	return _c
}

func (_c *MockAnnouncementRepository_List_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]AnnouncementRow, int, error)) *MockAnnouncementRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetPinned provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) SetPinned(ctx context.Context, id uuid.UUID, pinned bool) error {
	ret := _mock.Called(ctx, id, pinned)

	if len(ret) == 0 {
		panic("no return value specified for SetPinned")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, id, pinned)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_SetPinned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPinned'
type MockAnnouncementRepository_SetPinned_Call struct {
	*mock.Call
}

// SetPinned is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - pinned bool
func (_e *MockAnnouncementRepository_Expecter) SetPinned(ctx interface{}, id interface{}, pinned interface{}) *MockAnnouncementRepository_SetPinned_Call {
	return &MockAnnouncementRepository_SetPinned_Call{Call: _e.mock.On("SetPinned", ctx, id, pinned)}
}

func (_c *MockAnnouncementRepository_SetPinned_Call) Run(run func(ctx context.Context, id uuid.UUID, pinned bool)) *MockAnnouncementRepository_SetPinned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_SetPinned_Call) Return(err error) *MockAnnouncementRepository_SetPinned_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_SetPinned_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, pinned bool) error) *MockAnnouncementRepository_SetPinned_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeComment provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) UnlikeComment(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for UnlikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_UnlikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeComment'
type MockAnnouncementRepository_UnlikeComment_Call struct {
	*mock.Call
}

// UnlikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - commentID uuid.UUID
func (_e *MockAnnouncementRepository_Expecter) UnlikeComment(ctx interface{}, userID interface{}, commentID interface{}) *MockAnnouncementRepository_UnlikeComment_Call {
	return &MockAnnouncementRepository_UnlikeComment_Call{Call: _e.mock.On("UnlikeComment", ctx, userID, commentID)}
}

func (_c *MockAnnouncementRepository_UnlikeComment_Call) Run(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID)) *MockAnnouncementRepository_UnlikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_UnlikeComment_Call) Return(err error) *MockAnnouncementRepository_UnlikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_UnlikeComment_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error) *MockAnnouncementRepository_UnlikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) Update(ctx context.Context, id uuid.UUID, title string, body string) error {
	ret := _mock.Called(ctx, id, title, body)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, title, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAnnouncementRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - title string
//   - body string
func (_e *MockAnnouncementRepository_Expecter) Update(ctx interface{}, id interface{}, title interface{}, body interface{}) *MockAnnouncementRepository_Update_Call {
	return &MockAnnouncementRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, title, body)}
}

func (_c *MockAnnouncementRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, title string, body string)) *MockAnnouncementRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_Update_Call) Return(err error) *MockAnnouncementRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, title string, body string) error) *MockAnnouncementRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) UpdateComment(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, userID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockAnnouncementRepository_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockAnnouncementRepository_Expecter) UpdateComment(ctx interface{}, id interface{}, userID interface{}, body interface{}) *MockAnnouncementRepository_UpdateComment_Call {
	return &MockAnnouncementRepository_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, id, userID, body)}
}

func (_c *MockAnnouncementRepository_UpdateComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string)) *MockAnnouncementRepository_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_UpdateComment_Call) Return(err error) *MockAnnouncementRepository_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error) *MockAnnouncementRepository_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentAsAdmin provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) UpdateCommentAsAdmin(ctx context.Context, id uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentAsAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_UpdateCommentAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentAsAdmin'
type MockAnnouncementRepository_UpdateCommentAsAdmin_Call struct {
	*mock.Call
}

// UpdateCommentAsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - body string
func (_e *MockAnnouncementRepository_Expecter) UpdateCommentAsAdmin(ctx interface{}, id interface{}, body interface{}) *MockAnnouncementRepository_UpdateCommentAsAdmin_Call {
	return &MockAnnouncementRepository_UpdateCommentAsAdmin_Call{Call: _e.mock.On("UpdateCommentAsAdmin", ctx, id, body)}
}

func (_c *MockAnnouncementRepository_UpdateCommentAsAdmin_Call) Run(run func(ctx context.Context, id uuid.UUID, body string)) *MockAnnouncementRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_UpdateCommentAsAdmin_Call) Return(err error) *MockAnnouncementRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_UpdateCommentAsAdmin_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, body string) error) *MockAnnouncementRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaThumbnail provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) UpdateCommentMediaThumbnail(ctx context.Context, id int64, thumbnailURL string) error {
	ret := _mock.Called(ctx, id, thumbnailURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaThumbnail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, thumbnailURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaThumbnail'
type MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call struct {
	*mock.Call
}

// UpdateCommentMediaThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - thumbnailURL string
func (_e *MockAnnouncementRepository_Expecter) UpdateCommentMediaThumbnail(ctx interface{}, id interface{}, thumbnailURL interface{}) *MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call {
	return &MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call{Call: _e.mock.On("UpdateCommentMediaThumbnail", ctx, id, thumbnailURL)}
}

func (_c *MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call) Run(run func(ctx context.Context, id int64, thumbnailURL string)) *MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call) Return(err error) *MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call) RunAndReturn(run func(ctx context.Context, id int64, thumbnailURL string) error) *MockAnnouncementRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaURL provides a mock function for the type MockAnnouncementRepository
func (_mock *MockAnnouncementRepository) UpdateCommentMediaURL(ctx context.Context, id int64, mediaURL string) error {
	ret := _mock.Called(ctx, id, mediaURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, mediaURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnnouncementRepository_UpdateCommentMediaURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaURL'
type MockAnnouncementRepository_UpdateCommentMediaURL_Call struct {
	*mock.Call
}

// UpdateCommentMediaURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - mediaURL string
func (_e *MockAnnouncementRepository_Expecter) UpdateCommentMediaURL(ctx interface{}, id interface{}, mediaURL interface{}) *MockAnnouncementRepository_UpdateCommentMediaURL_Call {
	return &MockAnnouncementRepository_UpdateCommentMediaURL_Call{Call: _e.mock.On("UpdateCommentMediaURL", ctx, id, mediaURL)}
}

func (_c *MockAnnouncementRepository_UpdateCommentMediaURL_Call) Run(run func(ctx context.Context, id int64, mediaURL string)) *MockAnnouncementRepository_UpdateCommentMediaURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnnouncementRepository_UpdateCommentMediaURL_Call) Return(err error) *MockAnnouncementRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnnouncementRepository_UpdateCommentMediaURL_Call) RunAndReturn(run func(ctx context.Context, id int64, mediaURL string) error) *MockAnnouncementRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(run)
	return _c
}
