// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"umineko_city_of_books/internal/repository/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretRepository creates a new instance of MockSecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepository {
	mock := &MockSecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretRepository is an autogenerated mock type for the SecretRepository type
type MockSecretRepository struct {
	mock.Mock
}

type MockSecretRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepository) EXPECT() *MockSecretRepository_Expecter {
	return &MockSecretRepository_Expecter{mock: &_m.Mock}
}

// AddCommentMedia provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) AddCommentMedia(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int) (int64, error) {
	ret := _mock.Called(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for AddCommentMedia")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) (int64, error)); ok {
		return returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) int64); ok {
		r0 = returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r1 = returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_AddCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCommentMedia'
type MockSecretRepository_AddCommentMedia_Call struct {
	*mock.Call
}

// AddCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - mediaURL string
//   - mediaType string
//   - thumbnailURL string
//   - sortOrder int
func (_e *MockSecretRepository_Expecter) AddCommentMedia(ctx interface{}, commentID interface{}, mediaURL interface{}, mediaType interface{}, thumbnailURL interface{}, sortOrder interface{}) *MockSecretRepository_AddCommentMedia_Call {
	return &MockSecretRepository_AddCommentMedia_Call{Call: _e.mock.On("AddCommentMedia", ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)}
}

func (_c *MockSecretRepository_AddCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int)) *MockSecretRepository_AddCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSecretRepository_AddCommentMedia_Call) Return(n int64, err error) *MockSecretRepository_AddCommentMedia_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSecretRepository_AddCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int) (int64, error)) *MockSecretRepository_AddCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// CountCommentsBySecret provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) CountCommentsBySecret(ctx context.Context, secretIDs []string) (map[string]int, error) {
	ret := _mock.Called(ctx, secretIDs)

	if len(ret) == 0 {
		panic("no return value specified for CountCommentsBySecret")
	}

	var r0 map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]int, error)); ok {
		return returnFunc(ctx, secretIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]int); ok {
		r0 = returnFunc(ctx, secretIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, secretIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_CountCommentsBySecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCommentsBySecret'
type MockSecretRepository_CountCommentsBySecret_Call struct {
	*mock.Call
}

// CountCommentsBySecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretIDs []string
func (_e *MockSecretRepository_Expecter) CountCommentsBySecret(ctx interface{}, secretIDs interface{}) *MockSecretRepository_CountCommentsBySecret_Call {
	return &MockSecretRepository_CountCommentsBySecret_Call{Call: _e.mock.On("CountCommentsBySecret", ctx, secretIDs)}
}

func (_c *MockSecretRepository_CountCommentsBySecret_Call) Run(run func(ctx context.Context, secretIDs []string)) *MockSecretRepository_CountCommentsBySecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_CountCommentsBySecret_Call) Return(stringToInt map[string]int, err error) *MockSecretRepository_CountCommentsBySecret_Call {
	_c.Call.Return(stringToInt, err)
	return _c
}

func (_c *MockSecretRepository_CountCommentsBySecret_Call) RunAndReturn(run func(ctx context.Context, secretIDs []string) (map[string]int, error)) *MockSecretRepository_CountCommentsBySecret_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) CreateComment(ctx context.Context, id uuid.UUID, secretID string, parentID *uuid.UUID, userID uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, secretID, parentID, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, secretID, parentID, userID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockSecretRepository_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - secretID string
//   - parentID *uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockSecretRepository_Expecter) CreateComment(ctx interface{}, id interface{}, secretID interface{}, parentID interface{}, userID interface{}, body interface{}) *MockSecretRepository_CreateComment_Call {
	return &MockSecretRepository_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, id, secretID, parentID, userID, body)}
}

func (_c *MockSecretRepository_CreateComment_Call) Run(run func(ctx context.Context, id uuid.UUID, secretID string, parentID *uuid.UUID, userID uuid.UUID, body string)) *MockSecretRepository_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSecretRepository_CreateComment_Call) Return(err error) *MockSecretRepository_CreateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_CreateComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, secretID string, parentID *uuid.UUID, userID uuid.UUID, body string) error) *MockSecretRepository_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) DeleteComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockSecretRepository_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockSecretRepository_Expecter) DeleteComment(ctx interface{}, id interface{}, userID interface{}) *MockSecretRepository_DeleteComment_Call {
	return &MockSecretRepository_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, id, userID)}
}

func (_c *MockSecretRepository_DeleteComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockSecretRepository_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_DeleteComment_Call) Return(err error) *MockSecretRepository_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockSecretRepository_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCommentAsAdmin provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) DeleteCommentAsAdmin(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCommentAsAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_DeleteCommentAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCommentAsAdmin'
type MockSecretRepository_DeleteCommentAsAdmin_Call struct {
	*mock.Call
}

// DeleteCommentAsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSecretRepository_Expecter) DeleteCommentAsAdmin(ctx interface{}, id interface{}) *MockSecretRepository_DeleteCommentAsAdmin_Call {
	return &MockSecretRepository_DeleteCommentAsAdmin_Call{Call: _e.mock.On("DeleteCommentAsAdmin", ctx, id)}
}

func (_c *MockSecretRepository_DeleteCommentAsAdmin_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSecretRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_DeleteCommentAsAdmin_Call) Return(err error) *MockSecretRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_DeleteCommentAsAdmin_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSecretRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentAuthorID provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentAuthorID(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentAuthorID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentAuthorID'
type MockSecretRepository_GetCommentAuthorID_Call struct {
	*mock.Call
}

// GetCommentAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockSecretRepository_Expecter) GetCommentAuthorID(ctx interface{}, commentID interface{}) *MockSecretRepository_GetCommentAuthorID_Call {
	return &MockSecretRepository_GetCommentAuthorID_Call{Call: _e.mock.On("GetCommentAuthorID", ctx, commentID)}
}

func (_c *MockSecretRepository_GetCommentAuthorID_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockSecretRepository_GetCommentAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentAuthorID_Call) Return(uUID uuid.UUID, err error) *MockSecretRepository_GetCommentAuthorID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentAuthorID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error)) *MockSecretRepository_GetCommentAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentByID provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentByID(ctx context.Context, id uuid.UUID) (*SecretCommentRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentByID")
	}

	var r0 *SecretCommentRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*SecretCommentRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *SecretCommentRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SecretCommentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentByID'
type MockSecretRepository_GetCommentByID_Call struct {
	*mock.Call
}

// GetCommentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSecretRepository_Expecter) GetCommentByID(ctx interface{}, id interface{}) *MockSecretRepository_GetCommentByID_Call {
	return &MockSecretRepository_GetCommentByID_Call{Call: _e.mock.On("GetCommentByID", ctx, id)}
}

func (_c *MockSecretRepository_GetCommentByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSecretRepository_GetCommentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentByID_Call) Return(secretCommentRow *SecretCommentRow, err error) *MockSecretRepository_GetCommentByID_Call {
	_c.Call.Return(secretCommentRow, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*SecretCommentRow, error)) *MockSecretRepository_GetCommentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMedia provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentMedia(ctx context.Context, commentID uuid.UUID) ([]model.CommentMediaRow, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMedia")
	}

	var r0 []model.CommentMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.CommentMediaRow, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.CommentMediaRow); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMedia'
type MockSecretRepository_GetCommentMedia_Call struct {
	*mock.Call
}

// GetCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockSecretRepository_Expecter) GetCommentMedia(ctx interface{}, commentID interface{}) *MockSecretRepository_GetCommentMedia_Call {
	return &MockSecretRepository_GetCommentMedia_Call{Call: _e.mock.On("GetCommentMedia", ctx, commentID)}
}

func (_c *MockSecretRepository_GetCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockSecretRepository_GetCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentMedia_Call) Return(commentMediaRows []model.CommentMediaRow, err error) *MockSecretRepository_GetCommentMedia_Call {
	_c.Call.Return(commentMediaRows, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) ([]model.CommentMediaRow, error)) *MockSecretRepository_GetCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMediaBatch provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentMediaBatch(ctx context.Context, commentIDs []uuid.UUID) (map[uuid.UUID][]model.CommentMediaRow, error) {
	ret := _mock.Called(ctx, commentIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMediaBatch")
	}

	var r0 map[uuid.UUID][]model.CommentMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID][]model.CommentMediaRow, error)); ok {
		return returnFunc(ctx, commentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID][]model.CommentMediaRow); ok {
		r0 = returnFunc(ctx, commentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]model.CommentMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentMediaBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMediaBatch'
type MockSecretRepository_GetCommentMediaBatch_Call struct {
	*mock.Call
}

// GetCommentMediaBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - commentIDs []uuid.UUID
func (_e *MockSecretRepository_Expecter) GetCommentMediaBatch(ctx interface{}, commentIDs interface{}) *MockSecretRepository_GetCommentMediaBatch_Call {
	return &MockSecretRepository_GetCommentMediaBatch_Call{Call: _e.mock.On("GetCommentMediaBatch", ctx, commentIDs)}
}

func (_c *MockSecretRepository_GetCommentMediaBatch_Call) Run(run func(ctx context.Context, commentIDs []uuid.UUID)) *MockSecretRepository_GetCommentMediaBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentMediaBatch_Call) Return(uUIDToCommentMediaRows map[uuid.UUID][]model.CommentMediaRow, err error) *MockSecretRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(uUIDToCommentMediaRows, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentMediaBatch_Call) RunAndReturn(run func(ctx context.Context, commentIDs []uuid.UUID) (map[uuid.UUID][]model.CommentMediaRow, error)) *MockSecretRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentSecretID provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentSecretID(ctx context.Context, commentID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentSecretID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentSecretID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentSecretID'
type MockSecretRepository_GetCommentSecretID_Call struct {
	*mock.Call
}

// GetCommentSecretID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockSecretRepository_Expecter) GetCommentSecretID(ctx interface{}, commentID interface{}) *MockSecretRepository_GetCommentSecretID_Call {
	return &MockSecretRepository_GetCommentSecretID_Call{Call: _e.mock.On("GetCommentSecretID", ctx, commentID)}
}

func (_c *MockSecretRepository_GetCommentSecretID_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockSecretRepository_GetCommentSecretID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentSecretID_Call) Return(s string, err error) *MockSecretRepository_GetCommentSecretID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentSecretID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) (string, error)) *MockSecretRepository_GetCommentSecretID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommenterIDs provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommenterIDs(ctx context.Context, secretID string) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommenterIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, secretID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []uuid.UUID); ok {
		r0 = returnFunc(ctx, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommenterIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommenterIDs'
type MockSecretRepository_GetCommenterIDs_Call struct {
	*mock.Call
}

// GetCommenterIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
func (_e *MockSecretRepository_Expecter) GetCommenterIDs(ctx interface{}, secretID interface{}) *MockSecretRepository_GetCommenterIDs_Call {
	return &MockSecretRepository_GetCommenterIDs_Call{Call: _e.mock.On("GetCommenterIDs", ctx, secretID)}
}

func (_c *MockSecretRepository_GetCommenterIDs_Call) Run(run func(ctx context.Context, secretID string)) *MockSecretRepository_GetCommenterIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommenterIDs_Call) Return(uUIDs []uuid.UUID, err error) *MockSecretRepository_GetCommenterIDs_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockSecretRepository_GetCommenterIDs_Call) RunAndReturn(run func(ctx context.Context, secretID string) ([]uuid.UUID, error)) *MockSecretRepository_GetCommenterIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetComments(ctx context.Context, secretID string, viewerID uuid.UUID, excludeUserIDs []uuid.UUID) ([]SecretCommentRow, error) {
	ret := _mock.Called(ctx, secretID, viewerID, excludeUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []SecretCommentRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, []uuid.UUID) ([]SecretCommentRow, error)); ok {
		return returnFunc(ctx, secretID, viewerID, excludeUserIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, []uuid.UUID) []SecretCommentRow); ok {
		r0 = returnFunc(ctx, secretID, viewerID, excludeUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SecretCommentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, secretID, viewerID, excludeUserIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockSecretRepository_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
//   - viewerID uuid.UUID
//   - excludeUserIDs []uuid.UUID
func (_e *MockSecretRepository_Expecter) GetComments(ctx interface{}, secretID interface{}, viewerID interface{}, excludeUserIDs interface{}) *MockSecretRepository_GetComments_Call {
	return &MockSecretRepository_GetComments_Call{Call: _e.mock.On("GetComments", ctx, secretID, viewerID, excludeUserIDs)}
}

func (_c *MockSecretRepository_GetComments_Call) Run(run func(ctx context.Context, secretID string, viewerID uuid.UUID, excludeUserIDs []uuid.UUID)) *MockSecretRepository_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []uuid.UUID
		if args[3] != nil {
			arg3 = args[3].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetComments_Call) Return(secretCommentRows []SecretCommentRow, err error) *MockSecretRepository_GetComments_Call {
	_c.Call.Return(secretCommentRows, err)
	return _c
}

func (_c *MockSecretRepository_GetComments_Call) RunAndReturn(run func(ctx context.Context, secretID string, viewerID uuid.UUID, excludeUserIDs []uuid.UUID) ([]SecretCommentRow, error)) *MockSecretRepository_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirstSolver provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetFirstSolver(ctx context.Context, secretID string) (*SecretSolver, error) {
	ret := _mock.Called(ctx, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstSolver")
	}

	var r0 *SecretSolver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*SecretSolver, error)); ok {
		return returnFunc(ctx, secretID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *SecretSolver); ok {
		r0 = returnFunc(ctx, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SecretSolver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetFirstSolver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstSolver'
type MockSecretRepository_GetFirstSolver_Call struct {
	*mock.Call
}

// GetFirstSolver is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
func (_e *MockSecretRepository_Expecter) GetFirstSolver(ctx interface{}, secretID interface{}) *MockSecretRepository_GetFirstSolver_Call {
	return &MockSecretRepository_GetFirstSolver_Call{Call: _e.mock.On("GetFirstSolver", ctx, secretID)}
}

func (_c *MockSecretRepository_GetFirstSolver_Call) Run(run func(ctx context.Context, secretID string)) *MockSecretRepository_GetFirstSolver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetFirstSolver_Call) Return(secretSolver *SecretSolver, err error) *MockSecretRepository_GetFirstSolver_Call {
	_c.Call.Return(secretSolver, err)
	return _c
}

func (_c *MockSecretRepository_GetFirstSolver_Call) RunAndReturn(run func(ctx context.Context, secretID string) (*SecretSolver, error)) *MockSecretRepository_GetFirstSolver_Call {
	_c.Call.Return(run)
	return _c
}

// GetPieceCountForUser provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetPieceCountForUser(ctx context.Context, userID uuid.UUID, pieceIDs []string) (int, error) {
	ret := _mock.Called(ctx, userID, pieceIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetPieceCountForUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) (int, error)); ok {
		return returnFunc(ctx, userID, pieceIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) int); ok {
		r0 = returnFunc(ctx, userID, pieceIDs)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = returnFunc(ctx, userID, pieceIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetPieceCountForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPieceCountForUser'
type MockSecretRepository_GetPieceCountForUser_Call struct {
	*mock.Call
}

// GetPieceCountForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - pieceIDs []string
func (_e *MockSecretRepository_Expecter) GetPieceCountForUser(ctx interface{}, userID interface{}, pieceIDs interface{}) *MockSecretRepository_GetPieceCountForUser_Call {
	return &MockSecretRepository_GetPieceCountForUser_Call{Call: _e.mock.On("GetPieceCountForUser", ctx, userID, pieceIDs)}
}

func (_c *MockSecretRepository_GetPieceCountForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, pieceIDs []string)) *MockSecretRepository_GetPieceCountForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetPieceCountForUser_Call) Return(n int, err error) *MockSecretRepository_GetPieceCountForUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSecretRepository_GetPieceCountForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, pieceIDs []string) (int, error)) *MockSecretRepository_GetPieceCountForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetProgressLeaderboard provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetProgressLeaderboard(ctx context.Context, pieceIDs []string) ([]SecretLeaderboardRow, error) {
	ret := _mock.Called(ctx, pieceIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetProgressLeaderboard")
	}

	var r0 []SecretLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]SecretLeaderboardRow, error)); ok {
		return returnFunc(ctx, pieceIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []SecretLeaderboardRow); ok {
		r0 = returnFunc(ctx, pieceIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SecretLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, pieceIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetProgressLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProgressLeaderboard'
type MockSecretRepository_GetProgressLeaderboard_Call struct {
	*mock.Call
}

// GetProgressLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - pieceIDs []string
func (_e *MockSecretRepository_Expecter) GetProgressLeaderboard(ctx interface{}, pieceIDs interface{}) *MockSecretRepository_GetProgressLeaderboard_Call {
	return &MockSecretRepository_GetProgressLeaderboard_Call{Call: _e.mock.On("GetProgressLeaderboard", ctx, pieceIDs)}
}

func (_c *MockSecretRepository_GetProgressLeaderboard_Call) Run(run func(ctx context.Context, pieceIDs []string)) *MockSecretRepository_GetProgressLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetProgressLeaderboard_Call) Return(secretLeaderboardRows []SecretLeaderboardRow, err error) *MockSecretRepository_GetProgressLeaderboard_Call {
	_c.Call.Return(secretLeaderboardRows, err)
	return _c
}

func (_c *MockSecretRepository_GetProgressLeaderboard_Call) RunAndReturn(run func(ctx context.Context, pieceIDs []string) ([]SecretLeaderboardRow, error)) *MockSecretRepository_GetProgressLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetSolversLeaderboard provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetSolversLeaderboard(ctx context.Context, parentSecretIDs []string) ([]SecretSolverRow, error) {
	ret := _mock.Called(ctx, parentSecretIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetSolversLeaderboard")
	}

	var r0 []SecretSolverRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]SecretSolverRow, error)); ok {
		return returnFunc(ctx, parentSecretIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []SecretSolverRow); ok {
		r0 = returnFunc(ctx, parentSecretIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SecretSolverRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, parentSecretIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetSolversLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSolversLeaderboard'
type MockSecretRepository_GetSolversLeaderboard_Call struct {
	*mock.Call
}

// GetSolversLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - parentSecretIDs []string
func (_e *MockSecretRepository_Expecter) GetSolversLeaderboard(ctx interface{}, parentSecretIDs interface{}) *MockSecretRepository_GetSolversLeaderboard_Call {
	return &MockSecretRepository_GetSolversLeaderboard_Call{Call: _e.mock.On("GetSolversLeaderboard", ctx, parentSecretIDs)}
}

func (_c *MockSecretRepository_GetSolversLeaderboard_Call) Run(run func(ctx context.Context, parentSecretIDs []string)) *MockSecretRepository_GetSolversLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetSolversLeaderboard_Call) Return(secretSolverRows []SecretSolverRow, err error) *MockSecretRepository_GetSolversLeaderboard_Call {
	_c.Call.Return(secretSolverRows, err)
	return _c
}

func (_c *MockSecretRepository_GetSolversLeaderboard_Call) RunAndReturn(run func(ctx context.Context, parentSecretIDs []string) ([]SecretSolverRow, error)) *MockSecretRepository_GetSolversLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserProgressSummary provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetUserProgressSummary(ctx context.Context, userID uuid.UUID, pieceIDs []string) (*SecretLeaderboardRow, error) {
	ret := _mock.Called(ctx, userID, pieceIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProgressSummary")
	}

	var r0 *SecretLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) (*SecretLeaderboardRow, error)); ok {
		return returnFunc(ctx, userID, pieceIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) *SecretLeaderboardRow); ok {
		r0 = returnFunc(ctx, userID, pieceIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SecretLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = returnFunc(ctx, userID, pieceIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetUserProgressSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProgressSummary'
type MockSecretRepository_GetUserProgressSummary_Call struct {
	*mock.Call
}

// GetUserProgressSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - pieceIDs []string
func (_e *MockSecretRepository_Expecter) GetUserProgressSummary(ctx interface{}, userID interface{}, pieceIDs interface{}) *MockSecretRepository_GetUserProgressSummary_Call {
	return &MockSecretRepository_GetUserProgressSummary_Call{Call: _e.mock.On("GetUserProgressSummary", ctx, userID, pieceIDs)}
}

func (_c *MockSecretRepository_GetUserProgressSummary_Call) Run(run func(ctx context.Context, userID uuid.UUID, pieceIDs []string)) *MockSecretRepository_GetUserProgressSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetUserProgressSummary_Call) Return(secretLeaderboardRow *SecretLeaderboardRow, err error) *MockSecretRepository_GetUserProgressSummary_Call {
	_c.Call.Return(secretLeaderboardRow, err)
	return _c
}

func (_c *MockSecretRepository_GetUserProgressSummary_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, pieceIDs []string) (*SecretLeaderboardRow, error)) *MockSecretRepository_GetUserProgressSummary_Call {
	_c.Call.Return(run)
	return _c
}

// LikeComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) LikeComment(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for LikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_LikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeComment'
type MockSecretRepository_LikeComment_Call struct {
	*mock.Call
}

// LikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - commentID uuid.UUID
func (_e *MockSecretRepository_Expecter) LikeComment(ctx interface{}, userID interface{}, commentID interface{}) *MockSecretRepository_LikeComment_Call {
	return &MockSecretRepository_LikeComment_Call{Call: _e.mock.On("LikeComment", ctx, userID, commentID)}
}

func (_c *MockSecretRepository_LikeComment_Call) Run(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID)) *MockSecretRepository_LikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_LikeComment_Call) Return(err error) *MockSecretRepository_LikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_LikeComment_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error) *MockSecretRepository_LikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UnlikeComment(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for UnlikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UnlikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeComment'
type MockSecretRepository_UnlikeComment_Call struct {
	*mock.Call
}

// UnlikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - commentID uuid.UUID
func (_e *MockSecretRepository_Expecter) UnlikeComment(ctx interface{}, userID interface{}, commentID interface{}) *MockSecretRepository_UnlikeComment_Call {
	return &MockSecretRepository_UnlikeComment_Call{Call: _e.mock.On("UnlikeComment", ctx, userID, commentID)}
}

func (_c *MockSecretRepository_UnlikeComment_Call) Run(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID)) *MockSecretRepository_UnlikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UnlikeComment_Call) Return(err error) *MockSecretRepository_UnlikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UnlikeComment_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error) *MockSecretRepository_UnlikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UpdateComment(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, userID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockSecretRepository_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockSecretRepository_Expecter) UpdateComment(ctx interface{}, id interface{}, userID interface{}, body interface{}) *MockSecretRepository_UpdateComment_Call {
	return &MockSecretRepository_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, id, userID, body)}
}

func (_c *MockSecretRepository_UpdateComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string)) *MockSecretRepository_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UpdateComment_Call) Return(err error) *MockSecretRepository_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error) *MockSecretRepository_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentAsAdmin provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UpdateCommentAsAdmin(ctx context.Context, id uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentAsAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UpdateCommentAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentAsAdmin'
type MockSecretRepository_UpdateCommentAsAdmin_Call struct {
	*mock.Call
}

// UpdateCommentAsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - body string
func (_e *MockSecretRepository_Expecter) UpdateCommentAsAdmin(ctx interface{}, id interface{}, body interface{}) *MockSecretRepository_UpdateCommentAsAdmin_Call {
	return &MockSecretRepository_UpdateCommentAsAdmin_Call{Call: _e.mock.On("UpdateCommentAsAdmin", ctx, id, body)}
}

func (_c *MockSecretRepository_UpdateCommentAsAdmin_Call) Run(run func(ctx context.Context, id uuid.UUID, body string)) *MockSecretRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UpdateCommentAsAdmin_Call) Return(err error) *MockSecretRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UpdateCommentAsAdmin_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, body string) error) *MockSecretRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaThumbnail provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UpdateCommentMediaThumbnail(ctx context.Context, id int64, thumbnailURL string) error {
	ret := _mock.Called(ctx, id, thumbnailURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaThumbnail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, thumbnailURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UpdateCommentMediaThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaThumbnail'
type MockSecretRepository_UpdateCommentMediaThumbnail_Call struct {
	*mock.Call
}

// UpdateCommentMediaThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - thumbnailURL string
func (_e *MockSecretRepository_Expecter) UpdateCommentMediaThumbnail(ctx interface{}, id interface{}, thumbnailURL interface{}) *MockSecretRepository_UpdateCommentMediaThumbnail_Call {
	return &MockSecretRepository_UpdateCommentMediaThumbnail_Call{Call: _e.mock.On("UpdateCommentMediaThumbnail", ctx, id, thumbnailURL)}
}

func (_c *MockSecretRepository_UpdateCommentMediaThumbnail_Call) Run(run func(ctx context.Context, id int64, thumbnailURL string)) *MockSecretRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UpdateCommentMediaThumbnail_Call) Return(err error) *MockSecretRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UpdateCommentMediaThumbnail_Call) RunAndReturn(run func(ctx context.Context, id int64, thumbnailURL string) error) *MockSecretRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaURL provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UpdateCommentMediaURL(ctx context.Context, id int64, mediaURL string) error {
	ret := _mock.Called(ctx, id, mediaURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, mediaURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UpdateCommentMediaURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaURL'
type MockSecretRepository_UpdateCommentMediaURL_Call struct {
	*mock.Call
}

// UpdateCommentMediaURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - mediaURL string
func (_e *MockSecretRepository_Expecter) UpdateCommentMediaURL(ctx interface{}, id interface{}, mediaURL interface{}) *MockSecretRepository_UpdateCommentMediaURL_Call {
	return &MockSecretRepository_UpdateCommentMediaURL_Call{Call: _e.mock.On("UpdateCommentMediaURL", ctx, id, mediaURL)}
}

func (_c *MockSecretRepository_UpdateCommentMediaURL_Call) Run(run func(ctx context.Context, id int64, mediaURL string)) *MockSecretRepository_UpdateCommentMediaURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UpdateCommentMediaURL_Call) Return(err error) *MockSecretRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UpdateCommentMediaURL_Call) RunAndReturn(run func(ctx context.Context, id int64, mediaURL string) error) *MockSecretRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(run)
	return _c
}
