// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// CleanExpired provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) CleanExpired(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_CleanExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanExpired'
type MockSessionRepository_CleanExpired_Call struct {
	*mock.Call
}

// CleanExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionRepository_Expecter) CleanExpired(ctx interface{}) *MockSessionRepository_CleanExpired_Call {
	return &MockSessionRepository_CleanExpired_Call{Call: _e.mock.On("CleanExpired", ctx)}
}

func (_c *MockSessionRepository_CleanExpired_Call) Run(run func(ctx context.Context)) *MockSessionRepository_CleanExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionRepository_CleanExpired_Call) Return(err error) *MockSessionRepository_CleanExpired_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_CleanExpired_Call) RunAndReturn(run func(ctx context.Context) error) *MockSessionRepository_CleanExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Create(ctx context.Context, token string, userID uuid.UUID, expiresAt time.Time) error {
	ret := _mock.Called(ctx, token, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, token, userID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID uuid.UUID
//   - expiresAt time.Time
func (_e *MockSessionRepository_Expecter) Create(ctx interface{}, token interface{}, userID interface{}, expiresAt interface{}) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, token, userID, expiresAt)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, token string, userID uuid.UUID, expiresAt time.Time)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(err error) *MockSessionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token string, userID uuid.UUID, expiresAt time.Time) error) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Delete(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionRepository_Expecter) Delete(ctx interface{}, token interface{}) *MockSessionRepository_Delete_Call {
	return &MockSessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *MockSessionRepository_Delete_Call) Run(run func(ctx context.Context, token string)) *MockSessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Delete_Call) Return(err error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllForUser provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteAllForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_DeleteAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllForUser'
type MockSessionRepository_DeleteAllForUser_Call struct {
	*mock.Call
}

// DeleteAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionRepository_Expecter) DeleteAllForUser(ctx interface{}, userID interface{}) *MockSessionRepository_DeleteAllForUser_Call {
	return &MockSessionRepository_DeleteAllForUser_Call{Call: _e.mock.On("DeleteAllForUser", ctx, userID)}
}

func (_c *MockSessionRepository_DeleteAllForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionRepository_DeleteAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteAllForUser_Call) Return(err error) *MockSessionRepository_DeleteAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_DeleteAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockSessionRepository_DeleteAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) GetUserID(ctx context.Context, token string) (uuid.UUID, time.Time, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 uuid.UUID
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, time.Time, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) time.Time); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionRepository_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockSessionRepository_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionRepository_Expecter) GetUserID(ctx interface{}, token interface{}) *MockSessionRepository_GetUserID_Call {
	return &MockSessionRepository_GetUserID_Call{Call: _e.mock.On("GetUserID", ctx, token)}
}

func (_c *MockSessionRepository_GetUserID_Call) Run(run func(ctx context.Context, token string)) *MockSessionRepository_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_GetUserID_Call) Return(uUID uuid.UUID, time1 time.Time, err error) *MockSessionRepository_GetUserID_Call {
	_c.Call.Return(uUID, time1, err)
	return _c
}

func (_c *MockSessionRepository_GetUserID_Call) RunAndReturn(run func(ctx context.Context, token string) (uuid.UUID, time.Time, error)) *MockSessionRepository_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}
