// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"umineko_city_of_books/internal/dto"
	"umineko_city_of_books/internal/repository/model"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShipRepository creates a new instance of MockShipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShipRepository {
	mock := &MockShipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShipRepository is an autogenerated mock type for the ShipRepository type
type MockShipRepository struct {
	mock.Mock
}

type MockShipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShipRepository) EXPECT() *MockShipRepository_Expecter {
	return &MockShipRepository_Expecter{mock: &_m.Mock}
}

// AddCommentMedia provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) AddCommentMedia(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int) (int64, error) {
	ret := _mock.Called(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for AddCommentMedia")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) (int64, error)); ok {
		return returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, int) int64); ok {
		r0 = returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string, int) error); ok {
		r1 = returnFunc(ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_AddCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCommentMedia'
type MockShipRepository_AddCommentMedia_Call struct {
	*mock.Call
}

// AddCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - mediaURL string
//   - mediaType string
//   - thumbnailURL string
//   - sortOrder int
func (_e *MockShipRepository_Expecter) AddCommentMedia(ctx interface{}, commentID interface{}, mediaURL interface{}, mediaType interface{}, thumbnailURL interface{}, sortOrder interface{}) *MockShipRepository_AddCommentMedia_Call {
	return &MockShipRepository_AddCommentMedia_Call{Call: _e.mock.On("AddCommentMedia", ctx, commentID, mediaURL, mediaType, thumbnailURL, sortOrder)}
}

func (_c *MockShipRepository_AddCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int)) *MockShipRepository_AddCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockShipRepository_AddCommentMedia_Call) Return(n int64, err error) *MockShipRepository_AddCommentMedia_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockShipRepository_AddCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, mediaURL string, mediaType string, thumbnailURL string, sortOrder int) (int64, error)) *MockShipRepository_AddCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) CreateComment(ctx context.Context, id uuid.UUID, shipID uuid.UUID, parentID *uuid.UUID, userID uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, shipID, parentID, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, shipID, parentID, userID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockShipRepository_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - shipID uuid.UUID
//   - parentID *uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockShipRepository_Expecter) CreateComment(ctx interface{}, id interface{}, shipID interface{}, parentID interface{}, userID interface{}, body interface{}) *MockShipRepository_CreateComment_Call {
	return &MockShipRepository_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, id, shipID, parentID, userID, body)}
}

func (_c *MockShipRepository_CreateComment_Call) Run(run func(ctx context.Context, id uuid.UUID, shipID uuid.UUID, parentID *uuid.UUID, userID uuid.UUID, body string)) *MockShipRepository_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockShipRepository_CreateComment_Call) Return(err error) *MockShipRepository_CreateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_CreateComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, shipID uuid.UUID, parentID *uuid.UUID, userID uuid.UUID, body string) error) *MockShipRepository_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithCharacters provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) CreateWithCharacters(ctx context.Context, id uuid.UUID, userID uuid.UUID, title string, description string, characters []dto.ShipCharacter) error {
	ret := _mock.Called(ctx, id, userID, title, description, characters)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithCharacters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, []dto.ShipCharacter) error); ok {
		r0 = returnFunc(ctx, id, userID, title, description, characters)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_CreateWithCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithCharacters'
type MockShipRepository_CreateWithCharacters_Call struct {
	*mock.Call
}

// CreateWithCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - title string
//   - description string
//   - characters []dto.ShipCharacter
func (_e *MockShipRepository_Expecter) CreateWithCharacters(ctx interface{}, id interface{}, userID interface{}, title interface{}, description interface{}, characters interface{}) *MockShipRepository_CreateWithCharacters_Call {
	return &MockShipRepository_CreateWithCharacters_Call{Call: _e.mock.On("CreateWithCharacters", ctx, id, userID, title, description, characters)}
}

func (_c *MockShipRepository_CreateWithCharacters_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, title string, description string, characters []dto.ShipCharacter)) *MockShipRepository_CreateWithCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []dto.ShipCharacter
		if args[5] != nil {
			arg5 = args[5].([]dto.ShipCharacter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockShipRepository_CreateWithCharacters_Call) Return(err error) *MockShipRepository_CreateWithCharacters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_CreateWithCharacters_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, title string, description string, characters []dto.ShipCharacter) error) *MockShipRepository_CreateWithCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) Delete(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockShipRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockShipRepository_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}) *MockShipRepository_Delete_Call {
	return &MockShipRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID)}
}

func (_c *MockShipRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockShipRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipRepository_Delete_Call) Return(err error) *MockShipRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockShipRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAsAdmin provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) DeleteAsAdmin(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAsAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_DeleteAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAsAdmin'
type MockShipRepository_DeleteAsAdmin_Call struct {
	*mock.Call
}

// DeleteAsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockShipRepository_Expecter) DeleteAsAdmin(ctx interface{}, id interface{}) *MockShipRepository_DeleteAsAdmin_Call {
	return &MockShipRepository_DeleteAsAdmin_Call{Call: _e.mock.On("DeleteAsAdmin", ctx, id)}
}

func (_c *MockShipRepository_DeleteAsAdmin_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockShipRepository_DeleteAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_DeleteAsAdmin_Call) Return(err error) *MockShipRepository_DeleteAsAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_DeleteAsAdmin_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockShipRepository_DeleteAsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) DeleteComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockShipRepository_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockShipRepository_Expecter) DeleteComment(ctx interface{}, id interface{}, userID interface{}) *MockShipRepository_DeleteComment_Call {
	return &MockShipRepository_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, id, userID)}
}

func (_c *MockShipRepository_DeleteComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockShipRepository_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipRepository_DeleteComment_Call) Return(err error) *MockShipRepository_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockShipRepository_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCommentAsAdmin provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) DeleteCommentAsAdmin(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCommentAsAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_DeleteCommentAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCommentAsAdmin'
type MockShipRepository_DeleteCommentAsAdmin_Call struct {
	*mock.Call
}

// DeleteCommentAsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockShipRepository_Expecter) DeleteCommentAsAdmin(ctx interface{}, id interface{}) *MockShipRepository_DeleteCommentAsAdmin_Call {
	return &MockShipRepository_DeleteCommentAsAdmin_Call{Call: _e.mock.On("DeleteCommentAsAdmin", ctx, id)}
}

func (_c *MockShipRepository_DeleteCommentAsAdmin_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockShipRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_DeleteCommentAsAdmin_Call) Return(err error) *MockShipRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_DeleteCommentAsAdmin_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockShipRepository_DeleteCommentAsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorID provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetAuthorID(ctx context.Context, shipID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, shipID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, shipID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, shipID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, shipID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorID'
type MockShipRepository_GetAuthorID_Call struct {
	*mock.Call
}

// GetAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - shipID uuid.UUID
func (_e *MockShipRepository_Expecter) GetAuthorID(ctx interface{}, shipID interface{}) *MockShipRepository_GetAuthorID_Call {
	return &MockShipRepository_GetAuthorID_Call{Call: _e.mock.On("GetAuthorID", ctx, shipID)}
}

func (_c *MockShipRepository_GetAuthorID_Call) Run(run func(ctx context.Context, shipID uuid.UUID)) *MockShipRepository_GetAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetAuthorID_Call) Return(uUID uuid.UUID, err error) *MockShipRepository_GetAuthorID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockShipRepository_GetAuthorID_Call) RunAndReturn(run func(ctx context.Context, shipID uuid.UUID) (uuid.UUID, error)) *MockShipRepository_GetAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetByID(ctx context.Context, id uuid.UUID, viewerID uuid.UUID) (*model.ShipRow, error) {
	ret := _mock.Called(ctx, id, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.ShipRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.ShipRow, error)); ok {
		return returnFunc(ctx, id, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.ShipRow); ok {
		r0 = returnFunc(ctx, id, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShipRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockShipRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - viewerID uuid.UUID
func (_e *MockShipRepository_Expecter) GetByID(ctx interface{}, id interface{}, viewerID interface{}) *MockShipRepository_GetByID_Call {
	return &MockShipRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, viewerID)}
}

func (_c *MockShipRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, viewerID uuid.UUID)) *MockShipRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetByID_Call) Return(shipRow *model.ShipRow, err error) *MockShipRepository_GetByID_Call {
	_c.Call.Return(shipRow, err)
	return _c
}

func (_c *MockShipRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, viewerID uuid.UUID) (*model.ShipRow, error)) *MockShipRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCharacters provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCharacters(ctx context.Context, shipID uuid.UUID) ([]model.ShipCharacterRow, error) {
	ret := _mock.Called(ctx, shipID)

	if len(ret) == 0 {
		panic("no return value specified for GetCharacters")
	}

	var r0 []model.ShipCharacterRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ShipCharacterRow, error)); ok {
		return returnFunc(ctx, shipID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ShipCharacterRow); ok {
		r0 = returnFunc(ctx, shipID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShipCharacterRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, shipID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCharacters'
type MockShipRepository_GetCharacters_Call struct {
	*mock.Call
}

// GetCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - shipID uuid.UUID
func (_e *MockShipRepository_Expecter) GetCharacters(ctx interface{}, shipID interface{}) *MockShipRepository_GetCharacters_Call {
	return &MockShipRepository_GetCharacters_Call{Call: _e.mock.On("GetCharacters", ctx, shipID)}
}

func (_c *MockShipRepository_GetCharacters_Call) Run(run func(ctx context.Context, shipID uuid.UUID)) *MockShipRepository_GetCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCharacters_Call) Return(shipCharacterRows []model.ShipCharacterRow, err error) *MockShipRepository_GetCharacters_Call {
	_c.Call.Return(shipCharacterRows, err)
	return _c
}

func (_c *MockShipRepository_GetCharacters_Call) RunAndReturn(run func(ctx context.Context, shipID uuid.UUID) ([]model.ShipCharacterRow, error)) *MockShipRepository_GetCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// GetCharactersBatch provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCharactersBatch(ctx context.Context, shipIDs []uuid.UUID) (map[uuid.UUID][]model.ShipCharacterRow, error) {
	ret := _mock.Called(ctx, shipIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetCharactersBatch")
	}

	var r0 map[uuid.UUID][]model.ShipCharacterRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID][]model.ShipCharacterRow, error)); ok {
		return returnFunc(ctx, shipIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID][]model.ShipCharacterRow); ok {
		r0 = returnFunc(ctx, shipIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]model.ShipCharacterRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, shipIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCharactersBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCharactersBatch'
type MockShipRepository_GetCharactersBatch_Call struct {
	*mock.Call
}

// GetCharactersBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - shipIDs []uuid.UUID
func (_e *MockShipRepository_Expecter) GetCharactersBatch(ctx interface{}, shipIDs interface{}) *MockShipRepository_GetCharactersBatch_Call {
	return &MockShipRepository_GetCharactersBatch_Call{Call: _e.mock.On("GetCharactersBatch", ctx, shipIDs)}
}

func (_c *MockShipRepository_GetCharactersBatch_Call) Run(run func(ctx context.Context, shipIDs []uuid.UUID)) *MockShipRepository_GetCharactersBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCharactersBatch_Call) Return(uUIDToShipCharacterRows map[uuid.UUID][]model.ShipCharacterRow, err error) *MockShipRepository_GetCharactersBatch_Call {
	_c.Call.Return(uUIDToShipCharacterRows, err)
	return _c
}

func (_c *MockShipRepository_GetCharactersBatch_Call) RunAndReturn(run func(ctx context.Context, shipIDs []uuid.UUID) (map[uuid.UUID][]model.ShipCharacterRow, error)) *MockShipRepository_GetCharactersBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentAuthorID provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCommentAuthorID(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentAuthorID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCommentAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentAuthorID'
type MockShipRepository_GetCommentAuthorID_Call struct {
	*mock.Call
}

// GetCommentAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockShipRepository_Expecter) GetCommentAuthorID(ctx interface{}, commentID interface{}) *MockShipRepository_GetCommentAuthorID_Call {
	return &MockShipRepository_GetCommentAuthorID_Call{Call: _e.mock.On("GetCommentAuthorID", ctx, commentID)}
}

func (_c *MockShipRepository_GetCommentAuthorID_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockShipRepository_GetCommentAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCommentAuthorID_Call) Return(uUID uuid.UUID, err error) *MockShipRepository_GetCommentAuthorID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockShipRepository_GetCommentAuthorID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error)) *MockShipRepository_GetCommentAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMedia provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCommentMedia(ctx context.Context, commentID uuid.UUID) ([]model.ShipCommentMediaRow, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMedia")
	}

	var r0 []model.ShipCommentMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ShipCommentMediaRow, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ShipCommentMediaRow); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShipCommentMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMedia'
type MockShipRepository_GetCommentMedia_Call struct {
	*mock.Call
}

// GetCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockShipRepository_Expecter) GetCommentMedia(ctx interface{}, commentID interface{}) *MockShipRepository_GetCommentMedia_Call {
	return &MockShipRepository_GetCommentMedia_Call{Call: _e.mock.On("GetCommentMedia", ctx, commentID)}
}

func (_c *MockShipRepository_GetCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockShipRepository_GetCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCommentMedia_Call) Return(vs []model.ShipCommentMediaRow, err error) *MockShipRepository_GetCommentMedia_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockShipRepository_GetCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) ([]model.ShipCommentMediaRow, error)) *MockShipRepository_GetCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMediaBatch provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCommentMediaBatch(ctx context.Context, commentIDs []uuid.UUID) (map[uuid.UUID][]model.ShipCommentMediaRow, error) {
	ret := _mock.Called(ctx, commentIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMediaBatch")
	}

	var r0 map[uuid.UUID][]model.ShipCommentMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID][]model.ShipCommentMediaRow, error)); ok {
		return returnFunc(ctx, commentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID][]model.ShipCommentMediaRow); ok {
		r0 = returnFunc(ctx, commentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]model.ShipCommentMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCommentMediaBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMediaBatch'
type MockShipRepository_GetCommentMediaBatch_Call struct {
	*mock.Call
}

// GetCommentMediaBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - commentIDs []uuid.UUID
func (_e *MockShipRepository_Expecter) GetCommentMediaBatch(ctx interface{}, commentIDs interface{}) *MockShipRepository_GetCommentMediaBatch_Call {
	return &MockShipRepository_GetCommentMediaBatch_Call{Call: _e.mock.On("GetCommentMediaBatch", ctx, commentIDs)}
}

func (_c *MockShipRepository_GetCommentMediaBatch_Call) Run(run func(ctx context.Context, commentIDs []uuid.UUID)) *MockShipRepository_GetCommentMediaBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCommentMediaBatch_Call) Return(uUIDToVs map[uuid.UUID][]model.ShipCommentMediaRow, err error) *MockShipRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(uUIDToVs, err)
	return _c
}

func (_c *MockShipRepository_GetCommentMediaBatch_Call) RunAndReturn(run func(ctx context.Context, commentIDs []uuid.UUID) (map[uuid.UUID][]model.ShipCommentMediaRow, error)) *MockShipRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentShipID provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCommentShipID(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error) {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentShipID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return returnFunc(ctx, commentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, commentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCommentShipID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentShipID'
type MockShipRepository_GetCommentShipID_Call struct {
	*mock.Call
}

// GetCommentShipID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
func (_e *MockShipRepository_Expecter) GetCommentShipID(ctx interface{}, commentID interface{}) *MockShipRepository_GetCommentShipID_Call {
	return &MockShipRepository_GetCommentShipID_Call{Call: _e.mock.On("GetCommentShipID", ctx, commentID)}
}

func (_c *MockShipRepository_GetCommentShipID_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockShipRepository_GetCommentShipID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCommentShipID_Call) Return(uUID uuid.UUID, err error) *MockShipRepository_GetCommentShipID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockShipRepository_GetCommentShipID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) (uuid.UUID, error)) *MockShipRepository_GetCommentShipID_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetComments(ctx context.Context, shipID uuid.UUID, viewerID uuid.UUID, limit int, offset int, excludeUserIDs []uuid.UUID) ([]model.ShipCommentRow, int, error) {
	ret := _mock.Called(ctx, shipID, viewerID, limit, offset, excludeUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []model.ShipCommentRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, []uuid.UUID) ([]model.ShipCommentRow, int, error)); ok {
		return returnFunc(ctx, shipID, viewerID, limit, offset, excludeUserIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, []uuid.UUID) []model.ShipCommentRow); ok {
		r0 = returnFunc(ctx, shipID, viewerID, limit, offset, excludeUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShipCommentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int, []uuid.UUID) int); ok {
		r1 = returnFunc(ctx, shipID, viewerID, limit, offset, excludeUserIDs)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int, []uuid.UUID) error); ok {
		r2 = returnFunc(ctx, shipID, viewerID, limit, offset, excludeUserIDs)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockShipRepository_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockShipRepository_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - shipID uuid.UUID
//   - viewerID uuid.UUID
//   - limit int
//   - offset int
//   - excludeUserIDs []uuid.UUID
func (_e *MockShipRepository_Expecter) GetComments(ctx interface{}, shipID interface{}, viewerID interface{}, limit interface{}, offset interface{}, excludeUserIDs interface{}) *MockShipRepository_GetComments_Call {
	return &MockShipRepository_GetComments_Call{Call: _e.mock.On("GetComments", ctx, shipID, viewerID, limit, offset, excludeUserIDs)}
}

func (_c *MockShipRepository_GetComments_Call) Run(run func(ctx context.Context, shipID uuid.UUID, viewerID uuid.UUID, limit int, offset int, excludeUserIDs []uuid.UUID)) *MockShipRepository_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 []uuid.UUID
		if args[5] != nil {
			arg5 = args[5].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetComments_Call) Return(shipCommentRows []model.ShipCommentRow, n int, err error) *MockShipRepository_GetComments_Call {
	_c.Call.Return(shipCommentRows, n, err)
	return _c
}

func (_c *MockShipRepository_GetComments_Call) RunAndReturn(run func(ctx context.Context, shipID uuid.UUID, viewerID uuid.UUID, limit int, offset int, excludeUserIDs []uuid.UUID) ([]model.ShipCommentRow, int, error)) *MockShipRepository_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// LikeComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) LikeComment(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for LikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_LikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeComment'
type MockShipRepository_LikeComment_Call struct {
	*mock.Call
}

// LikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - commentID uuid.UUID
func (_e *MockShipRepository_Expecter) LikeComment(ctx interface{}, userID interface{}, commentID interface{}) *MockShipRepository_LikeComment_Call {
	return &MockShipRepository_LikeComment_Call{Call: _e.mock.On("LikeComment", ctx, userID, commentID)}
}

func (_c *MockShipRepository_LikeComment_Call) Run(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID)) *MockShipRepository_LikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipRepository_LikeComment_Call) Return(err error) *MockShipRepository_LikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_LikeComment_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error) *MockShipRepository_LikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) List(ctx context.Context, viewerID uuid.UUID, sort string, crackshipsOnly bool, series string, characterID string, limit int, offset int, excludeUserIDs []uuid.UUID) ([]model.ShipRow, int, error) {
	ret := _mock.Called(ctx, viewerID, sort, crackshipsOnly, series, characterID, limit, offset, excludeUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.ShipRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, bool, string, string, int, int, []uuid.UUID) ([]model.ShipRow, int, error)); ok {
		return returnFunc(ctx, viewerID, sort, crackshipsOnly, series, characterID, limit, offset, excludeUserIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, bool, string, string, int, int, []uuid.UUID) []model.ShipRow); ok {
		r0 = returnFunc(ctx, viewerID, sort, crackshipsOnly, series, characterID, limit, offset, excludeUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShipRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, bool, string, string, int, int, []uuid.UUID) int); ok {
		r1 = returnFunc(ctx, viewerID, sort, crackshipsOnly, series, characterID, limit, offset, excludeUserIDs)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, bool, string, string, int, int, []uuid.UUID) error); ok {
		r2 = returnFunc(ctx, viewerID, sort, crackshipsOnly, series, characterID, limit, offset, excludeUserIDs)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockShipRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockShipRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID uuid.UUID
//   - sort string
//   - crackshipsOnly bool
//   - series string
//   - characterID string
//   - limit int
//   - offset int
//   - excludeUserIDs []uuid.UUID
func (_e *MockShipRepository_Expecter) List(ctx interface{}, viewerID interface{}, sort interface{}, crackshipsOnly interface{}, series interface{}, characterID interface{}, limit interface{}, offset interface{}, excludeUserIDs interface{}) *MockShipRepository_List_Call {
	return &MockShipRepository_List_Call{Call: _e.mock.On("List", ctx, viewerID, sort, crackshipsOnly, series, characterID, limit, offset, excludeUserIDs)}
}

func (_c *MockShipRepository_List_Call) Run(run func(ctx context.Context, viewerID uuid.UUID, sort string, crackshipsOnly bool, series string, characterID string, limit int, offset int, excludeUserIDs []uuid.UUID)) *MockShipRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		var arg7 int
		if args[7] != nil {
			arg7 = args[7].(int)
		}
		var arg8 []uuid.UUID
		if args[8] != nil {
			arg8 = args[8].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
		)
	})
	return _c
}

func (_c *MockShipRepository_List_Call) Return(shipRows []model.ShipRow, n int, err error) *MockShipRepository_List_Call {
	_c.Call.Return(shipRows, n, err)
	return _c
}

func (_c *MockShipRepository_List_Call) RunAndReturn(run func(ctx context.Context, viewerID uuid.UUID, sort string, crackshipsOnly bool, series string, characterID string, limit int, offset int, excludeUserIDs []uuid.UUID) ([]model.ShipRow, int, error)) *MockShipRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) ListByUser(ctx context.Context, userID uuid.UUID, viewerID uuid.UUID, limit int, offset int) ([]model.ShipRow, int, error) {
	ret := _mock.Called(ctx, userID, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.ShipRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]model.ShipRow, int, error)); ok {
		return returnFunc(ctx, userID, viewerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) []model.ShipRow); ok {
		r0 = returnFunc(ctx, userID, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShipRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) int); ok {
		r1 = returnFunc(ctx, userID, viewerID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, userID, viewerID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockShipRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockShipRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - viewerID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockShipRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, viewerID interface{}, limit interface{}, offset interface{}) *MockShipRepository_ListByUser_Call {
	return &MockShipRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, viewerID, limit, offset)}
}

func (_c *MockShipRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, viewerID uuid.UUID, limit int, offset int)) *MockShipRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockShipRepository_ListByUser_Call) Return(shipRows []model.ShipRow, n int, err error) *MockShipRepository_ListByUser_Call {
	_c.Call.Return(shipRows, n, err)
	return _c
}

func (_c *MockShipRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, viewerID uuid.UUID, limit int, offset int) ([]model.ShipRow, int, error)) *MockShipRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UnlikeComment(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for UnlikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UnlikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeComment'
type MockShipRepository_UnlikeComment_Call struct {
	*mock.Call
}

// UnlikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - commentID uuid.UUID
func (_e *MockShipRepository_Expecter) UnlikeComment(ctx interface{}, userID interface{}, commentID interface{}) *MockShipRepository_UnlikeComment_Call {
	return &MockShipRepository_UnlikeComment_Call{Call: _e.mock.On("UnlikeComment", ctx, userID, commentID)}
}

func (_c *MockShipRepository_UnlikeComment_Call) Run(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID)) *MockShipRepository_UnlikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipRepository_UnlikeComment_Call) Return(err error) *MockShipRepository_UnlikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UnlikeComment_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, commentID uuid.UUID) error) *MockShipRepository_UnlikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateComment(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, userID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockShipRepository_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockShipRepository_Expecter) UpdateComment(ctx interface{}, id interface{}, userID interface{}, body interface{}) *MockShipRepository_UpdateComment_Call {
	return &MockShipRepository_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, id, userID, body)}
}

func (_c *MockShipRepository_UpdateComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string)) *MockShipRepository_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateComment_Call) Return(err error) *MockShipRepository_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error) *MockShipRepository_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentAsAdmin provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateCommentAsAdmin(ctx context.Context, id uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentAsAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateCommentAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentAsAdmin'
type MockShipRepository_UpdateCommentAsAdmin_Call struct {
	*mock.Call
}

// UpdateCommentAsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - body string
func (_e *MockShipRepository_Expecter) UpdateCommentAsAdmin(ctx interface{}, id interface{}, body interface{}) *MockShipRepository_UpdateCommentAsAdmin_Call {
	return &MockShipRepository_UpdateCommentAsAdmin_Call{Call: _e.mock.On("UpdateCommentAsAdmin", ctx, id, body)}
}

func (_c *MockShipRepository_UpdateCommentAsAdmin_Call) Run(run func(ctx context.Context, id uuid.UUID, body string)) *MockShipRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateCommentAsAdmin_Call) Return(err error) *MockShipRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateCommentAsAdmin_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, body string) error) *MockShipRepository_UpdateCommentAsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaThumbnail provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateCommentMediaThumbnail(ctx context.Context, id int64, thumbnailURL string) error {
	ret := _mock.Called(ctx, id, thumbnailURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaThumbnail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, thumbnailURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateCommentMediaThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaThumbnail'
type MockShipRepository_UpdateCommentMediaThumbnail_Call struct {
	*mock.Call
}

// UpdateCommentMediaThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - thumbnailURL string
func (_e *MockShipRepository_Expecter) UpdateCommentMediaThumbnail(ctx interface{}, id interface{}, thumbnailURL interface{}) *MockShipRepository_UpdateCommentMediaThumbnail_Call {
	return &MockShipRepository_UpdateCommentMediaThumbnail_Call{Call: _e.mock.On("UpdateCommentMediaThumbnail", ctx, id, thumbnailURL)}
}

func (_c *MockShipRepository_UpdateCommentMediaThumbnail_Call) Run(run func(ctx context.Context, id int64, thumbnailURL string)) *MockShipRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateCommentMediaThumbnail_Call) Return(err error) *MockShipRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateCommentMediaThumbnail_Call) RunAndReturn(run func(ctx context.Context, id int64, thumbnailURL string) error) *MockShipRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaURL provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateCommentMediaURL(ctx context.Context, id int64, mediaURL string) error {
	ret := _mock.Called(ctx, id, mediaURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, mediaURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateCommentMediaURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaURL'
type MockShipRepository_UpdateCommentMediaURL_Call struct {
	*mock.Call
}

// UpdateCommentMediaURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - mediaURL string
func (_e *MockShipRepository_Expecter) UpdateCommentMediaURL(ctx interface{}, id interface{}, mediaURL interface{}) *MockShipRepository_UpdateCommentMediaURL_Call {
	return &MockShipRepository_UpdateCommentMediaURL_Call{Call: _e.mock.On("UpdateCommentMediaURL", ctx, id, mediaURL)}
}

func (_c *MockShipRepository_UpdateCommentMediaURL_Call) Run(run func(ctx context.Context, id int64, mediaURL string)) *MockShipRepository_UpdateCommentMediaURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateCommentMediaURL_Call) Return(err error) *MockShipRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateCommentMediaURL_Call) RunAndReturn(run func(ctx context.Context, id int64, mediaURL string) error) *MockShipRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImage provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateImage(ctx context.Context, id uuid.UUID, imageURL string, thumbnailURL string) error {
	ret := _mock.Called(ctx, id, imageURL, thumbnailURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, id, imageURL, thumbnailURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImage'
type MockShipRepository_UpdateImage_Call struct {
	*mock.Call
}

// UpdateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - imageURL string
//   - thumbnailURL string
func (_e *MockShipRepository_Expecter) UpdateImage(ctx interface{}, id interface{}, imageURL interface{}, thumbnailURL interface{}) *MockShipRepository_UpdateImage_Call {
	return &MockShipRepository_UpdateImage_Call{Call: _e.mock.On("UpdateImage", ctx, id, imageURL, thumbnailURL)}
}

func (_c *MockShipRepository_UpdateImage_Call) Run(run func(ctx context.Context, id uuid.UUID, imageURL string, thumbnailURL string)) *MockShipRepository_UpdateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateImage_Call) Return(err error) *MockShipRepository_UpdateImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateImage_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, imageURL string, thumbnailURL string) error) *MockShipRepository_UpdateImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithCharacters provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateWithCharacters(ctx context.Context, id uuid.UUID, userID uuid.UUID, title string, description string, characters []dto.ShipCharacter, asAdmin bool) error {
	ret := _mock.Called(ctx, id, userID, title, description, characters, asAdmin)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithCharacters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, []dto.ShipCharacter, bool) error); ok {
		r0 = returnFunc(ctx, id, userID, title, description, characters, asAdmin)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateWithCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithCharacters'
type MockShipRepository_UpdateWithCharacters_Call struct {
	*mock.Call
}

// UpdateWithCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - title string
//   - description string
//   - characters []dto.ShipCharacter
//   - asAdmin bool
func (_e *MockShipRepository_Expecter) UpdateWithCharacters(ctx interface{}, id interface{}, userID interface{}, title interface{}, description interface{}, characters interface{}, asAdmin interface{}) *MockShipRepository_UpdateWithCharacters_Call {
	return &MockShipRepository_UpdateWithCharacters_Call{Call: _e.mock.On("UpdateWithCharacters", ctx, id, userID, title, description, characters, asAdmin)}
}

func (_c *MockShipRepository_UpdateWithCharacters_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, title string, description string, characters []dto.ShipCharacter, asAdmin bool)) *MockShipRepository_UpdateWithCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []dto.ShipCharacter
		if args[5] != nil {
			arg5 = args[5].([]dto.ShipCharacter)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateWithCharacters_Call) Return(err error) *MockShipRepository_UpdateWithCharacters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateWithCharacters_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, title string, description string, characters []dto.ShipCharacter, asAdmin bool) error) *MockShipRepository_UpdateWithCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// Vote provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) Vote(ctx context.Context, userID uuid.UUID, shipID uuid.UUID, value int) error {
	ret := _mock.Called(ctx, userID, shipID, value)

	if len(ret) == 0 {
		panic("no return value specified for Vote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, userID, shipID, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_Vote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Vote'
type MockShipRepository_Vote_Call struct {
	*mock.Call
}

// Vote is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - shipID uuid.UUID
//   - value int
func (_e *MockShipRepository_Expecter) Vote(ctx interface{}, userID interface{}, shipID interface{}, value interface{}) *MockShipRepository_Vote_Call {
	return &MockShipRepository_Vote_Call{Call: _e.mock.On("Vote", ctx, userID, shipID, value)}
}

func (_c *MockShipRepository_Vote_Call) Run(run func(ctx context.Context, userID uuid.UUID, shipID uuid.UUID, value int)) *MockShipRepository_Vote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockShipRepository_Vote_Call) Return(err error) *MockShipRepository_Vote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_Vote_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, shipID uuid.UUID, value int) error) *MockShipRepository_Vote_Call {
	_c.Call.Return(run)
	return _c
}
