// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStatsRepository creates a new instance of MockStatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsRepository {
	mock := &MockStatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatsRepository is an autogenerated mock type for the StatsRepository type
type MockStatsRepository struct {
	mock.Mock
}

type MockStatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsRepository) EXPECT() *MockStatsRepository_Expecter {
	return &MockStatsRepository_Expecter{mock: &_m.Mock}
}

// GetMostActiveUsers provides a mock function for the type MockStatsRepository
func (_mock *MockStatsRepository) GetMostActiveUsers(ctx context.Context, limit int) ([]ActiveUser, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMostActiveUsers")
	}

	var r0 []ActiveUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]ActiveUser, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []ActiveUser); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ActiveUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatsRepository_GetMostActiveUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMostActiveUsers'
type MockStatsRepository_GetMostActiveUsers_Call struct {
	*mock.Call
}

// GetMostActiveUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockStatsRepository_Expecter) GetMostActiveUsers(ctx interface{}, limit interface{}) *MockStatsRepository_GetMostActiveUsers_Call {
	return &MockStatsRepository_GetMostActiveUsers_Call{Call: _e.mock.On("GetMostActiveUsers", ctx, limit)}
}

func (_c *MockStatsRepository_GetMostActiveUsers_Call) Run(run func(ctx context.Context, limit int)) *MockStatsRepository_GetMostActiveUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatsRepository_GetMostActiveUsers_Call) Return(activeUsers []ActiveUser, err error) *MockStatsRepository_GetMostActiveUsers_Call {
	_c.Call.Return(activeUsers, err)
	return _c
}

func (_c *MockStatsRepository_GetMostActiveUsers_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]ActiveUser, error)) *MockStatsRepository_GetMostActiveUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverview provides a mock function for the type MockStatsRepository
func (_mock *MockStatsRepository) GetOverview(ctx context.Context) (*SiteStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOverview")
	}

	var r0 *SiteStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*SiteStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *SiteStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SiteStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatsRepository_GetOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverview'
type MockStatsRepository_GetOverview_Call struct {
	*mock.Call
}

// GetOverview is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStatsRepository_Expecter) GetOverview(ctx interface{}) *MockStatsRepository_GetOverview_Call {
	return &MockStatsRepository_GetOverview_Call{Call: _e.mock.On("GetOverview", ctx)}
}

func (_c *MockStatsRepository_GetOverview_Call) Run(run func(ctx context.Context)) *MockStatsRepository_GetOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatsRepository_GetOverview_Call) Return(siteStats *SiteStats, err error) *MockStatsRepository_GetOverview_Call {
	_c.Call.Return(siteStats, err)
	return _c
}

func (_c *MockStatsRepository_GetOverview_Call) RunAndReturn(run func(ctx context.Context) (*SiteStats, error)) *MockStatsRepository_GetOverview_Call {
	_c.Call.Return(run)
	return _c
}
