// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUploadRepository creates a new instance of MockUploadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadRepository {
	mock := &MockUploadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadRepository is an autogenerated mock type for the UploadRepository type
type MockUploadRepository struct {
	mock.Mock
}

type MockUploadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadRepository) EXPECT() *MockUploadRepository_Expecter {
	return &MockUploadRepository_Expecter{mock: &_m.Mock}
}

// GetAllReferencedFiles provides a mock function for the type MockUploadRepository
func (_mock *MockUploadRepository) GetAllReferencedFiles() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllReferencedFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadRepository_GetAllReferencedFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllReferencedFiles'
type MockUploadRepository_GetAllReferencedFiles_Call struct {
	*mock.Call
}

// GetAllReferencedFiles is a helper method to define mock.On call
func (_e *MockUploadRepository_Expecter) GetAllReferencedFiles() *MockUploadRepository_GetAllReferencedFiles_Call {
	return &MockUploadRepository_GetAllReferencedFiles_Call{Call: _e.mock.On("GetAllReferencedFiles")}
}

func (_c *MockUploadRepository_GetAllReferencedFiles_Call) Run(run func()) *MockUploadRepository_GetAllReferencedFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadRepository_GetAllReferencedFiles_Call) Return(strings []string, err error) *MockUploadRepository_GetAllReferencedFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockUploadRepository_GetAllReferencedFiles_Call) RunAndReturn(run func() ([]string, error)) *MockUploadRepository_GetAllReferencedFiles_Call {
	_c.Call.Return(run)
	return _c
}
