// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package upload

import (
	"context"
	"io"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(urlPath string) error {
	ret := _mock.Called(urlPath)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(urlPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - urlPath string
func (_e *MockService_Expecter) Delete(urlPath interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", urlPath)}
}

func (_c *MockService_Delete_Call) Run(run func(urlPath string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(urlPath string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByPrefix provides a mock function for the type MockService
func (_mock *MockService) DeleteByPrefix(subDir string, prefix string) error {
	ret := _mock.Called(subDir, prefix)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPrefix")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(subDir, prefix)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteByPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPrefix'
type MockService_DeleteByPrefix_Call struct {
	*mock.Call
}

// DeleteByPrefix is a helper method to define mock.On call
//   - subDir string
//   - prefix string
func (_e *MockService_Expecter) DeleteByPrefix(subDir interface{}, prefix interface{}) *MockService_DeleteByPrefix_Call {
	return &MockService_DeleteByPrefix_Call{Call: _e.mock.On("DeleteByPrefix", subDir, prefix)}
}

func (_c *MockService_DeleteByPrefix_Call) Run(run func(subDir string, prefix string)) *MockService_DeleteByPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteByPrefix_Call) Return(err error) *MockService_DeleteByPrefix_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteByPrefix_Call) RunAndReturn(run func(subDir string, prefix string) error) *MockService_DeleteByPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// FullDiskPath provides a mock function for the type MockService
func (_mock *MockService) FullDiskPath(urlPath string) string {
	ret := _mock.Called(urlPath)

	if len(ret) == 0 {
		panic("no return value specified for FullDiskPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(urlPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockService_FullDiskPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullDiskPath'
type MockService_FullDiskPath_Call struct {
	*mock.Call
}

// FullDiskPath is a helper method to define mock.On call
//   - urlPath string
func (_e *MockService_Expecter) FullDiskPath(urlPath interface{}) *MockService_FullDiskPath_Call {
	return &MockService_FullDiskPath_Call{Call: _e.mock.On("FullDiskPath", urlPath)}
}

func (_c *MockService_FullDiskPath_Call) Run(run func(urlPath string)) *MockService_FullDiskPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_FullDiskPath_Call) Return(s string) *MockService_FullDiskPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockService_FullDiskPath_Call) RunAndReturn(run func(urlPath string) string) *MockService_FullDiskPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadDir provides a mock function for the type MockService
func (_mock *MockService) GetUploadDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUploadDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockService_GetUploadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadDir'
type MockService_GetUploadDir_Call struct {
	*mock.Call
}

// GetUploadDir is a helper method to define mock.On call
func (_e *MockService_Expecter) GetUploadDir() *MockService_GetUploadDir_Call {
	return &MockService_GetUploadDir_Call{Call: _e.mock.On("GetUploadDir")}
}

func (_c *MockService_GetUploadDir_Call) Run(run func()) *MockService_GetUploadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetUploadDir_Call) Return(s string) *MockService_GetUploadDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockService_GetUploadDir_Call) RunAndReturn(run func() string) *MockService_GetUploadDir_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFile provides a mock function for the type MockService
func (_mock *MockService) SaveFile(subDir string, filename string, reader io.Reader) (string, error) {
	ret := _mock.Called(subDir, filename, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader) (string, error)); ok {
		return returnFunc(subDir, filename, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader) string); ok {
		r0 = returnFunc(subDir, filename, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = returnFunc(subDir, filename, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SaveFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFile'
type MockService_SaveFile_Call struct {
	*mock.Call
}

// SaveFile is a helper method to define mock.On call
//   - subDir string
//   - filename string
//   - reader io.Reader
func (_e *MockService_Expecter) SaveFile(subDir interface{}, filename interface{}, reader interface{}) *MockService_SaveFile_Call {
	return &MockService_SaveFile_Call{Call: _e.mock.On("SaveFile", subDir, filename, reader)}
}

func (_c *MockService_SaveFile_Call) Run(run func(subDir string, filename string, reader io.Reader)) *MockService_SaveFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SaveFile_Call) Return(s string, err error) *MockService_SaveFile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_SaveFile_Call) RunAndReturn(run func(subDir string, filename string, reader io.Reader) (string, error)) *MockService_SaveFile_Call {
	_c.Call.Return(run)
	return _c
}

// SaveImage provides a mock function for the type MockService
func (_mock *MockService) SaveImage(ctx context.Context, subDir string, id uuid.UUID, contentType string, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, subDir, id, contentType, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, subDir, id, contentType, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, subDir, id, contentType, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, string, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, subDir, id, contentType, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SaveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveImage'
type MockService_SaveImage_Call struct {
	*mock.Call
}

// SaveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - id uuid.UUID
//   - contentType string
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) SaveImage(ctx interface{}, subDir interface{}, id interface{}, contentType interface{}, fileSize interface{}, maxSize interface{}, reader interface{}) *MockService_SaveImage_Call {
	return &MockService_SaveImage_Call{Call: _e.mock.On("SaveImage", ctx, subDir, id, contentType, fileSize, maxSize, reader)}
}

func (_c *MockService_SaveImage_Call) Run(run func(ctx context.Context, subDir string, id uuid.UUID, contentType string, fileSize int64, maxSize int64, reader io.Reader)) *MockService_SaveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 io.Reader
		if args[6] != nil {
			arg6 = args[6].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockService_SaveImage_Call) Return(s string, err error) *MockService_SaveImage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_SaveImage_Call) RunAndReturn(run func(ctx context.Context, subDir string, id uuid.UUID, contentType string, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *MockService_SaveImage_Call {
	_c.Call.Return(run)
	return _c
}

// SaveVideo provides a mock function for the type MockService
func (_mock *MockService) SaveVideo(ctx context.Context, subDir string, id uuid.UUID, contentType string, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, subDir, id, contentType, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveVideo")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, subDir, id, contentType, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, subDir, id, contentType, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, string, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, subDir, id, contentType, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SaveVideo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveVideo'
type MockService_SaveVideo_Call struct {
	*mock.Call
}

// SaveVideo is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - id uuid.UUID
//   - contentType string
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) SaveVideo(ctx interface{}, subDir interface{}, id interface{}, contentType interface{}, fileSize interface{}, maxSize interface{}, reader interface{}) *MockService_SaveVideo_Call {
	return &MockService_SaveVideo_Call{Call: _e.mock.On("SaveVideo", ctx, subDir, id, contentType, fileSize, maxSize, reader)}
}

func (_c *MockService_SaveVideo_Call) Run(run func(ctx context.Context, subDir string, id uuid.UUID, contentType string, fileSize int64, maxSize int64, reader io.Reader)) *MockService_SaveVideo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 io.Reader
		if args[6] != nil {
			arg6 = args[6].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockService_SaveVideo_Call) Return(s string, err error) *MockService_SaveVideo_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_SaveVideo_Call) RunAndReturn(run func(ctx context.Context, subDir string, id uuid.UUID, contentType string, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *MockService_SaveVideo_Call {
	_c.Call.Return(run)
	return _c
}
