// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	"context"
	"umineko_city_of_books/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, userID uuid.UUID, limit int, offset int) (*dto.NotificationListResponse, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.NotificationListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) (*dto.NotificationListResponse, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) *dto.NotificationListResponse); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.NotificationListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) List(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, userID, limit, offset)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(notificationListResponse *dto.NotificationListResponse, err error) *MockService_List_Call {
	_c.Call.Return(notificationListResponse, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int, offset int) (*dto.NotificationListResponse, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function for the type MockService
func (_mock *MockService) MarkAllRead(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockService_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) MarkAllRead(ctx interface{}, userID interface{}) *MockService_MarkAllRead_Call {
	return &MockService_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *MockService_MarkAllRead_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_MarkAllRead_Call) Return(err error) *MockService_MarkAllRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_MarkAllRead_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockService_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockService
func (_mock *MockService) MarkRead(ctx context.Context, id int, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockService_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - userID uuid.UUID
func (_e *MockService_Expecter) MarkRead(ctx interface{}, id interface{}, userID interface{}) *MockService_MarkRead_Call {
	return &MockService_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, id, userID)}
}

func (_c *MockService_MarkRead_Call) Run(run func(ctx context.Context, id int, userID uuid.UUID)) *MockService_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_MarkRead_Call) Return(err error) *MockService_MarkRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_MarkRead_Call) RunAndReturn(run func(ctx context.Context, id int, userID uuid.UUID) error) *MockService_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function for the type MockService
func (_mock *MockService) Notify(ctx context.Context, params dto.NotifyParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.NotifyParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockService_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - params dto.NotifyParams
func (_e *MockService_Expecter) Notify(ctx interface{}, params interface{}) *MockService_Notify_Call {
	return &MockService_Notify_Call{Call: _e.mock.On("Notify", ctx, params)}
}

func (_c *MockService_Notify_Call) Run(run func(ctx context.Context, params dto.NotifyParams)) *MockService_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.NotifyParams
		if args[1] != nil {
			arg1 = args[1].(dto.NotifyParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Notify_Call) Return(err error) *MockService_Notify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Notify_Call) RunAndReturn(run func(ctx context.Context, params dto.NotifyParams) error) *MockService_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyMany provides a mock function for the type MockService
func (_mock *MockService) NotifyMany(ctx context.Context, params []dto.NotifyParams) {
	_mock.Called(ctx, params)
	return
}

// MockService_NotifyMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyMany'
type MockService_NotifyMany_Call struct {
	*mock.Call
}

// NotifyMany is a helper method to define mock.On call
//   - ctx context.Context
//   - params []dto.NotifyParams
func (_e *MockService_Expecter) NotifyMany(ctx interface{}, params interface{}) *MockService_NotifyMany_Call {
	return &MockService_NotifyMany_Call{Call: _e.mock.On("NotifyMany", ctx, params)}
}

func (_c *MockService_NotifyMany_Call) Run(run func(ctx context.Context, params []dto.NotifyParams)) *MockService_NotifyMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []dto.NotifyParams
		if args[1] != nil {
			arg1 = args[1].([]dto.NotifyParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_NotifyMany_Call) Return() *MockService_NotifyMany_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_NotifyMany_Call) RunAndReturn(run func(ctx context.Context, params []dto.NotifyParams)) *MockService_NotifyMany_Call {
	_c.Run(run)
	return _c
}

// UnreadCount provides a mock function for the type MockService
func (_mock *MockService) UnreadCount(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnreadCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnreadCount'
type MockService_UnreadCount_Call struct {
	*mock.Call
}

// UnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) UnreadCount(ctx interface{}, userID interface{}) *MockService_UnreadCount_Call {
	return &MockService_UnreadCount_Call{Call: _e.mock.On("UnreadCount", ctx, userID)}
}

func (_c *MockService_UnreadCount_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_UnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_UnreadCount_Call) Return(n int, err error) *MockService_UnreadCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_UnreadCount_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int, error)) *MockService_UnreadCount_Call {
	_c.Call.Return(run)
	return _c
}
