-- +goose Up

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    id UUID PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL,
    bio TEXT NOT NULL DEFAULT '',
    avatar_url TEXT NOT NULL DEFAULT '',
    banner_url TEXT NOT NULL DEFAULT '',
    favourite_character TEXT NOT NULL DEFAULT '',
    gender TEXT NOT NULL DEFAULT '',
    social_twitter TEXT NOT NULL DEFAULT '',
    social_discord TEXT NOT NULL DEFAULT '',
    social_waifulist TEXT NOT NULL DEFAULT '',
    social_tumblr TEXT NOT NULL DEFAULT '',
    social_github TEXT NOT NULL DEFAULT '',
    website TEXT NOT NULL DEFAULT '',
    pronoun_subject TEXT NOT NULL DEFAULT 'they',
    pronoun_possessive TEXT NOT NULL DEFAULT 'their',
    banner_position REAL NOT NULL DEFAULT 50.0,
    dms_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email TEXT NOT NULL DEFAULT '',
    email_public BOOLEAN NOT NULL DEFAULT FALSE,
    email_notifications BOOLEAN NOT NULL DEFAULT FALSE,
    home_page TEXT NOT NULL DEFAULT 'theories',
    episode_progress INTEGER NOT NULL DEFAULT 0,
    ip TEXT,
    game_board_sort TEXT NOT NULL DEFAULT 'relevance',
    mystery_score_adjustment INTEGER NOT NULL DEFAULT 0,
    gm_score_adjustment INTEGER NOT NULL DEFAULT 0,
    theme TEXT NOT NULL DEFAULT '',
    font TEXT NOT NULL DEFAULT '',
    wide_layout BOOLEAN NOT NULL DEFAULT FALSE,
    dob TEXT NOT NULL DEFAULT '',
    dob_public BOOLEAN NOT NULL DEFAULT FALSE,
    play_message_sound BOOLEAN NOT NULL DEFAULT TRUE,
    play_notification_sound BOOLEAN NOT NULL DEFAULT TRUE,
    higurashi_arc_progress INTEGER NOT NULL DEFAULT 0,
    ciconia_chapter_progress INTEGER NOT NULL DEFAULT 0,
    banned_at TIMESTAMPTZ,
    banned_by UUID REFERENCES users(id) ON DELETE SET NULL,
    ban_reason TEXT NOT NULL DEFAULT '',
    locked_at TIMESTAMPTZ,
    locked_by UUID REFERENCES users(id) ON DELETE SET NULL,
    lock_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE sessions (
    token TEXT PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE theories (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    episode INTEGER NOT NULL DEFAULT 0,
    series TEXT NOT NULL DEFAULT 'umineko',
    credibility_score REAL NOT NULL DEFAULT 50.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE theory_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theory_id UUID NOT NULL REFERENCES theories(id) ON DELETE CASCADE,
    audio_id TEXT NOT NULL,
    quote_index INTEGER,
    note TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    truth_weight REAL NOT NULL DEFAULT 1.0,
    lang TEXT NOT NULL DEFAULT 'en'
);

CREATE TABLE responses (
    id UUID PRIMARY KEY,
    theory_id UUID NOT NULL REFERENCES theories(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES responses(id) ON DELETE CASCADE,
    side TEXT NOT NULL CHECK (side IN ('with_love', 'without_love')),
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE response_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id UUID NOT NULL REFERENCES responses(id) ON DELETE CASCADE,
    audio_id TEXT NOT NULL,
    quote_index INTEGER,
    note TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    truth_weight REAL NOT NULL DEFAULT 1.0,
    lang TEXT NOT NULL DEFAULT 'en'
);

CREATE TABLE theory_votes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    theory_id UUID NOT NULL REFERENCES theories(id) ON DELETE CASCADE,
    value INTEGER NOT NULL CHECK (value IN (1, -1)),
    PRIMARY KEY (user_id, theory_id)
);

CREATE TABLE response_votes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    response_id UUID NOT NULL REFERENCES responses(id) ON DELETE CASCADE,
    value INTEGER NOT NULL CHECK (value IN (1, -1)),
    PRIMARY KEY (user_id, response_id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    reference_id TEXT NOT NULL,
    reference_type TEXT NOT NULL DEFAULT 'theory',
    actor_id UUID REFERENCES users(id) ON DELETE SET NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE user_roles (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    PRIMARY KEY (user_id, role)
);

CREATE TABLE site_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by UUID REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id UUID REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT,
    details TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE invites (
    code TEXT PRIMARY KEY,
    created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    used_by UUID REFERENCES users(id) ON DELETE SET NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE chat_rooms (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    type TEXT NOT NULL CHECK (type IN ('dm', 'group')),
    created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    last_message_at TIMESTAMPTZ,
    dm_pair_key TEXT,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT NOT NULL DEFAULT '',
    is_rp BOOLEAN NOT NULL DEFAULT FALSE,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    system_kind TEXT,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE chat_room_members (
    room_id UUID NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_read_at TIMESTAMPTZ,
    role TEXT NOT NULL DEFAULT 'member',
    nickname TEXT NOT NULL DEFAULT '',
    avatar_url TEXT NOT NULL DEFAULT '',
    muted BOOLEAN NOT NULL DEFAULT FALSE,
    nickname_locked BOOLEAN NOT NULL DEFAULT FALSE,
    left_at TIMESTAMPTZ,
    timeout_until TIMESTAMPTZ,
    timeout_set_by_staff BOOLEAN NOT NULL DEFAULT FALSE,
    ghost BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE chat_messages (
    id UUID PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    reply_to_id UUID REFERENCES chat_messages(id) ON DELETE SET NULL,
    pinned_at TIMESTAMPTZ,
    pinned_by UUID REFERENCES users(id) ON DELETE SET NULL,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    edited_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE chat_message_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id UUID NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE chat_message_reactions (
    message_id UUID NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    emoji TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (message_id, user_id, emoji)
);

CREATE TABLE chat_room_tags (
    room_id UUID NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    tag TEXT NOT NULL,
    PRIMARY KEY (room_id, tag)
);

CREATE TABLE chat_room_bans (
    room_id UUID NOT NULL REFERENCES chat_rooms(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    banned_by UUID REFERENCES users(id) ON DELETE SET NULL,
    reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE chat_banned_words (
    id UUID PRIMARY KEY,
    scope TEXT NOT NULL CHECK (scope IN ('global','room')),
    room_id UUID REFERENCES chat_rooms(id) ON DELETE CASCADE,
    pattern TEXT NOT NULL,
    match_mode TEXT NOT NULL CHECK (match_mode IN ('substring','whole_word','regex')),
    case_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    action TEXT NOT NULL CHECK (action IN ('delete','kick')),
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK ((scope = 'global' AND room_id IS NULL) OR (scope = 'room' AND room_id IS NOT NULL))
);

CREATE TABLE posts (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    corner TEXT NOT NULL DEFAULT 'general',
    updated_at TIMESTAMPTZ,
    shared_content_id TEXT,
    shared_content_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video')),
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE post_views (
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    viewer_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (post_id, viewer_hash)
);

CREATE TABLE follows (
    follower_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    following_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (follower_id, following_id)
);

CREATE TABLE post_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, post_id)
);

CREATE TABLE post_comments (
    id UUID PRIMARY KEY,
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    parent_id UUID REFERENCES post_comments(id) ON DELETE CASCADE,
    updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE post_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES post_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video')),
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE post_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES post_comments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE post_polls (
    id UUID PRIMARY KEY,
    post_id UUID NOT NULL UNIQUE REFERENCES posts(id) ON DELETE CASCADE,
    duration_seconds INTEGER NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE post_poll_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id UUID NOT NULL REFERENCES post_polls(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE post_poll_votes (
    poll_id UUID NOT NULL REFERENCES post_polls(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    option_id BIGINT NOT NULL REFERENCES post_poll_options(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (poll_id, user_id)
);

CREATE TABLE suggestion_resolved (
    post_id UUID PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
    resolved_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'done',
    resolved_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE share_counts (
    content_id TEXT NOT NULL,
    content_type TEXT NOT NULL,
    share_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (content_id, content_type)
);

CREATE TABLE embeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL,
    owner_type TEXT NOT NULL CHECK (owner_type IN ('post', 'comment')),
    url TEXT NOT NULL,
    embed_type TEXT NOT NULL CHECK (embed_type IN ('link', 'youtube')),
    title TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    image TEXT NOT NULL DEFAULT '',
    site_name TEXT NOT NULL DEFAULT '',
    video_id TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE art (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    corner TEXT NOT NULL DEFAULT 'general',
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    image_url TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    view_count INTEGER NOT NULL DEFAULT 0,
    art_type TEXT NOT NULL DEFAULT 'drawing',
    is_spoiler BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE galleries (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    cover_art_id UUID REFERENCES art(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

ALTER TABLE art ADD COLUMN gallery_id UUID REFERENCES galleries(id) ON DELETE SET NULL;

CREATE TABLE art_tags (
    art_id UUID NOT NULL REFERENCES art(id) ON DELETE CASCADE,
    tag TEXT NOT NULL,
    PRIMARY KEY (art_id, tag)
);

CREATE TABLE art_views (
    art_id UUID NOT NULL REFERENCES art(id) ON DELETE CASCADE,
    viewer_hash TEXT NOT NULL,
    PRIMARY KEY (art_id, viewer_hash)
);

CREATE TABLE art_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    art_id UUID NOT NULL REFERENCES art(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, art_id)
);

CREATE TABLE art_comments (
    id UUID PRIMARY KEY,
    art_id UUID NOT NULL REFERENCES art(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES art_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE art_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES art_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video')),
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE art_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES art_comments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    resolved_by UUID REFERENCES users(id) ON DELETE SET NULL,
    context_id TEXT NOT NULL DEFAULT '',
    resolution_comment TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE blocks (
    blocker_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE mysteries (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    difficulty TEXT NOT NULL DEFAULT 'medium',
    solved BOOLEAN NOT NULL DEFAULT FALSE,
    winner_id UUID REFERENCES users(id) ON DELETE SET NULL,
    solved_at TIMESTAMPTZ,
    paused BOOLEAN NOT NULL DEFAULT FALSE,
    paused_at TIMESTAMPTZ,
    paused_duration_seconds INTEGER NOT NULL DEFAULT 0,
    free_for_all BOOLEAN NOT NULL DEFAULT FALSE,
    gm_away BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE mystery_clues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mystery_id UUID NOT NULL REFERENCES mysteries(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    truth_type TEXT NOT NULL DEFAULT 'red',
    sort_order INTEGER NOT NULL DEFAULT 0,
    player_id UUID REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE mystery_attempts (
    id UUID PRIMARY KEY,
    mystery_id UUID NOT NULL REFERENCES mysteries(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES mystery_attempts(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    is_winner BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE mystery_attempt_votes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    attempt_id UUID NOT NULL REFERENCES mystery_attempts(id) ON DELETE CASCADE,
    value INTEGER NOT NULL CHECK (value IN (1, -1)),
    PRIMARY KEY (user_id, attempt_id)
);

CREATE TABLE mystery_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mystery_id UUID NOT NULL REFERENCES mysteries(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE mystery_comments (
    id UUID PRIMARY KEY,
    mystery_id UUID NOT NULL REFERENCES mysteries(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES mystery_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE mystery_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES mystery_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE mystery_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES mystery_comments(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE ships (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    image_url TEXT NOT NULL DEFAULT '',
    thumbnail_url TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ship_characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ship_id UUID NOT NULL REFERENCES ships(id) ON DELETE CASCADE,
    series TEXT NOT NULL,
    character_id TEXT NOT NULL DEFAULT '',
    character_name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE ship_votes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ship_id UUID NOT NULL REFERENCES ships(id) ON DELETE CASCADE,
    value INTEGER NOT NULL CHECK (value IN (1, -1)),
    PRIMARY KEY (user_id, ship_id)
);

CREATE TABLE ship_comments (
    id UUID PRIMARY KEY,
    ship_id UUID NOT NULL REFERENCES ships(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES ship_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE ship_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES ship_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE ship_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES ship_comments(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE announcements (
    id UUID PRIMARY KEY,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE announcement_comments (
    id UUID PRIMARY KEY,
    announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES announcement_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE announcement_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES announcement_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE announcement_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES announcement_comments(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE fanfic_series (
    name CITEXT PRIMARY KEY
);

CREATE TABLE fanfic_languages (
    name CITEXT PRIMARY KEY
);

CREATE TABLE fanfics (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    series TEXT NOT NULL DEFAULT 'Umineko',
    rating TEXT NOT NULL DEFAULT 'K',
    language TEXT NOT NULL DEFAULT 'English',
    status TEXT NOT NULL DEFAULT 'in_progress',
    is_oneshot BOOLEAN NOT NULL DEFAULT FALSE,
    cover_image_url TEXT NOT NULL DEFAULT '',
    cover_thumbnail_url TEXT NOT NULL DEFAULT '',
    word_count INTEGER NOT NULL DEFAULT 0,
    favourite_count INTEGER NOT NULL DEFAULT 0,
    view_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    contains_lemons BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE fanfic_chapters (
    id UUID PRIMARY KEY,
    fanfic_id UUID NOT NULL REFERENCES fanfics(id) ON DELETE CASCADE,
    chapter_number INTEGER NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    body TEXT NOT NULL DEFAULT '',
    word_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(fanfic_id, chapter_number)
);

CREATE TABLE fanfic_genres (
    fanfic_id UUID NOT NULL REFERENCES fanfics(id) ON DELETE CASCADE,
    genre TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (fanfic_id, genre)
);

CREATE TABLE fanfic_characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fanfic_id UUID NOT NULL REFERENCES fanfics(id) ON DELETE CASCADE,
    series TEXT NOT NULL,
    character_id TEXT NOT NULL DEFAULT '',
    character_name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_pairing BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE fanfic_oc_characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT NOT NULL UNIQUE,
    created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE fanfic_favourites (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fanfic_id UUID NOT NULL REFERENCES fanfics(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, fanfic_id)
);

CREATE TABLE fanfic_views (
    fanfic_id UUID NOT NULL REFERENCES fanfics(id) ON DELETE CASCADE,
    viewer_hash TEXT NOT NULL,
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (fanfic_id, viewer_hash)
);

CREATE TABLE fanfic_comments (
    id UUID PRIMARY KEY,
    fanfic_id UUID NOT NULL REFERENCES fanfics(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES fanfic_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE fanfic_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES fanfic_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE fanfic_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES fanfic_comments(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE fanfic_tags (
    fanfic_id UUID NOT NULL REFERENCES fanfics(id) ON DELETE CASCADE,
    tag TEXT NOT NULL,
    PRIMARY KEY (fanfic_id, tag)
);

CREATE TABLE fanfic_reading_progress (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fanfic_id UUID NOT NULL REFERENCES fanfics(id) ON DELETE CASCADE,
    chapter_number INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, fanfic_id)
);

CREATE TABLE journals (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    work TEXT NOT NULL DEFAULT 'general',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    last_author_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    archived_at TIMESTAMPTZ
);

CREATE TABLE journal_comments (
    id UUID PRIMARY KEY,
    journal_id UUID NOT NULL REFERENCES journals(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES journal_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE journal_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES journal_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE journal_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES journal_comments(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE journal_follows (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    journal_id UUID NOT NULL REFERENCES journals(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, journal_id)
);

CREATE TABLE vanity_roles (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    color TEXT NOT NULL DEFAULT '#888888',
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE user_vanity_roles (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    vanity_role_id TEXT NOT NULL REFERENCES vanity_roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, vanity_role_id)
);

CREATE TABLE user_secrets (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    secret_id TEXT NOT NULL,
    unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, secret_id)
);

CREATE TABLE secret_comments (
    id UUID PRIMARY KEY,
    secret_id TEXT NOT NULL,
    parent_id UUID REFERENCES secret_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE secret_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES secret_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE secret_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES secret_comments(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, comment_id)
);

CREATE TABLE giphy_favourites (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    giphy_id TEXT NOT NULL,
    url TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    preview_url TEXT NOT NULL DEFAULT '',
    width INTEGER NOT NULL DEFAULT 0,
    height INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, giphy_id)
);

CREATE TABLE banned_giphy (
    kind TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by TEXT,
    reason TEXT,
    PRIMARY KEY (kind, value)
);

CREATE TABLE game_rooms (
    id UUID PRIMARY KEY,
    game_type TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'active', 'finished', 'declined', 'abandoned')),
    state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    turn_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    winner_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    result TEXT,
    created_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ
);

CREATE TABLE game_room_players (
    room_id UUID NOT NULL REFERENCES game_rooms(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slot INTEGER NOT NULL,
    joined BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (room_id, user_id),
    UNIQUE (room_id, slot)
);

CREATE TABLE game_room_moves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES game_rooms(id) ON DELETE CASCADE,
    ply INTEGER NOT NULL,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    action_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (room_id, ply)
);

CREATE TABLE sidebar_last_visited (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    visited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, key)
);

CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX idx_theories_user_id ON theories(user_id);
CREATE INDEX idx_theories_created_at ON theories(created_at DESC);
CREATE INDEX idx_theories_episode ON theories(episode);
CREATE INDEX idx_theories_series ON theories(series);
CREATE INDEX idx_theories_credibility ON theories(credibility_score DESC);
CREATE INDEX idx_theory_evidence_theory_id ON theory_evidence(theory_id);
CREATE INDEX idx_responses_theory_id ON responses(theory_id);
CREATE INDEX idx_responses_user_id ON responses(user_id);
CREATE INDEX idx_responses_parent_id ON responses(parent_id);
CREATE INDEX idx_response_evidence_response_id ON response_evidence(response_id);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_user_read ON notifications(user_id, read);
CREATE INDEX idx_audit_log_actor ON audit_log(actor_id);
CREATE INDEX idx_audit_log_action ON audit_log(action);
CREATE INDEX idx_audit_log_created_at ON audit_log(created_at DESC);
CREATE INDEX idx_invites_created_by ON invites(created_by);
CREATE INDEX idx_chat_room_members_user ON chat_room_members(user_id);
CREATE INDEX idx_chat_room_members_active ON chat_room_members(room_id, user_id) WHERE left_at IS NULL;
CREATE INDEX idx_chat_messages_room ON chat_messages(room_id, created_at DESC);
CREATE INDEX idx_chat_messages_reply_to ON chat_messages(reply_to_id);
CREATE INDEX idx_chat_messages_pinned ON chat_messages(room_id, pinned_at) WHERE pinned_at IS NOT NULL;
CREATE INDEX idx_chat_message_media_message ON chat_message_media(message_id);
CREATE INDEX idx_chat_message_reactions_message ON chat_message_reactions(message_id);
CREATE INDEX idx_chat_room_tags_tag ON chat_room_tags(tag);
CREATE INDEX idx_chat_rooms_last_message_at ON chat_rooms(last_message_at DESC);
CREATE UNIQUE INDEX idx_chat_rooms_dm_pair_key ON chat_rooms(dm_pair_key) WHERE type = 'dm';
CREATE INDEX idx_chat_rooms_public ON chat_rooms(is_public, last_message_at) WHERE type = 'group';
CREATE INDEX idx_chat_rooms_is_rp ON chat_rooms(is_rp) WHERE type = 'group';
CREATE UNIQUE INDEX idx_chat_rooms_system_kind ON chat_rooms(system_kind) WHERE system_kind IS NOT NULL;
CREATE INDEX idx_chat_rooms_archived_at ON chat_rooms(archived_at);
CREATE INDEX idx_chat_room_bans_user ON chat_room_bans(user_id);
CREATE INDEX idx_chat_banned_words_scope ON chat_banned_words(scope);
CREATE INDEX idx_chat_banned_words_room ON chat_banned_words(room_id);
CREATE INDEX idx_posts_user_id ON posts(user_id);
CREATE INDEX idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX idx_posts_corner ON posts(corner);
CREATE INDEX idx_posts_shared_content ON posts(shared_content_id, shared_content_type);
CREATE INDEX idx_post_media_post_id ON post_media(post_id);
CREATE INDEX idx_post_comments_post_id ON post_comments(post_id);
CREATE INDEX idx_post_comments_user_id ON post_comments(user_id);
CREATE INDEX idx_post_comments_parent_id ON post_comments(parent_id);
CREATE INDEX idx_post_comment_media_comment_id ON post_comment_media(comment_id);
CREATE INDEX idx_post_comment_likes_comment_id ON post_comment_likes(comment_id);
CREATE INDEX idx_post_polls_post_id ON post_polls(post_id);
CREATE INDEX idx_post_poll_options_poll_id ON post_poll_options(poll_id);
CREATE INDEX idx_post_poll_votes_option_id ON post_poll_votes(option_id);
CREATE INDEX idx_follows_following_id ON follows(following_id);
CREATE INDEX idx_follows_follower_id ON follows(follower_id);
CREATE INDEX idx_post_likes_post_id ON post_likes(post_id);
CREATE INDEX idx_reports_status ON reports(status, created_at DESC);
CREATE INDEX idx_reports_target ON reports(target_type, target_id);
CREATE INDEX idx_blocks_blocker_id ON blocks(blocker_id);
CREATE INDEX idx_blocks_blocked_id ON blocks(blocked_id);
CREATE INDEX idx_art_user_id ON art(user_id);
CREATE INDEX idx_art_corner ON art(corner);
CREATE INDEX idx_art_created_at ON art(created_at);
CREATE INDEX idx_art_gallery_id ON art(gallery_id);
CREATE INDEX idx_art_tags_tag ON art_tags(tag);
CREATE INDEX idx_art_likes_art_id ON art_likes(art_id);
CREATE INDEX idx_art_comments_art_id ON art_comments(art_id);
CREATE INDEX idx_art_comments_parent_id ON art_comments(parent_id);
CREATE INDEX idx_art_comment_media_comment_id ON art_comment_media(comment_id);
CREATE INDEX idx_art_comment_likes_comment_id ON art_comment_likes(comment_id);
CREATE INDEX idx_galleries_user_id ON galleries(user_id);
CREATE INDEX idx_mysteries_created_at ON mysteries(created_at DESC);
CREATE INDEX idx_mysteries_user_id ON mysteries(user_id);
CREATE INDEX idx_mystery_clues_mystery_id ON mystery_clues(mystery_id);
CREATE INDEX idx_mystery_clues_player_id ON mystery_clues(player_id);
CREATE INDEX idx_mystery_attempts_mystery_id ON mystery_attempts(mystery_id);
CREATE INDEX idx_mystery_attachments_mystery_id ON mystery_attachments(mystery_id);
CREATE INDEX idx_mystery_comments_mystery_id ON mystery_comments(mystery_id);
CREATE INDEX idx_mystery_comments_parent_id ON mystery_comments(parent_id);
CREATE INDEX idx_mystery_comment_media_comment_id ON mystery_comment_media(comment_id);
CREATE INDEX idx_mystery_comment_likes_comment_id ON mystery_comment_likes(comment_id);
CREATE INDEX idx_ships_created_at ON ships(created_at DESC);
CREATE INDEX idx_ships_user_id ON ships(user_id);
CREATE INDEX idx_ship_characters_ship_id ON ship_characters(ship_id);
CREATE INDEX idx_ship_characters_lookup ON ship_characters(series, character_id);
CREATE INDEX idx_ship_votes_ship_id ON ship_votes(ship_id);
CREATE INDEX idx_ship_comments_ship_id ON ship_comments(ship_id);
CREATE INDEX idx_ship_comments_parent_id ON ship_comments(parent_id);
CREATE INDEX idx_ship_comment_media_comment_id ON ship_comment_media(comment_id);
CREATE INDEX idx_ship_comment_likes_comment_id ON ship_comment_likes(comment_id);
CREATE INDEX idx_announcements_created_at ON announcements(created_at DESC);
CREATE INDEX idx_announcement_comments_announcement_id ON announcement_comments(announcement_id);
CREATE INDEX idx_announcement_comments_parent_id ON announcement_comments(parent_id);
CREATE INDEX idx_announcement_comment_media_comment_id ON announcement_comment_media(comment_id);
CREATE INDEX idx_announcement_comment_likes_comment_id ON announcement_comment_likes(comment_id);
CREATE INDEX idx_fanfics_user_id ON fanfics(user_id);
CREATE INDEX idx_fanfics_updated_at ON fanfics(updated_at DESC);
CREATE INDEX idx_fanfics_published_at ON fanfics(published_at DESC);
CREATE INDEX idx_fanfics_series ON fanfics(series);
CREATE INDEX idx_fanfics_rating ON fanfics(rating);
CREATE INDEX idx_fanfics_language ON fanfics(language);
CREATE INDEX idx_fanfics_status ON fanfics(status);
CREATE INDEX idx_fanfics_contains_lemons ON fanfics(contains_lemons);
CREATE INDEX idx_fanfic_chapters_fanfic_id ON fanfic_chapters(fanfic_id);
CREATE INDEX idx_fanfic_genres_genre ON fanfic_genres(genre);
CREATE INDEX idx_fanfic_characters_fanfic_id ON fanfic_characters(fanfic_id);
CREATE INDEX idx_fanfic_characters_lookup ON fanfic_characters(series, character_id);
CREATE INDEX idx_fanfic_characters_name ON fanfic_characters(character_name);
CREATE INDEX idx_fanfic_oc_characters_name ON fanfic_oc_characters(name);
CREATE INDEX idx_fanfic_favourites_fanfic_id ON fanfic_favourites(fanfic_id);
CREATE INDEX idx_fanfic_comments_fanfic_id ON fanfic_comments(fanfic_id);
CREATE INDEX idx_fanfic_comments_parent_id ON fanfic_comments(parent_id);
CREATE INDEX idx_fanfic_comment_media_comment_id ON fanfic_comment_media(comment_id);
CREATE INDEX idx_fanfic_comment_likes_comment_id ON fanfic_comment_likes(comment_id);
CREATE INDEX idx_fanfic_tags_tag ON fanfic_tags(tag);
CREATE INDEX idx_journals_user_id ON journals(user_id);
CREATE INDEX idx_journals_work ON journals(work);
CREATE INDEX idx_journals_last_author_activity ON journals(last_author_activity_at);
CREATE INDEX idx_journals_archived_at ON journals(archived_at);
CREATE INDEX idx_journal_comments_journal_id ON journal_comments(journal_id);
CREATE INDEX idx_journal_comments_parent_id ON journal_comments(parent_id);
CREATE INDEX idx_journal_comment_media_comment_id ON journal_comment_media(comment_id);
CREATE INDEX idx_journal_comment_likes_comment_id ON journal_comment_likes(comment_id);
CREATE INDEX idx_journal_follows_journal_id ON journal_follows(journal_id);
CREATE INDEX idx_giphy_favourites_user_created ON giphy_favourites(user_id, created_at DESC);
CREATE INDEX idx_game_rooms_status ON game_rooms(status);
CREATE INDEX idx_game_rooms_game_type_status ON game_rooms(game_type, status);
CREATE INDEX idx_game_room_players_user ON game_room_players(user_id);
CREATE INDEX idx_game_room_moves_room ON game_room_moves(room_id, ply);
CREATE INDEX idx_users_locked_at ON users(locked_at);
CREATE INDEX idx_secret_comments_secret_id ON secret_comments(secret_id);
CREATE INDEX idx_secret_comments_parent_id ON secret_comments(parent_id);
CREATE INDEX idx_secret_comment_media_comment_id ON secret_comment_media(comment_id);
CREATE INDEX idx_secret_comment_likes_comment_id ON secret_comment_likes(comment_id);

INSERT INTO fanfic_series (name) VALUES ('Umineko'), ('Higurashi'), ('Ciconia');

INSERT INTO fanfic_languages (name) VALUES
    ('English'), ('Spanish'), ('French'), ('German'), ('Portuguese'),
    ('Italian'), ('Japanese'), ('Chinese'), ('Korean'), ('Russian'),
    ('Polish'), ('Dutch'), ('Indonesian'), ('Turkish'), ('Arabic'),
    ('Thai'), ('Filipino'), ('Vietnamese'), ('Hindi');

INSERT INTO vanity_roles (id, label, color, is_system, sort_order) VALUES
    ('system_top_detective', 'True Detective', '#38bdf8', TRUE, 0),
    ('system_top_gm', 'Game Master', '#ef5350', TRUE, 1),
    ('system_witch_hunter', 'Witch Hunter', '#e89ec0', TRUE, 100);

-- +goose Down

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
CREATE EXTENSION IF NOT EXISTS citext;
