// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package journal

import (
	"context"
	"io"
	"umineko_city_of_books/internal/dto"
	"umineko_city_of_books/internal/journal/params"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ArchiveStale provides a mock function for the type MockService
func (_mock *MockService) ArchiveStale(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveStale")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ArchiveStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveStale'
type MockService_ArchiveStale_Call struct {
	*mock.Call
}

// ArchiveStale is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ArchiveStale(ctx interface{}) *MockService_ArchiveStale_Call {
	return &MockService_ArchiveStale_Call{Call: _e.mock.On("ArchiveStale", ctx)}
}

func (_c *MockService_ArchiveStale_Call) Run(run func(ctx context.Context)) *MockService_ArchiveStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ArchiveStale_Call) Return(n int, err error) *MockService_ArchiveStale_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_ArchiveStale_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockService_ArchiveStale_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComment provides a mock function for the type MockService
func (_mock *MockService) CreateComment(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, parentID *uuid.UUID, body string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, journalID, userID, parentID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, journalID, userID, parentID, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, journalID, userID, parentID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, journalID, userID, parentID, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockService_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - journalID uuid.UUID
//   - userID uuid.UUID
//   - parentID *uuid.UUID
//   - body string
func (_e *MockService_Expecter) CreateComment(ctx interface{}, journalID interface{}, userID interface{}, parentID interface{}, body interface{}) *MockService_CreateComment_Call {
	return &MockService_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, journalID, userID, parentID, body)}
}

func (_c *MockService_CreateComment_Call) Run(run func(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, parentID *uuid.UUID, body string)) *MockService_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_CreateComment_Call) Return(uUID uuid.UUID, err error) *MockService_CreateComment_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockService_CreateComment_Call) RunAndReturn(run func(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, parentID *uuid.UUID, body string) (uuid.UUID, error)) *MockService_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJournal provides a mock function for the type MockService
func (_mock *MockService) CreateJournal(ctx context.Context, userID uuid.UUID, req dto.CreateJournalRequest) (uuid.UUID, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateJournal")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateJournalRequest) (uuid.UUID, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateJournalRequest) uuid.UUID); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateJournalRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJournal'
type MockService_CreateJournal_Call struct {
	*mock.Call
}

// CreateJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.CreateJournalRequest
func (_e *MockService_Expecter) CreateJournal(ctx interface{}, userID interface{}, req interface{}) *MockService_CreateJournal_Call {
	return &MockService_CreateJournal_Call{Call: _e.mock.On("CreateJournal", ctx, userID, req)}
}

func (_c *MockService_CreateJournal_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.CreateJournalRequest)) *MockService_CreateJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.CreateJournalRequest
		if args[2] != nil {
			arg2 = args[2].(dto.CreateJournalRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateJournal_Call) Return(uUID uuid.UUID, err error) *MockService_CreateJournal_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockService_CreateJournal_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.CreateJournalRequest) (uuid.UUID, error)) *MockService_CreateJournal_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockService
func (_mock *MockService) DeleteComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockService_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) DeleteComment(ctx interface{}, id interface{}, userID interface{}) *MockService_DeleteComment_Call {
	return &MockService_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, id, userID)}
}

func (_c *MockService_DeleteComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteComment_Call) Return(err error) *MockService_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJournal provides a mock function for the type MockService
func (_mock *MockService) DeleteJournal(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJournal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJournal'
type MockService_DeleteJournal_Call struct {
	*mock.Call
}

// DeleteJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) DeleteJournal(ctx interface{}, id interface{}, userID interface{}) *MockService_DeleteJournal_Call {
	return &MockService_DeleteJournal_Call{Call: _e.mock.On("DeleteJournal", ctx, id, userID)}
}

func (_c *MockService_DeleteJournal_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_DeleteJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteJournal_Call) Return(err error) *MockService_DeleteJournal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_DeleteJournal_Call {
	_c.Call.Return(run)
	return _c
}

// FollowJournal provides a mock function for the type MockService
func (_mock *MockService) FollowJournal(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FollowJournal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_FollowJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FollowJournal'
type MockService_FollowJournal_Call struct {
	*mock.Call
}

// FollowJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) FollowJournal(ctx interface{}, id interface{}, userID interface{}) *MockService_FollowJournal_Call {
	return &MockService_FollowJournal_Call{Call: _e.mock.On("FollowJournal", ctx, id, userID)}
}

func (_c *MockService_FollowJournal_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_FollowJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_FollowJournal_Call) Return(err error) *MockService_FollowJournal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_FollowJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_FollowJournal_Call {
	_c.Call.Return(run)
	return _c
}

// GetJournalDetail provides a mock function for the type MockService
func (_mock *MockService) GetJournalDetail(ctx context.Context, id uuid.UUID, viewerID uuid.UUID) (*dto.JournalDetailResponse, error) {
	ret := _mock.Called(ctx, id, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetJournalDetail")
	}

	var r0 *dto.JournalDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.JournalDetailResponse, error)); ok {
		return returnFunc(ctx, id, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.JournalDetailResponse); ok {
		r0 = returnFunc(ctx, id, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetJournalDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJournalDetail'
type MockService_GetJournalDetail_Call struct {
	*mock.Call
}

// GetJournalDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) GetJournalDetail(ctx interface{}, id interface{}, viewerID interface{}) *MockService_GetJournalDetail_Call {
	return &MockService_GetJournalDetail_Call{Call: _e.mock.On("GetJournalDetail", ctx, id, viewerID)}
}

func (_c *MockService_GetJournalDetail_Call) Run(run func(ctx context.Context, id uuid.UUID, viewerID uuid.UUID)) *MockService_GetJournalDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetJournalDetail_Call) Return(journalDetailResponse *dto.JournalDetailResponse, err error) *MockService_GetJournalDetail_Call {
	_c.Call.Return(journalDetailResponse, err)
	return _c
}

func (_c *MockService_GetJournalDetail_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, viewerID uuid.UUID) (*dto.JournalDetailResponse, error)) *MockService_GetJournalDetail_Call {
	_c.Call.Return(run)
	return _c
}

// LikeComment provides a mock function for the type MockService
func (_mock *MockService) LikeComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for LikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_LikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeComment'
type MockService_LikeComment_Call struct {
	*mock.Call
}

// LikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) LikeComment(ctx interface{}, id interface{}, userID interface{}) *MockService_LikeComment_Call {
	return &MockService_LikeComment_Call{Call: _e.mock.On("LikeComment", ctx, id, userID)}
}

func (_c *MockService_LikeComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_LikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_LikeComment_Call) Return(err error) *MockService_LikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_LikeComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_LikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// ListFollowedByUser provides a mock function for the type MockService
func (_mock *MockService) ListFollowedByUser(ctx context.Context, followerID uuid.UUID, viewerID uuid.UUID, limit int, offset int) (*dto.JournalListResponse, error) {
	ret := _mock.Called(ctx, followerID, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListFollowedByUser")
	}

	var r0 *dto.JournalListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) (*dto.JournalListResponse, error)); ok {
		return returnFunc(ctx, followerID, viewerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) *dto.JournalListResponse); ok {
		r0 = returnFunc(ctx, followerID, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, followerID, viewerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListFollowedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFollowedByUser'
type MockService_ListFollowedByUser_Call struct {
	*mock.Call
}

// ListFollowedByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID uuid.UUID
//   - viewerID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListFollowedByUser(ctx interface{}, followerID interface{}, viewerID interface{}, limit interface{}, offset interface{}) *MockService_ListFollowedByUser_Call {
	return &MockService_ListFollowedByUser_Call{Call: _e.mock.On("ListFollowedByUser", ctx, followerID, viewerID, limit, offset)}
}

func (_c *MockService_ListFollowedByUser_Call) Run(run func(ctx context.Context, followerID uuid.UUID, viewerID uuid.UUID, limit int, offset int)) *MockService_ListFollowedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_ListFollowedByUser_Call) Return(journalListResponse *dto.JournalListResponse, err error) *MockService_ListFollowedByUser_Call {
	_c.Call.Return(journalListResponse, err)
	return _c
}

func (_c *MockService_ListFollowedByUser_Call) RunAndReturn(run func(ctx context.Context, followerID uuid.UUID, viewerID uuid.UUID, limit int, offset int) (*dto.JournalListResponse, error)) *MockService_ListFollowedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListJournals provides a mock function for the type MockService
func (_mock *MockService) ListJournals(ctx context.Context, p params.ListParams, viewerID uuid.UUID) (*dto.JournalListResponse, error) {
	ret := _mock.Called(ctx, p, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for ListJournals")
	}

	var r0 *dto.JournalListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, params.ListParams, uuid.UUID) (*dto.JournalListResponse, error)); ok {
		return returnFunc(ctx, p, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, params.ListParams, uuid.UUID) *dto.JournalListResponse); ok {
		r0 = returnFunc(ctx, p, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, params.ListParams, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, p, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListJournals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJournals'
type MockService_ListJournals_Call struct {
	*mock.Call
}

// ListJournals is a helper method to define mock.On call
//   - ctx context.Context
//   - p params.ListParams
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) ListJournals(ctx interface{}, p interface{}, viewerID interface{}) *MockService_ListJournals_Call {
	return &MockService_ListJournals_Call{Call: _e.mock.On("ListJournals", ctx, p, viewerID)}
}

func (_c *MockService_ListJournals_Call) Run(run func(ctx context.Context, p params.ListParams, viewerID uuid.UUID)) *MockService_ListJournals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 params.ListParams
		if args[1] != nil {
			arg1 = args[1].(params.ListParams)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListJournals_Call) Return(journalListResponse *dto.JournalListResponse, err error) *MockService_ListJournals_Call {
	_c.Call.Return(journalListResponse, err)
	return _c
}

func (_c *MockService_ListJournals_Call) RunAndReturn(run func(ctx context.Context, p params.ListParams, viewerID uuid.UUID) (*dto.JournalListResponse, error)) *MockService_ListJournals_Call {
	_c.Call.Return(run)
	return _c
}

// ListJournalsByUser provides a mock function for the type MockService
func (_mock *MockService) ListJournalsByUser(ctx context.Context, authorID uuid.UUID, viewerID uuid.UUID, limit int, offset int) (*dto.JournalListResponse, error) {
	ret := _mock.Called(ctx, authorID, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListJournalsByUser")
	}

	var r0 *dto.JournalListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) (*dto.JournalListResponse, error)); ok {
		return returnFunc(ctx, authorID, viewerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) *dto.JournalListResponse); ok {
		r0 = returnFunc(ctx, authorID, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, authorID, viewerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListJournalsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJournalsByUser'
type MockService_ListJournalsByUser_Call struct {
	*mock.Call
}

// ListJournalsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID uuid.UUID
//   - viewerID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListJournalsByUser(ctx interface{}, authorID interface{}, viewerID interface{}, limit interface{}, offset interface{}) *MockService_ListJournalsByUser_Call {
	return &MockService_ListJournalsByUser_Call{Call: _e.mock.On("ListJournalsByUser", ctx, authorID, viewerID, limit, offset)}
}

func (_c *MockService_ListJournalsByUser_Call) Run(run func(ctx context.Context, authorID uuid.UUID, viewerID uuid.UUID, limit int, offset int)) *MockService_ListJournalsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_ListJournalsByUser_Call) Return(journalListResponse *dto.JournalListResponse, err error) *MockService_ListJournalsByUser_Call {
	_c.Call.Return(journalListResponse, err)
	return _c
}

func (_c *MockService_ListJournalsByUser_Call) RunAndReturn(run func(ctx context.Context, authorID uuid.UUID, viewerID uuid.UUID, limit int, offset int) (*dto.JournalListResponse, error)) *MockService_ListJournalsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnfollowJournal provides a mock function for the type MockService
func (_mock *MockService) UnfollowJournal(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnfollowJournal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UnfollowJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnfollowJournal'
type MockService_UnfollowJournal_Call struct {
	*mock.Call
}

// UnfollowJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) UnfollowJournal(ctx interface{}, id interface{}, userID interface{}) *MockService_UnfollowJournal_Call {
	return &MockService_UnfollowJournal_Call{Call: _e.mock.On("UnfollowJournal", ctx, id, userID)}
}

func (_c *MockService_UnfollowJournal_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_UnfollowJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UnfollowJournal_Call) Return(err error) *MockService_UnfollowJournal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UnfollowJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_UnfollowJournal_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeComment provides a mock function for the type MockService
func (_mock *MockService) UnlikeComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnlikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UnlikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeComment'
type MockService_UnlikeComment_Call struct {
	*mock.Call
}

// UnlikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) UnlikeComment(ctx interface{}, id interface{}, userID interface{}) *MockService_UnlikeComment_Call {
	return &MockService_UnlikeComment_Call{Call: _e.mock.On("UnlikeComment", ctx, id, userID)}
}

func (_c *MockService_UnlikeComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_UnlikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UnlikeComment_Call) Return(err error) *MockService_UnlikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UnlikeComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_UnlikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockService
func (_mock *MockService) UpdateComment(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, userID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockService_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockService_Expecter) UpdateComment(ctx interface{}, id interface{}, userID interface{}, body interface{}) *MockService_UpdateComment_Call {
	return &MockService_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, id, userID, body)}
}

func (_c *MockService_UpdateComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string)) *MockService_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateComment_Call) Return(err error) *MockService_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error) *MockService_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJournal provides a mock function for the type MockService
func (_mock *MockService) UpdateJournal(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.CreateJournalRequest) error {
	ret := _mock.Called(ctx, id, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJournal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.CreateJournalRequest) error); ok {
		r0 = returnFunc(ctx, id, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJournal'
type MockService_UpdateJournal_Call struct {
	*mock.Call
}

// UpdateJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - req dto.CreateJournalRequest
func (_e *MockService_Expecter) UpdateJournal(ctx interface{}, id interface{}, userID interface{}, req interface{}) *MockService_UpdateJournal_Call {
	return &MockService_UpdateJournal_Call{Call: _e.mock.On("UpdateJournal", ctx, id, userID, req)}
}

func (_c *MockService_UpdateJournal_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.CreateJournalRequest)) *MockService_UpdateJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.CreateJournalRequest
		if args[3] != nil {
			arg3 = args[3].(dto.CreateJournalRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateJournal_Call) Return(err error) *MockService_UpdateJournal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.CreateJournalRequest) error) *MockService_UpdateJournal_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCommentMedia provides a mock function for the type MockService
func (_mock *MockService) UploadCommentMedia(ctx context.Context, commentID uuid.UUID, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader) (*dto.PostMediaResponse, error) {
	ret := _mock.Called(ctx, commentID, userID, contentType, fileSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for UploadCommentMedia")
	}

	var r0 *dto.PostMediaResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, io.Reader) (*dto.PostMediaResponse, error)); ok {
		return returnFunc(ctx, commentID, userID, contentType, fileSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, io.Reader) *dto.PostMediaResponse); ok {
		r0 = returnFunc(ctx, commentID, userID, contentType, fileSize, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PostMediaResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, commentID, userID, contentType, fileSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCommentMedia'
type MockService_UploadCommentMedia_Call struct {
	*mock.Call
}

// UploadCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - userID uuid.UUID
//   - contentType string
//   - fileSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) UploadCommentMedia(ctx interface{}, commentID interface{}, userID interface{}, contentType interface{}, fileSize interface{}, reader interface{}) *MockService_UploadCommentMedia_Call {
	return &MockService_UploadCommentMedia_Call{Call: _e.mock.On("UploadCommentMedia", ctx, commentID, userID, contentType, fileSize, reader)}
}

func (_c *MockService_UploadCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader)) *MockService_UploadCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_UploadCommentMedia_Call) Return(postMediaResponse *dto.PostMediaResponse, err error) *MockService_UploadCommentMedia_Call {
	_c.Call.Return(postMediaResponse, err)
	return _c
}

func (_c *MockService_UploadCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader) (*dto.PostMediaResponse, error)) *MockService_UploadCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}
