// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package follow

import (
	"context"
	"umineko_city_of_books/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Follow provides a mock function for the type MockService
func (_mock *MockService) Follow(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID) error {
	ret := _mock.Called(ctx, followerID, followingID)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, followerID, followingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type MockService_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID uuid.UUID
//   - followingID uuid.UUID
func (_e *MockService_Expecter) Follow(ctx interface{}, followerID interface{}, followingID interface{}) *MockService_Follow_Call {
	return &MockService_Follow_Call{Call: _e.mock.On("Follow", ctx, followerID, followingID)}
}

func (_c *MockService_Follow_Call) Run(run func(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID)) *MockService_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Follow_Call) Return(err error) *MockService_Follow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Follow_Call) RunAndReturn(run func(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID) error) *MockService_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowStats provides a mock function for the type MockService
func (_mock *MockService) GetFollowStats(ctx context.Context, userID uuid.UUID, viewerID uuid.UUID) (*dto.FollowStatsResponse, error) {
	ret := _mock.Called(ctx, userID, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowStats")
	}

	var r0 *dto.FollowStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.FollowStatsResponse, error)); ok {
		return returnFunc(ctx, userID, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.FollowStatsResponse); ok {
		r0 = returnFunc(ctx, userID, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.FollowStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetFollowStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowStats'
type MockService_GetFollowStats_Call struct {
	*mock.Call
}

// GetFollowStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) GetFollowStats(ctx interface{}, userID interface{}, viewerID interface{}) *MockService_GetFollowStats_Call {
	return &MockService_GetFollowStats_Call{Call: _e.mock.On("GetFollowStats", ctx, userID, viewerID)}
}

func (_c *MockService_GetFollowStats_Call) Run(run func(ctx context.Context, userID uuid.UUID, viewerID uuid.UUID)) *MockService_GetFollowStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetFollowStats_Call) Return(followStatsResponse *dto.FollowStatsResponse, err error) *MockService_GetFollowStats_Call {
	_c.Call.Return(followStatsResponse, err)
	return _c
}

func (_c *MockService_GetFollowStats_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, viewerID uuid.UUID) (*dto.FollowStatsResponse, error)) *MockService_GetFollowStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowers provides a mock function for the type MockService
func (_mock *MockService) GetFollowers(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]dto.UserResponse, int, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowers")
	}

	var r0 []dto.UserResponse
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]dto.UserResponse, int, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []dto.UserResponse); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_GetFollowers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowers'
type MockService_GetFollowers_Call struct {
	*mock.Call
}

// GetFollowers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) GetFollowers(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockService_GetFollowers_Call {
	return &MockService_GetFollowers_Call{Call: _e.mock.On("GetFollowers", ctx, userID, limit, offset)}
}

func (_c *MockService_GetFollowers_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockService_GetFollowers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_GetFollowers_Call) Return(userResponses []dto.UserResponse, n int, err error) *MockService_GetFollowers_Call {
	_c.Call.Return(userResponses, n, err)
	return _c
}

func (_c *MockService_GetFollowers_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]dto.UserResponse, int, error)) *MockService_GetFollowers_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowing provides a mock function for the type MockService
func (_mock *MockService) GetFollowing(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]dto.UserResponse, int, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowing")
	}

	var r0 []dto.UserResponse
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]dto.UserResponse, int, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []dto.UserResponse); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_GetFollowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowing'
type MockService_GetFollowing_Call struct {
	*mock.Call
}

// GetFollowing is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) GetFollowing(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockService_GetFollowing_Call {
	return &MockService_GetFollowing_Call{Call: _e.mock.On("GetFollowing", ctx, userID, limit, offset)}
}

func (_c *MockService_GetFollowing_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockService_GetFollowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_GetFollowing_Call) Return(userResponses []dto.UserResponse, n int, err error) *MockService_GetFollowing_Call {
	_c.Call.Return(userResponses, n, err)
	return _c
}

func (_c *MockService_GetFollowing_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]dto.UserResponse, int, error)) *MockService_GetFollowing_Call {
	_c.Call.Return(run)
	return _c
}

// GetMutualFollowers provides a mock function for the type MockService
func (_mock *MockService) GetMutualFollowers(ctx context.Context, userID uuid.UUID) ([]dto.UserResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMutualFollowers")
	}

	var r0 []dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]dto.UserResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []dto.UserResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetMutualFollowers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMutualFollowers'
type MockService_GetMutualFollowers_Call struct {
	*mock.Call
}

// GetMutualFollowers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) GetMutualFollowers(ctx interface{}, userID interface{}) *MockService_GetMutualFollowers_Call {
	return &MockService_GetMutualFollowers_Call{Call: _e.mock.On("GetMutualFollowers", ctx, userID)}
}

func (_c *MockService_GetMutualFollowers_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_GetMutualFollowers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetMutualFollowers_Call) Return(userResponses []dto.UserResponse, err error) *MockService_GetMutualFollowers_Call {
	_c.Call.Return(userResponses, err)
	return _c
}

func (_c *MockService_GetMutualFollowers_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]dto.UserResponse, error)) *MockService_GetMutualFollowers_Call {
	_c.Call.Return(run)
	return _c
}

// IsFollowing provides a mock function for the type MockService
func (_mock *MockService) IsFollowing(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, followerID, followingID)

	if len(ret) == 0 {
		panic("no return value specified for IsFollowing")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, followerID, followingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, followerID, followingID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, followerID, followingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_IsFollowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFollowing'
type MockService_IsFollowing_Call struct {
	*mock.Call
}

// IsFollowing is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID uuid.UUID
//   - followingID uuid.UUID
func (_e *MockService_Expecter) IsFollowing(ctx interface{}, followerID interface{}, followingID interface{}) *MockService_IsFollowing_Call {
	return &MockService_IsFollowing_Call{Call: _e.mock.On("IsFollowing", ctx, followerID, followingID)}
}

func (_c *MockService_IsFollowing_Call) Run(run func(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID)) *MockService_IsFollowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_IsFollowing_Call) Return(b bool, err error) *MockService_IsFollowing_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockService_IsFollowing_Call) RunAndReturn(run func(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID) (bool, error)) *MockService_IsFollowing_Call {
	_c.Call.Return(run)
	return _c
}

// Unfollow provides a mock function for the type MockService
func (_mock *MockService) Unfollow(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID) error {
	ret := _mock.Called(ctx, followerID, followingID)

	if len(ret) == 0 {
		panic("no return value specified for Unfollow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, followerID, followingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Unfollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unfollow'
type MockService_Unfollow_Call struct {
	*mock.Call
}

// Unfollow is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID uuid.UUID
//   - followingID uuid.UUID
func (_e *MockService_Expecter) Unfollow(ctx interface{}, followerID interface{}, followingID interface{}) *MockService_Unfollow_Call {
	return &MockService_Unfollow_Call{Call: _e.mock.On("Unfollow", ctx, followerID, followingID)}
}

func (_c *MockService_Unfollow_Call) Run(run func(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID)) *MockService_Unfollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Unfollow_Call) Return(err error) *MockService_Unfollow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Unfollow_Call) RunAndReturn(run func(ctx context.Context, followerID uuid.UUID, followingID uuid.UUID) error) *MockService_Unfollow_Call {
	_c.Call.Return(run)
	return _c
}
