// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package profile

import (
	"context"
	"io"
	"umineko_city_of_books/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockService
func (_mock *MockService) ChangePassword(ctx context.Context, userID uuid.UUID, req dto.ChangePasswordRequest) error {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ChangePasswordRequest) error); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.ChangePasswordRequest
func (_e *MockService_Expecter) ChangePassword(ctx interface{}, userID interface{}, req interface{}) *MockService_ChangePassword_Call {
	return &MockService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, req)}
}

func (_c *MockService_ChangePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.ChangePasswordRequest)) *MockService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.ChangePasswordRequest
		if args[2] != nil {
			arg2 = args[2].(dto.ChangePasswordRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ChangePassword_Call) Return(err error) *MockService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.ChangePasswordRequest) error) *MockService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function for the type MockService
func (_mock *MockService) DeleteAccount(ctx context.Context, userID uuid.UUID, req dto.DeleteAccountRequest) error {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.DeleteAccountRequest) error); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.DeleteAccountRequest
func (_e *MockService_Expecter) DeleteAccount(ctx interface{}, userID interface{}, req interface{}) *MockService_DeleteAccount_Call {
	return &MockService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, userID, req)}
}

func (_c *MockService_DeleteAccount_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.DeleteAccountRequest)) *MockService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.DeleteAccountRequest
		if args[2] != nil {
			arg2 = args[2].(dto.DeleteAccountRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteAccount_Call) Return(err error) *MockService_DeleteAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteAccount_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.DeleteAccountRequest) error) *MockService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivity provides a mock function for the type MockService
func (_mock *MockService) GetActivity(ctx context.Context, username string, limit int, offset int) (*dto.ActivityListResponse, error) {
	ret := _mock.Called(ctx, username, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetActivity")
	}

	var r0 *dto.ActivityListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (*dto.ActivityListResponse, error)); ok {
		return returnFunc(ctx, username, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) *dto.ActivityListResponse); ok {
		r0 = returnFunc(ctx, username, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ActivityListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, username, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivity'
type MockService_GetActivity_Call struct {
	*mock.Call
}

// GetActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - limit int
//   - offset int
func (_e *MockService_Expecter) GetActivity(ctx interface{}, username interface{}, limit interface{}, offset interface{}) *MockService_GetActivity_Call {
	return &MockService_GetActivity_Call{Call: _e.mock.On("GetActivity", ctx, username, limit, offset)}
}

func (_c *MockService_GetActivity_Call) Run(run func(ctx context.Context, username string, limit int, offset int)) *MockService_GetActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_GetActivity_Call) Return(activityListResponse *dto.ActivityListResponse, err error) *MockService_GetActivity_Call {
	_c.Call.Return(activityListResponse, err)
	return _c
}

func (_c *MockService_GetActivity_Call) RunAndReturn(run func(ctx context.Context, username string, limit int, offset int) (*dto.ActivityListResponse, error)) *MockService_GetActivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type MockService
func (_mock *MockService) GetProfile(ctx context.Context, username string, viewerID uuid.UUID) (*dto.UserProfileResponse, error) {
	ret := _mock.Called(ctx, username, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *dto.UserProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*dto.UserProfileResponse, error)); ok {
		return returnFunc(ctx, username, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *dto.UserProfileResponse); ok {
		r0 = returnFunc(ctx, username, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, username, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) GetProfile(ctx interface{}, username interface{}, viewerID interface{}) *MockService_GetProfile_Call {
	return &MockService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, username, viewerID)}
}

func (_c *MockService_GetProfile_Call) Run(run func(ctx context.Context, username string, viewerID uuid.UUID)) *MockService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetProfile_Call) Return(userProfileResponse *dto.UserProfileResponse, err error) *MockService_GetProfile_Call {
	_c.Call.Return(userProfileResponse, err)
	return _c
}

func (_c *MockService_GetProfile_Call) RunAndReturn(run func(ctx context.Context, username string, viewerID uuid.UUID) (*dto.UserProfileResponse, error)) *MockService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublicUsers provides a mock function for the type MockService
func (_mock *MockService) ListPublicUsers(ctx context.Context) ([]dto.UserResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPublicUsers")
	}

	var r0 []dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.UserResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.UserResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListPublicUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublicUsers'
type MockService_ListPublicUsers_Call struct {
	*mock.Call
}

// ListPublicUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListPublicUsers(ctx interface{}) *MockService_ListPublicUsers_Call {
	return &MockService_ListPublicUsers_Call{Call: _e.mock.On("ListPublicUsers", ctx)}
}

func (_c *MockService_ListPublicUsers_Call) Run(run func(ctx context.Context)) *MockService_ListPublicUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListPublicUsers_Call) Return(userResponses []dto.UserResponse, err error) *MockService_ListPublicUsers_Call {
	_c.Call.Return(userResponses, err)
	return _c
}

func (_c *MockService_ListPublicUsers_Call) RunAndReturn(run func(ctx context.Context) ([]dto.UserResponse, error)) *MockService_ListPublicUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function for the type MockService
func (_mock *MockService) SearchUsers(ctx context.Context, query string, limit int) ([]dto.UserResponse, error) {
	ret := _mock.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []dto.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]dto.UserResponse, error)); ok {
		return returnFunc(ctx, query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []dto.UserResponse); ok {
		r0 = returnFunc(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockService_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
func (_e *MockService_Expecter) SearchUsers(ctx interface{}, query interface{}, limit interface{}) *MockService_SearchUsers_Call {
	return &MockService_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, limit)}
}

func (_c *MockService_SearchUsers_Call) Run(run func(ctx context.Context, query string, limit int)) *MockService_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SearchUsers_Call) Return(userResponses []dto.UserResponse, err error) *MockService_SearchUsers_Call {
	_c.Call.Return(userResponses, err)
	return _c
}

func (_c *MockService_SearchUsers_Call) RunAndReturn(run func(ctx context.Context, query string, limit int) ([]dto.UserResponse, error)) *MockService_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockService
func (_mock *MockService) UpdateProfile(ctx context.Context, userID uuid.UUID, req dto.UpdateProfileRequest) error {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateProfileRequest) error); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.UpdateProfileRequest
func (_e *MockService_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MockService_UpdateProfile_Call {
	return &MockService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MockService_UpdateProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.UpdateProfileRequest)) *MockService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.UpdateProfileRequest
		if args[2] != nil {
			arg2 = args[2].(dto.UpdateProfileRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateProfile_Call) Return(err error) *MockService_UpdateProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.UpdateProfileRequest) error) *MockService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadAvatar provides a mock function for the type MockService
func (_mock *MockService) UploadAvatar(ctx context.Context, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, userID, contentType, fileSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, userID, contentType, fileSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, userID, contentType, fileSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, userID, contentType, fileSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAvatar'
type MockService_UploadAvatar_Call struct {
	*mock.Call
}

// UploadAvatar is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - contentType string
//   - fileSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) UploadAvatar(ctx interface{}, userID interface{}, contentType interface{}, fileSize interface{}, reader interface{}) *MockService_UploadAvatar_Call {
	return &MockService_UploadAvatar_Call{Call: _e.mock.On("UploadAvatar", ctx, userID, contentType, fileSize, reader)}
}

func (_c *MockService_UploadAvatar_Call) Run(run func(ctx context.Context, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader)) *MockService_UploadAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 io.Reader
		if args[4] != nil {
			arg4 = args[4].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_UploadAvatar_Call) Return(s string, err error) *MockService_UploadAvatar_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_UploadAvatar_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader) (string, error)) *MockService_UploadAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// UploadBanner provides a mock function for the type MockService
func (_mock *MockService) UploadBanner(ctx context.Context, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, userID, contentType, fileSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for UploadBanner")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, userID, contentType, fileSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, userID, contentType, fileSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, userID, contentType, fileSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadBanner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadBanner'
type MockService_UploadBanner_Call struct {
	*mock.Call
}

// UploadBanner is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - contentType string
//   - fileSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) UploadBanner(ctx interface{}, userID interface{}, contentType interface{}, fileSize interface{}, reader interface{}) *MockService_UploadBanner_Call {
	return &MockService_UploadBanner_Call{Call: _e.mock.On("UploadBanner", ctx, userID, contentType, fileSize, reader)}
}

func (_c *MockService_UploadBanner_Call) Run(run func(ctx context.Context, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader)) *MockService_UploadBanner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 io.Reader
		if args[4] != nil {
			arg4 = args[4].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_UploadBanner_Call) Return(s string, err error) *MockService_UploadBanner_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_UploadBanner_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader) (string, error)) *MockService_UploadBanner_Call {
	_c.Call.Return(run)
	return _c
}
