// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chat

import (
	"context"
	"io"
	"umineko_city_of_books/internal/dto"
	"umineko_city_of_books/internal/role"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateGroupRoom provides a mock function for the type MockService
func (_mock *MockService) CreateGroupRoom(ctx context.Context, creatorID uuid.UUID, req dto.CreateGroupRoomRequest) (*dto.ChatRoomResponse, error) {
	ret := _mock.Called(ctx, creatorID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupRoom")
	}

	var r0 *dto.ChatRoomResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateGroupRoomRequest) (*dto.ChatRoomResponse, error)); ok {
		return returnFunc(ctx, creatorID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateGroupRoomRequest) *dto.ChatRoomResponse); ok {
		r0 = returnFunc(ctx, creatorID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatRoomResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateGroupRoomRequest) error); ok {
		r1 = returnFunc(ctx, creatorID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateGroupRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupRoom'
type MockService_CreateGroupRoom_Call struct {
	*mock.Call
}

// CreateGroupRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID uuid.UUID
//   - req dto.CreateGroupRoomRequest
func (_e *MockService_Expecter) CreateGroupRoom(ctx interface{}, creatorID interface{}, req interface{}) *MockService_CreateGroupRoom_Call {
	return &MockService_CreateGroupRoom_Call{Call: _e.mock.On("CreateGroupRoom", ctx, creatorID, req)}
}

func (_c *MockService_CreateGroupRoom_Call) Run(run func(ctx context.Context, creatorID uuid.UUID, req dto.CreateGroupRoomRequest)) *MockService_CreateGroupRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.CreateGroupRoomRequest
		if args[2] != nil {
			arg2 = args[2].(dto.CreateGroupRoomRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateGroupRoom_Call) Return(chatRoomResponse *dto.ChatRoomResponse, err error) *MockService_CreateGroupRoom_Call {
	_c.Call.Return(chatRoomResponse, err)
	return _c
}

func (_c *MockService_CreateGroupRoom_Call) RunAndReturn(run func(ctx context.Context, creatorID uuid.UUID, req dto.CreateGroupRoomRequest) (*dto.ChatRoomResponse, error)) *MockService_CreateGroupRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChat provides a mock function for the type MockService
func (_mock *MockService) DeleteChat(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChat'
type MockService_DeleteChat_Call struct {
	*mock.Call
}

// DeleteChat is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) DeleteChat(ctx interface{}, roomID interface{}, userID interface{}) *MockService_DeleteChat_Call {
	return &MockService_DeleteChat_Call{Call: _e.mock.On("DeleteChat", ctx, roomID, userID)}
}

func (_c *MockService_DeleteChat_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_DeleteChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteChat_Call) Return(err error) *MockService_DeleteChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteChat_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error) *MockService_DeleteChat_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureSystemRooms provides a mock function for the type MockService
func (_mock *MockService) EnsureSystemRooms(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSystemRooms")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_EnsureSystemRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSystemRooms'
type MockService_EnsureSystemRooms_Call struct {
	*mock.Call
}

// EnsureSystemRooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) EnsureSystemRooms(ctx interface{}) *MockService_EnsureSystemRooms_Call {
	return &MockService_EnsureSystemRooms_Call{Call: _e.mock.On("EnsureSystemRooms", ctx)}
}

func (_c *MockService_EnsureSystemRooms_Call) Run(run func(ctx context.Context)) *MockService_EnsureSystemRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_EnsureSystemRooms_Call) Return(err error) *MockService_EnsureSystemRooms_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_EnsureSystemRooms_Call) RunAndReturn(run func(ctx context.Context) error) *MockService_EnsureSystemRooms_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function for the type MockService
func (_mock *MockService) GetMembers(ctx context.Context, viewerID uuid.UUID, roomID uuid.UUID) ([]dto.ChatRoomMemberResponse, error) {
	ret := _mock.Called(ctx, viewerID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []dto.ChatRoomMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]dto.ChatRoomMemberResponse, error)); ok {
		return returnFunc(ctx, viewerID, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []dto.ChatRoomMemberResponse); ok {
		r0 = returnFunc(ctx, viewerID, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ChatRoomMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, viewerID, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type MockService_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID uuid.UUID
//   - roomID uuid.UUID
func (_e *MockService_Expecter) GetMembers(ctx interface{}, viewerID interface{}, roomID interface{}) *MockService_GetMembers_Call {
	return &MockService_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, viewerID, roomID)}
}

func (_c *MockService_GetMembers_Call) Run(run func(ctx context.Context, viewerID uuid.UUID, roomID uuid.UUID)) *MockService_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetMembers_Call) Return(chatRoomMemberResponses []dto.ChatRoomMemberResponse, err error) *MockService_GetMembers_Call {
	_c.Call.Return(chatRoomMemberResponses, err)
	return _c
}

func (_c *MockService_GetMembers_Call) RunAndReturn(run func(ctx context.Context, viewerID uuid.UUID, roomID uuid.UUID) ([]dto.ChatRoomMemberResponse, error)) *MockService_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockService
func (_mock *MockService) GetMessages(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, limit int, offset int) (*dto.ChatMessageListResponse, error) {
	ret := _mock.Called(ctx, userID, roomID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 *dto.ChatMessageListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) (*dto.ChatMessageListResponse, error)); ok {
		return returnFunc(ctx, userID, roomID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) *dto.ChatMessageListResponse); ok {
		r0 = returnFunc(ctx, userID, roomID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatMessageListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, userID, roomID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockService_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) GetMessages(ctx interface{}, userID interface{}, roomID interface{}, limit interface{}, offset interface{}) *MockService_GetMessages_Call {
	return &MockService_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, userID, roomID, limit, offset)}
}

func (_c *MockService_GetMessages_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, limit int, offset int)) *MockService_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_GetMessages_Call) Return(chatMessageListResponse *dto.ChatMessageListResponse, err error) *MockService_GetMessages_Call {
	_c.Call.Return(chatMessageListResponse, err)
	return _c
}

func (_c *MockService_GetMessages_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, limit int, offset int) (*dto.ChatMessageListResponse, error)) *MockService_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessagesBefore provides a mock function for the type MockService
func (_mock *MockService) GetMessagesBefore(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, before string, limit int) (*dto.ChatMessageListResponse, error) {
	ret := _mock.Called(ctx, userID, roomID, before, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesBefore")
	}

	var r0 *dto.ChatMessageListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int) (*dto.ChatMessageListResponse, error)); ok {
		return returnFunc(ctx, userID, roomID, before, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int) *dto.ChatMessageListResponse); ok {
		r0 = returnFunc(ctx, userID, roomID, before, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatMessageListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int) error); ok {
		r1 = returnFunc(ctx, userID, roomID, before, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetMessagesBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesBefore'
type MockService_GetMessagesBefore_Call struct {
	*mock.Call
}

// GetMessagesBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roomID uuid.UUID
//   - before string
//   - limit int
func (_e *MockService_Expecter) GetMessagesBefore(ctx interface{}, userID interface{}, roomID interface{}, before interface{}, limit interface{}) *MockService_GetMessagesBefore_Call {
	return &MockService_GetMessagesBefore_Call{Call: _e.mock.On("GetMessagesBefore", ctx, userID, roomID, before, limit)}
}

func (_c *MockService_GetMessagesBefore_Call) Run(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, before string, limit int)) *MockService_GetMessagesBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_GetMessagesBefore_Call) Return(chatMessageListResponse *dto.ChatMessageListResponse, err error) *MockService_GetMessagesBefore_Call {
	_c.Call.Return(chatMessageListResponse, err)
	return _c
}

func (_c *MockService_GetMessagesBefore_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, roomID uuid.UUID, before string, limit int) (*dto.ChatMessageListResponse, error)) *MockService_GetMessagesBefore_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomsByUser provides a mock function for the type MockService
func (_mock *MockService) GetRoomsByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomsByUser")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetRoomsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomsByUser'
type MockService_GetRoomsByUser_Call struct {
	*mock.Call
}

// GetRoomsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) GetRoomsByUser(ctx interface{}, userID interface{}) *MockService_GetRoomsByUser_Call {
	return &MockService_GetRoomsByUser_Call{Call: _e.mock.On("GetRoomsByUser", ctx, userID)}
}

func (_c *MockService_GetRoomsByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_GetRoomsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetRoomsByUser_Call) Return(uUIDs []uuid.UUID, err error) *MockService_GetRoomsByUser_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockService_GetRoomsByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)) *MockService_GetRoomsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreadCount provides a mock function for the type MockService
func (_mock *MockService) GetUnreadCount(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadCount'
type MockService_GetUnreadCount_Call struct {
	*mock.Call
}

// GetUnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) GetUnreadCount(ctx interface{}, userID interface{}) *MockService_GetUnreadCount_Call {
	return &MockService_GetUnreadCount_Call{Call: _e.mock.On("GetUnreadCount", ctx, userID)}
}

func (_c *MockService_GetUnreadCount_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_GetUnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetUnreadCount_Call) Return(n int, err error) *MockService_GetUnreadCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_GetUnreadCount_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int, error)) *MockService_GetUnreadCount_Call {
	_c.Call.Return(run)
	return _c
}

// IsRoomMuted provides a mock function for the type MockService
func (_mock *MockService) IsRoomMuted(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsRoomMuted")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, roomID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_IsRoomMuted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRoomMuted'
type MockService_IsRoomMuted_Call struct {
	*mock.Call
}

// IsRoomMuted is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) IsRoomMuted(ctx interface{}, roomID interface{}, userID interface{}) *MockService_IsRoomMuted_Call {
	return &MockService_IsRoomMuted_Call{Call: _e.mock.On("IsRoomMuted", ctx, roomID, userID)}
}

func (_c *MockService_IsRoomMuted_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_IsRoomMuted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_IsRoomMuted_Call) Return(b bool, err error) *MockService_IsRoomMuted_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockService_IsRoomMuted_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (bool, error)) *MockService_IsRoomMuted_Call {
	_c.Call.Return(run)
	return _c
}

// JoinRoom provides a mock function for the type MockService
func (_mock *MockService) JoinRoom(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (*dto.ChatRoomResponse, error) {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for JoinRoom")
	}

	var r0 *dto.ChatRoomResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.ChatRoomResponse, error)); ok {
		return returnFunc(ctx, roomID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.ChatRoomResponse); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatRoomResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_JoinRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinRoom'
type MockService_JoinRoom_Call struct {
	*mock.Call
}

// JoinRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) JoinRoom(ctx interface{}, roomID interface{}, userID interface{}) *MockService_JoinRoom_Call {
	return &MockService_JoinRoom_Call{Call: _e.mock.On("JoinRoom", ctx, roomID, userID)}
}

func (_c *MockService_JoinRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_JoinRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_JoinRoom_Call) Return(chatRoomResponse *dto.ChatRoomResponse, err error) *MockService_JoinRoom_Call {
	_c.Call.Return(chatRoomResponse, err)
	return _c
}

func (_c *MockService_JoinRoom_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) (*dto.ChatRoomResponse, error)) *MockService_JoinRoom_Call {
	_c.Call.Return(run)
	return _c
}

// KickMember provides a mock function for the type MockService
func (_mock *MockService) KickMember(ctx context.Context, hostID uuid.UUID, roomID uuid.UUID, targetID uuid.UUID) error {
	ret := _mock.Called(ctx, hostID, roomID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for KickMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, hostID, roomID, targetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_KickMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KickMember'
type MockService_KickMember_Call struct {
	*mock.Call
}

// KickMember is a helper method to define mock.On call
//   - ctx context.Context
//   - hostID uuid.UUID
//   - roomID uuid.UUID
//   - targetID uuid.UUID
func (_e *MockService_Expecter) KickMember(ctx interface{}, hostID interface{}, roomID interface{}, targetID interface{}) *MockService_KickMember_Call {
	return &MockService_KickMember_Call{Call: _e.mock.On("KickMember", ctx, hostID, roomID, targetID)}
}

func (_c *MockService_KickMember_Call) Run(run func(ctx context.Context, hostID uuid.UUID, roomID uuid.UUID, targetID uuid.UUID)) *MockService_KickMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_KickMember_Call) Return(err error) *MockService_KickMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_KickMember_Call) RunAndReturn(run func(ctx context.Context, hostID uuid.UUID, roomID uuid.UUID, targetID uuid.UUID) error) *MockService_KickMember_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveRoom provides a mock function for the type MockService
func (_mock *MockService) LeaveRoom(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_LeaveRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveRoom'
type MockService_LeaveRoom_Call struct {
	*mock.Call
}

// LeaveRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) LeaveRoom(ctx interface{}, roomID interface{}, userID interface{}) *MockService_LeaveRoom_Call {
	return &MockService_LeaveRoom_Call{Call: _e.mock.On("LeaveRoom", ctx, roomID, userID)}
}

func (_c *MockService_LeaveRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_LeaveRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_LeaveRoom_Call) Return(err error) *MockService_LeaveRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_LeaveRoom_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error) *MockService_LeaveRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublicRooms provides a mock function for the type MockService
func (_mock *MockService) ListPublicRooms(ctx context.Context, search string, isRPOnly bool, tag string, viewerID uuid.UUID, limit int, offset int) (*dto.ChatRoomListResponse, error) {
	ret := _mock.Called(ctx, search, isRPOnly, tag, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPublicRooms")
	}

	var r0 *dto.ChatRoomListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, string, uuid.UUID, int, int) (*dto.ChatRoomListResponse, error)); ok {
		return returnFunc(ctx, search, isRPOnly, tag, viewerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, string, uuid.UUID, int, int) *dto.ChatRoomListResponse); ok {
		r0 = returnFunc(ctx, search, isRPOnly, tag, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatRoomListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, string, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, search, isRPOnly, tag, viewerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListPublicRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublicRooms'
type MockService_ListPublicRooms_Call struct {
	*mock.Call
}

// ListPublicRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - isRPOnly bool
//   - tag string
//   - viewerID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListPublicRooms(ctx interface{}, search interface{}, isRPOnly interface{}, tag interface{}, viewerID interface{}, limit interface{}, offset interface{}) *MockService_ListPublicRooms_Call {
	return &MockService_ListPublicRooms_Call{Call: _e.mock.On("ListPublicRooms", ctx, search, isRPOnly, tag, viewerID, limit, offset)}
}

func (_c *MockService_ListPublicRooms_Call) Run(run func(ctx context.Context, search string, isRPOnly bool, tag string, viewerID uuid.UUID, limit int, offset int)) *MockService_ListPublicRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(uuid.UUID)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockService_ListPublicRooms_Call) Return(chatRoomListResponse *dto.ChatRoomListResponse, err error) *MockService_ListPublicRooms_Call {
	_c.Call.Return(chatRoomListResponse, err)
	return _c
}

func (_c *MockService_ListPublicRooms_Call) RunAndReturn(run func(ctx context.Context, search string, isRPOnly bool, tag string, viewerID uuid.UUID, limit int, offset int) (*dto.ChatRoomListResponse, error)) *MockService_ListPublicRooms_Call {
	_c.Call.Return(run)
	return _c
}

// ListRooms provides a mock function for the type MockService
func (_mock *MockService) ListRooms(ctx context.Context, userID uuid.UUID) (*dto.ChatRoomListResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListRooms")
	}

	var r0 *dto.ChatRoomListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.ChatRoomListResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.ChatRoomListResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatRoomListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRooms'
type MockService_ListRooms_Call struct {
	*mock.Call
}

// ListRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) ListRooms(ctx interface{}, userID interface{}) *MockService_ListRooms_Call {
	return &MockService_ListRooms_Call{Call: _e.mock.On("ListRooms", ctx, userID)}
}

func (_c *MockService_ListRooms_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_ListRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListRooms_Call) Return(chatRoomListResponse *dto.ChatRoomListResponse, err error) *MockService_ListRooms_Call {
	_c.Call.Return(chatRoomListResponse, err)
	return _c
}

func (_c *MockService_ListRooms_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*dto.ChatRoomListResponse, error)) *MockService_ListRooms_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserGroupRooms provides a mock function for the type MockService
func (_mock *MockService) ListUserGroupRooms(ctx context.Context, userID uuid.UUID, search string, isRPOnly bool, tag string, role string, limit int, offset int) (*dto.ChatRoomListResponse, error) {
	ret := _mock.Called(ctx, userID, search, isRPOnly, tag, role, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUserGroupRooms")
	}

	var r0 *dto.ChatRoomListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, bool, string, string, int, int) (*dto.ChatRoomListResponse, error)); ok {
		return returnFunc(ctx, userID, search, isRPOnly, tag, role, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, bool, string, string, int, int) *dto.ChatRoomListResponse); ok {
		r0 = returnFunc(ctx, userID, search, isRPOnly, tag, role, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatRoomListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, bool, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, search, isRPOnly, tag, role, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListUserGroupRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserGroupRooms'
type MockService_ListUserGroupRooms_Call struct {
	*mock.Call
}

// ListUserGroupRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - search string
//   - isRPOnly bool
//   - tag string
//   - role string
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListUserGroupRooms(ctx interface{}, userID interface{}, search interface{}, isRPOnly interface{}, tag interface{}, role interface{}, limit interface{}, offset interface{}) *MockService_ListUserGroupRooms_Call {
	return &MockService_ListUserGroupRooms_Call{Call: _e.mock.On("ListUserGroupRooms", ctx, userID, search, isRPOnly, tag, role, limit, offset)}
}

func (_c *MockService_ListUserGroupRooms_Call) Run(run func(ctx context.Context, userID uuid.UUID, search string, isRPOnly bool, tag string, role string, limit int, offset int)) *MockService_ListUserGroupRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		var arg7 int
		if args[7] != nil {
			arg7 = args[7].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockService_ListUserGroupRooms_Call) Return(chatRoomListResponse *dto.ChatRoomListResponse, err error) *MockService_ListUserGroupRooms_Call {
	_c.Call.Return(chatRoomListResponse, err)
	return _c
}

func (_c *MockService_ListUserGroupRooms_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, search string, isRPOnly bool, tag string, role string, limit int, offset int) (*dto.ChatRoomListResponse, error)) *MockService_ListUserGroupRooms_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockService
func (_mock *MockService) MarkRead(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockService_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) MarkRead(ctx interface{}, roomID interface{}, userID interface{}) *MockService_MarkRead_Call {
	return &MockService_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, roomID, userID)}
}

func (_c *MockService_MarkRead_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_MarkRead_Call) Return(err error) *MockService_MarkRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_MarkRead_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error) *MockService_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveDMRoom provides a mock function for the type MockService
func (_mock *MockService) ResolveDMRoom(ctx context.Context, senderID uuid.UUID, recipientID uuid.UUID) (*dto.ResolveDMResponse, error) {
	ret := _mock.Called(ctx, senderID, recipientID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDMRoom")
	}

	var r0 *dto.ResolveDMResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.ResolveDMResponse, error)); ok {
		return returnFunc(ctx, senderID, recipientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.ResolveDMResponse); ok {
		r0 = returnFunc(ctx, senderID, recipientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ResolveDMResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, senderID, recipientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ResolveDMRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDMRoom'
type MockService_ResolveDMRoom_Call struct {
	*mock.Call
}

// ResolveDMRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - recipientID uuid.UUID
func (_e *MockService_Expecter) ResolveDMRoom(ctx interface{}, senderID interface{}, recipientID interface{}) *MockService_ResolveDMRoom_Call {
	return &MockService_ResolveDMRoom_Call{Call: _e.mock.On("ResolveDMRoom", ctx, senderID, recipientID)}
}

func (_c *MockService_ResolveDMRoom_Call) Run(run func(ctx context.Context, senderID uuid.UUID, recipientID uuid.UUID)) *MockService_ResolveDMRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ResolveDMRoom_Call) Return(resolveDMResponse *dto.ResolveDMResponse, err error) *MockService_ResolveDMRoom_Call {
	_c.Call.Return(resolveDMResponse, err)
	return _c
}

func (_c *MockService_ResolveDMRoom_Call) RunAndReturn(run func(ctx context.Context, senderID uuid.UUID, recipientID uuid.UUID) (*dto.ResolveDMResponse, error)) *MockService_ResolveDMRoom_Call {
	_c.Call.Return(run)
	return _c
}

// SendDMMessage provides a mock function for the type MockService
func (_mock *MockService) SendDMMessage(ctx context.Context, senderID uuid.UUID, recipientID uuid.UUID, body string) (*dto.SendDMResponse, error) {
	ret := _mock.Called(ctx, senderID, recipientID, body)

	if len(ret) == 0 {
		panic("no return value specified for SendDMMessage")
	}

	var r0 *dto.SendDMResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*dto.SendDMResponse, error)); ok {
		return returnFunc(ctx, senderID, recipientID, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *dto.SendDMResponse); ok {
		r0 = returnFunc(ctx, senderID, recipientID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SendDMResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, senderID, recipientID, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SendDMMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDMMessage'
type MockService_SendDMMessage_Call struct {
	*mock.Call
}

// SendDMMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - recipientID uuid.UUID
//   - body string
func (_e *MockService_Expecter) SendDMMessage(ctx interface{}, senderID interface{}, recipientID interface{}, body interface{}) *MockService_SendDMMessage_Call {
	return &MockService_SendDMMessage_Call{Call: _e.mock.On("SendDMMessage", ctx, senderID, recipientID, body)}
}

func (_c *MockService_SendDMMessage_Call) Run(run func(ctx context.Context, senderID uuid.UUID, recipientID uuid.UUID, body string)) *MockService_SendDMMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SendDMMessage_Call) Return(sendDMResponse *dto.SendDMResponse, err error) *MockService_SendDMMessage_Call {
	_c.Call.Return(sendDMResponse, err)
	return _c
}

func (_c *MockService_SendDMMessage_Call) RunAndReturn(run func(ctx context.Context, senderID uuid.UUID, recipientID uuid.UUID, body string) (*dto.SendDMResponse, error)) *MockService_SendDMMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockService
func (_mock *MockService) SendMessage(ctx context.Context, senderID uuid.UUID, roomID uuid.UUID, req dto.SendMessageRequest) (*dto.ChatMessageResponse, error) {
	ret := _mock.Called(ctx, senderID, roomID, req)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *dto.ChatMessageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.SendMessageRequest) (*dto.ChatMessageResponse, error)); ok {
		return returnFunc(ctx, senderID, roomID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.SendMessageRequest) *dto.ChatMessageResponse); ok {
		r0 = returnFunc(ctx, senderID, roomID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatMessageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.SendMessageRequest) error); ok {
		r1 = returnFunc(ctx, senderID, roomID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID uuid.UUID
//   - roomID uuid.UUID
//   - req dto.SendMessageRequest
func (_e *MockService_Expecter) SendMessage(ctx interface{}, senderID interface{}, roomID interface{}, req interface{}) *MockService_SendMessage_Call {
	return &MockService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, senderID, roomID, req)}
}

func (_c *MockService_SendMessage_Call) Run(run func(ctx context.Context, senderID uuid.UUID, roomID uuid.UUID, req dto.SendMessageRequest)) *MockService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.SendMessageRequest
		if args[3] != nil {
			arg3 = args[3].(dto.SendMessageRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SendMessage_Call) Return(chatMessageResponse *dto.ChatMessageResponse, err error) *MockService_SendMessage_Call {
	_c.Call.Return(chatMessageResponse, err)
	return _c
}

func (_c *MockService_SendMessage_Call) RunAndReturn(run func(ctx context.Context, senderID uuid.UUID, roomID uuid.UUID, req dto.SendMessageRequest) (*dto.ChatMessageResponse, error)) *MockService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SetRoomMuted provides a mock function for the type MockService
func (_mock *MockService) SetRoomMuted(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, muted bool) error {
	ret := _mock.Called(ctx, roomID, userID, muted)

	if len(ret) == 0 {
		panic("no return value specified for SetRoomMuted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, roomID, userID, muted)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetRoomMuted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRoomMuted'
type MockService_SetRoomMuted_Call struct {
	*mock.Call
}

// SetRoomMuted is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - muted bool
func (_e *MockService_Expecter) SetRoomMuted(ctx interface{}, roomID interface{}, userID interface{}, muted interface{}) *MockService_SetRoomMuted_Call {
	return &MockService_SetRoomMuted_Call{Call: _e.mock.On("SetRoomMuted", ctx, roomID, userID, muted)}
}

func (_c *MockService_SetRoomMuted_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, muted bool)) *MockService_SetRoomMuted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SetRoomMuted_Call) Return(err error) *MockService_SetRoomMuted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetRoomMuted_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, muted bool) error) *MockService_SetRoomMuted_Call {
	_c.Call.Return(run)
	return _c
}

// SyncSystemRoomMembership provides a mock function for the type MockService
func (_mock *MockService) SyncSystemRoomMembership(ctx context.Context, userID uuid.UUID, newRole role.Role) error {
	ret := _mock.Called(ctx, userID, newRole)

	if len(ret) == 0 {
		panic("no return value specified for SyncSystemRoomMembership")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, role.Role) error); ok {
		r0 = returnFunc(ctx, userID, newRole)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SyncSystemRoomMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncSystemRoomMembership'
type MockService_SyncSystemRoomMembership_Call struct {
	*mock.Call
}

// SyncSystemRoomMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - newRole role.Role
func (_e *MockService_Expecter) SyncSystemRoomMembership(ctx interface{}, userID interface{}, newRole interface{}) *MockService_SyncSystemRoomMembership_Call {
	return &MockService_SyncSystemRoomMembership_Call{Call: _e.mock.On("SyncSystemRoomMembership", ctx, userID, newRole)}
}

func (_c *MockService_SyncSystemRoomMembership_Call) Run(run func(ctx context.Context, userID uuid.UUID, newRole role.Role)) *MockService_SyncSystemRoomMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 role.Role
		if args[2] != nil {
			arg2 = args[2].(role.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SyncSystemRoomMembership_Call) Return(err error) *MockService_SyncSystemRoomMembership_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SyncSystemRoomMembership_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, newRole role.Role) error) *MockService_SyncSystemRoomMembership_Call {
	_c.Call.Return(run)
	return _c
}

// UploadMessageMedia provides a mock function for the type MockService
func (_mock *MockService) UploadMessageMedia(ctx context.Context, messageID uuid.UUID, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader) (*dto.PostMediaResponse, error) {
	ret := _mock.Called(ctx, messageID, userID, contentType, fileSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for UploadMessageMedia")
	}

	var r0 *dto.PostMediaResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, io.Reader) (*dto.PostMediaResponse, error)); ok {
		return returnFunc(ctx, messageID, userID, contentType, fileSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, io.Reader) *dto.PostMediaResponse); ok {
		r0 = returnFunc(ctx, messageID, userID, contentType, fileSize, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PostMediaResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, messageID, userID, contentType, fileSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadMessageMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadMessageMedia'
type MockService_UploadMessageMedia_Call struct {
	*mock.Call
}

// UploadMessageMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID uuid.UUID
//   - userID uuid.UUID
//   - contentType string
//   - fileSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) UploadMessageMedia(ctx interface{}, messageID interface{}, userID interface{}, contentType interface{}, fileSize interface{}, reader interface{}) *MockService_UploadMessageMedia_Call {
	return &MockService_UploadMessageMedia_Call{Call: _e.mock.On("UploadMessageMedia", ctx, messageID, userID, contentType, fileSize, reader)}
}

func (_c *MockService_UploadMessageMedia_Call) Run(run func(ctx context.Context, messageID uuid.UUID, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader)) *MockService_UploadMessageMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_UploadMessageMedia_Call) Return(postMediaResponse *dto.PostMediaResponse, err error) *MockService_UploadMessageMedia_Call {
	_c.Call.Return(postMediaResponse, err)
	return _c
}

func (_c *MockService_UploadMessageMedia_Call) RunAndReturn(run func(ctx context.Context, messageID uuid.UUID, userID uuid.UUID, contentType string, fileSize int64, reader io.Reader) (*dto.PostMediaResponse, error)) *MockService_UploadMessageMedia_Call {
	_c.Call.Return(run)
	return _c
}
